import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{execFileSync,spawnSync}from'node:child_process';
const base='66b0eda121cd9aee40857a2d691e25b18737f63e',script=path.resolve('scripts/integrate-reporting-completion.mjs');
const inputs=['data/catalog.json','data/corpus/source.json','data/corpus/guide.json','data/corpus/example.json','data/coverage/research-questions.json','data/coverage/assessments.json','data/coverage/mapping-overrides.json','data/research/foundations.json','data/research-questions.json','data/coverage/research-criteria.json','data/coverage/subsector-profiles.json','data/coverage/subsector-screening.json'];
const proposals=['reporting-completion-2026-09-19.json','reporting-completion-inventory-2026-09-19.json','reporting-completion-example-2026-09-19.json','reporting-completion-retrieval-2026-09-19.json'].map(f=>`data/research/${f}`);
const read=f=>JSON.parse(fs.readFileSync(f)),bytes=root=>inputs.map(f=>[f,fs.readFileSync(path.join(root,f))]);
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aa-int118-'));for(const f of [...inputs,...proposals]){fs.mkdirSync(path.dirname(path.join(root,f)),{recursive:true});fs.writeFileSync(path.join(root,f),proposals.includes(f)?fs.readFileSync(f):execFileSync('git',['show',`${base}:${f}`],{maxBuffer:32*1024*1024}));}return root;}
const run=(root,...args)=>spawnSync(process.execPath,[script,'--current',...args],{cwd:root,env:{...process.env,REPORTING_COMPLETION_ROOT:root},encoding:'utf8'});
test('current reporting integration reuses publisher records without changing prior source rights, questions or mappings',()=>{const root=fixture();try{const before=bytes(root),oldSources=read(path.join(root,'data/corpus/source.json')),oldQuestions=read(path.join(root,'data/coverage/research-questions.json')).questions,oldMappings=read(path.join(root,'data/coverage/mapping-overrides.json')).records;let result=run(root,'--dry-run');assert.equal(result.status,0,result.stderr);assert.deepEqual(bytes(root),before);result=run(root);assert.equal(result.status,0,result.stderr);
const sources=read(path.join(root,'data/corpus/source.json'));assert.equal(sources.length,oldSources.length+1);for(const old of oldSources){const actual=structuredClone(sources.find(s=>s.id===old.id));if(actual.data.supplemental_reviews?.some(r=>r.batch==='reporting-completion-us')){actual.data.supplemental_reviews=actual.data.supplemental_reviews.filter(r=>r.batch!=='reporting-completion-us');if(!Object.hasOwn(old.data,'supplemental_reviews'))delete actual.data.supplemental_reviews;}assert.deepEqual(actual,old,old.id);}
const questions=read(path.join(root,'data/coverage/research-questions.json')).questions;for(const old of oldQuestions)assert.deepEqual(questions.find(q=>q.id===old.id),old,old.id);const mappings=read(path.join(root,'data/coverage/mapping-overrides.json')).records;for(const[id,row]of Object.entries(oldMappings))assert.deepEqual(mappings[id],row,id);assert.equal(read(path.join(root,'data/catalog.json')).corpus_version,'2026-09-19.12416');const first=bytes(root);result=run(root);assert.equal(result.status,0,result.stderr);assert.deepEqual(bytes(root),first);
}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('current reporting integration rejects unknown editions and late review or retrieval conflicts before any write',()=>{for(const defect of ['edition','review','retrieval','foundation']){const root=fixture();try{if(defect!=='edition'){const r=run(root);assert.equal(r.status,0,r.stderr);}const file=defect==='edition'?'data/catalog.json':defect==='review'?'data/corpus/source.json':defect==='retrieval'?'data/research-questions.json':'data/research/foundations.json',value=read(path.join(root,file));if(defect==='edition')value.corpus_version='2099-01-01.1';if(defect==='review')value.find(s=>s.id==='src_1os761s').data.supplemental_reviews.find(r=>r.batch==='reporting-completion-us').locator='Conflicting locator';if(defect==='retrieval')value.find(f=>f.id==='rq-reporting-completion-close').expected_ids=['guide-q-leases'];if(defect==='foundation')value.reporting_completion_us.note='Conflicting source provenance';fs.writeFileSync(path.join(root,file),JSON.stringify(value,null,2)+'\n');const before=bytes(root),result=run(root);assert.notEqual(result.status,0,defect);assert.deepEqual(bytes(root),before,defect);}finally{fs.rmSync(root,{recursive:true,force:true});}}});
test('legacy reporting applicator refuses newer supplemental reviews before writing',()=>{const root=fixture();try{let result=run(root);assert.equal(result.status,0,result.stderr);for(const file of ['reporting-foundations.json','reporting-foundations-example.json','reporting-foundations-assessments.json','reporting-foundations-inventory.json'])fs.copyFileSync(`data/research/${file}`,path.join(root,'data/research',file));const before=bytes(root);result=spawnSync(process.execPath,[path.resolve('scripts/apply-reporting-foundations.mjs'),'--integrate-into-newer-corpus'],{cwd:root,env:{...process.env,REPORTING_FOUNDATIONS_ROOT:root},encoding:'utf8'});assert.notEqual(result.status,0);assert.match(result.stderr,/src_fasb_202010: existing canonical record differs; refusing overwrite/);assert.deepEqual(bytes(root),before);}finally{fs.rmSync(root,{recursive:true,force:true});}});
