import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {applyToRoot,packetFile} from '../scripts/integrate-accommodation-food.mjs';
const base='e6e5d6f2ea3cf67649f31bd8a7db74340bab773a';
const files=['data/catalog.json',...fs.readdirSync('data/corpus').filter(n=>n.endsWith('.json')).map(n=>`data/corpus/${n}`),'data/coverage/research-questions.json','data/coverage/assessments.json','data/coverage/mapping-overrides.json','data/coverage/research-criteria.json','data/coverage/subsector-profiles.json','data/coverage/subsector-screening.json','data/research-questions.json'];
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'accommodation-food-current-'));for(const file of files){fs.mkdirSync(path.dirname(path.join(dir,file)),{recursive:true});fs.writeFileSync(path.join(dir,file),execFileSync('git',['show',`${base}:${file}`],{maxBuffer:64*1024*1024}));}for(const f of [packetFile,'data/research/accommodation-food-retrieval-2026-09-19.json']){fs.mkdirSync(path.dirname(path.join(dir,f)),{recursive:true});fs.copyFileSync(f,path.join(dir,f));}return dir;}
const snapshot=dir=>new Map(files.map(f=>[f,fs.readFileSync(path.join(dir,f))]));
const read=(dir,file)=>JSON.parse(fs.readFileSync(path.join(dir,file)));
test('accommodation-food current integration preserves all prior records, questions and source rights and replays byte-stably',()=>{const dir=fixture();try{const before=snapshot(dir);applyToRoot(dir,{currentMode:true});for(const file of files.filter(f=>f.startsWith('data/corpus/'))){const after=read(dir,file);for(const row of JSON.parse(before.get(file)))assert.deepEqual(after.find(r=>r.id===row.id),row,row.id);}for(const[file,key]of [['data/coverage/research-questions.json','questions'],['data/coverage/assessments.json','assessments']]){const after=read(dir,file)[key];for(const row of JSON.parse(before.get(file))[key])assert.deepEqual(after.find(r=>r.id===row.id),row);}assert.equal(read(dir,'data/catalog.json').corpus_version,'2026-09-19.12425');assert.equal(read(dir,'data/coverage/research-criteria.json').population.named_research_questions,337);const first=snapshot(dir);applyToRoot(dir,{currentMode:true});for(const[f,b]of first)assert.deepEqual(fs.readFileSync(path.join(dir,f)),b,f);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('accommodation-food current integration refuses a late retrieval conflict or unknown edition before writing',()=>{for(const type of ['retrieval','edition']){const dir=fixture();try{const f=type==='retrieval'?'data/research-questions.json':'data/catalog.json',v=read(dir,f);if(type==='retrieval')v.push({...JSON.parse(fs.readFileSync('data/research/accommodation-food-retrieval-2026-09-19.json'))[0],expected_ids:['wrong']});else v.corpus_version='unknown';fs.writeFileSync(path.join(dir,f),JSON.stringify(v,null,2)+'\n');const before=snapshot(dir);assert.throws(()=>applyToRoot(dir,{currentMode:true}));for(const[f,b]of before)assert.deepEqual(fs.readFileSync(path.join(dir,f)),b,f);}finally{fs.rmSync(dir,{recursive:true,force:true});}}});
