import { divisionSchema, ledgerBenchLinks, productSchema, semver, stringArray, trackSchema } from "./schema-common";

export const ledgerBenchProgramSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: ledgerBenchLinks.program_schema,
  title: "LedgerBench benchmark-program record",
  description: "The public measurement claim, products, tracks, divisions, metrics, integrity rules, governance, launch gates, and precedent record for LedgerBench.",
  type: "object",
  additionalProperties: false,
  required: [
    "id", "version", "status", "title", "subtitle", "reviewed_at", "mission",
    "measurement_claim", "unit_under_test", "unit_of_evaluation", "non_claims",
    "products", "tracks", "divisions", "task_universe", "capability_dimensions",
    "primary_metric", "hard_gates", "required_reporting", "task_admission",
    "split_policy", "statistical_principles", "submission_program", "governance",
    "lifecycle", "launch_gates", "first_release", "precedents", "provenance", "licenses",
  ],
  properties: {
    id: { type: "string", const: "ledgerbench" },
    version: { type: "string", pattern: semver },
    status: { type: "string", enum: ["proposed", "preview", "active", "saturated", "retired", "archived"] },
    title: { type: "string" },
    subtitle: { type: "string" },
    reviewed_at: { type: "string", format: "date" },
    mission: { type: "string" },
    measurement_claim: { type: "string" },
    unit_under_test: { type: "string" },
    unit_of_evaluation: {
      type: "object",
      additionalProperties: false,
      required: ["name", "definition", "terminal_states"],
      properties: {
        name: { type: "string", const: "episode" },
        definition: { type: "string" },
        terminal_states: stringArray,
      },
    },
    non_claims: stringArray,
    products: { type: "array", minItems: 4, items: productSchema },
    tracks: { type: "array", minItems: 5, items: trackSchema },
    divisions: { type: "array", minItems: 3, items: divisionSchema },
    task_universe: {
      type: "object",
      additionalProperties: false,
      required: [
        "domains", "behaviors", "evidence_conditions", "time_horizons",
        "authority_exposures", "consequence_classes", "operating_context_fields",
      ],
      properties: {
        domains: stringArray,
        behaviors: stringArray,
        evidence_conditions: stringArray,
        time_horizons: stringArray,
        authority_exposures: stringArray,
        consequence_classes: stringArray,
        operating_context_fields: stringArray,
      },
    },
    capability_dimensions: {
      type: "array",
      minItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "name", "question"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          question: { type: "string" },
        },
      },
    },
    primary_metric: {
      type: "object",
      additionalProperties: false,
      required: ["id", "name", "abbreviation", "definition", "episode_acceptance_conditions"],
      properties: {
        id: { type: "string", const: "accepted-work-rate" },
        name: { type: "string", const: "Accepted Work Rate" },
        abbreviation: { type: "string", const: "AWR" },
        definition: { type: "string" },
        episode_acceptance_conditions: stringArray,
      },
    },
    hard_gates: stringArray,
    required_reporting: stringArray,
    task_admission: {
      type: "array",
      minItems: 10,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["order", "id", "name", "gate"],
        properties: {
          order: { type: "integer", minimum: 1 },
          id: { type: "string" },
          name: { type: "string" },
          gate: { type: "string" },
        },
      },
    },
    split_policy: {
      type: "object",
      additionalProperties: false,
      required: ["primary_splits_are_exclusive", "splits", "grouping_keys"],
      properties: {
        primary_splits_are_exclusive: { type: "boolean", const: true },
        splits: {
          type: "array",
          minItems: 8,
          items: {
            type: "object",
            additionalProperties: false,
            required: ["id", "visibility", "unseen_factor"],
            properties: {
              id: { type: "string" },
              visibility: { type: "string", enum: ["public", "private"] },
              unseen_factor: { type: "string" },
            },
          },
        },
        grouping_keys: stringArray,
      },
    },
    statistical_principles: stringArray,
    submission_program: {
      type: "object",
      required: ["statuses", "official_default", "submission_limits"],
      additionalProperties: false,
      properties: {
        statuses: {
          type: "array",
          minItems: 4,
          items: {
            type: "object",
            additionalProperties: false,
            required: ["id", "meaning"],
            properties: { id: { type: "string" }, meaning: { type: "string" } },
          },
        },
        official_default: stringArray,
        submission_limits: stringArray,
      },
    },
    governance: {
      type: "array",
      minItems: 7,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "name", "responsibility"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          responsibility: { type: "string" },
        },
      },
    },
    lifecycle: stringArray,
    launch_gates: stringArray,
    first_release: { type: "object" },
    precedents: {
      type: "array",
      minItems: 10,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "name", "source", "practice_adopted"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          source: { type: "string", format: "uri" },
          practice_adopted: { type: "string" },
        },
      },
    },
    provenance: { type: "object" },
    licenses: { type: "object" },
  },
} as const;
