import { ledgerBenchProgram } from "../../data/ledgerbench-program.mjs";
import { ledgerBenchLinks } from "./schema-common";

function bullets(items: readonly string[]) {
  return items.map((item) => `- ${item}`);
}

export function renderLedgerBenchMarkdown() {
  return [
    `# ${ledgerBenchProgram.title}`,
    "",
    `> ${ledgerBenchProgram.subtitle}`,
    "",
    `Status: **${ledgerBenchProgram.status}**. Version ${ledgerBenchProgram.version}. Reviewed ${ledgerBenchProgram.reviewed_at}.`,
    "",
    "## Mission",
    "",
    ledgerBenchProgram.mission,
    "",
    "## Measurement claim",
    "",
    ledgerBenchProgram.measurement_claim,
    "",
    `**Unit under test:** ${ledgerBenchProgram.unit_under_test}`,
    "",
    `**Unit of evaluation:** ${ledgerBenchProgram.unit_of_evaluation.definition}`,
    "",
    "## What the result does not establish",
    "",
    ...bullets(ledgerBenchProgram.non_claims),
    "",
    "## Program products",
    "",
    ...ledgerBenchProgram.products.flatMap((product) => [
      `### ${product.name}`,
      "",
      `**Question:** ${product.question}`,
      "",
      product.result,
      "",
      `Competitive ranking: ${product.ranking ? "yes" : "no"}.`,
      "",
    ]),
    "## Tracks",
    "",
    ...ledgerBenchProgram.tracks.flatMap((track) => [
      `### ${track.name}`,
      "",
      `Status: ${track.status}. Human horizon: ${track.human_horizon}.`,
      "",
      track.purpose,
      "",
    ]),
    "## Divisions",
    "",
    ...ledgerBenchProgram.divisions.flatMap((division) => [
      `### ${division.name}`,
      "",
      division.purpose,
      "",
      `- Human intervention: ${division.human_intervention}`,
      `- Comparability: ${division.comparability}`,
      "",
    ]),
    "## Task universe",
    "",
    `### Domains`,
    "",
    ...bullets(ledgerBenchProgram.task_universe.domains),
    "",
    "### Evidence conditions",
    "",
    ...bullets(ledgerBenchProgram.task_universe.evidence_conditions),
    "",
    "### Human time horizons",
    "",
    ...bullets(ledgerBenchProgram.task_universe.time_horizons),
    "",
    "## Primary metric",
    "",
    `### ${ledgerBenchProgram.primary_metric.name} (${ledgerBenchProgram.primary_metric.abbreviation})`,
    "",
    ledgerBenchProgram.primary_metric.definition,
    "",
    ...bullets(ledgerBenchProgram.primary_metric.episode_acceptance_conditions),
    "",
    "## Hard gates",
    "",
    ...bullets(ledgerBenchProgram.hard_gates),
    "",
    "## Capability dimensions",
    "",
    ...ledgerBenchProgram.capability_dimensions.map((dimension) => (
      `- **${dimension.name}:** ${dimension.question}`
    )),
    "",
    "## Task admission",
    "",
    ...ledgerBenchProgram.task_admission.map((stage) => (
      `${stage.order}. **${stage.name}.** ${stage.gate}`
    )),
    "",
    "## Evaluation integrity",
    "",
    `Primary splits are exclusive: ${ledgerBenchProgram.split_policy.primary_splits_are_exclusive ? "yes" : "no"}.`,
    "",
    ...ledgerBenchProgram.split_policy.splits.map((split) => (
      `- **${split.id}:** ${split.visibility}; ${split.unseen_factor}.`
    )),
    "",
    "## Statistical principles",
    "",
    ...bullets(ledgerBenchProgram.statistical_principles),
    "",
    "## Submission verification",
    "",
    ...ledgerBenchProgram.submission_program.statuses.map((status) => (
      `- **${status.id}:** ${status.meaning}`
    )),
    "",
    "## Governance",
    "",
    ...ledgerBenchProgram.governance.map((body) => (
      `- **${body.name}:** ${body.responsibility}`
    )),
    "",
    "## Launch gates",
    "",
    ...bullets(ledgerBenchProgram.launch_gates),
    "",
    "## Proposed first release",
    "",
    `Reporting basis: ${ledgerBenchProgram.first_release.reporting_basis}.`,
    "",
    ...ledgerBenchProgram.first_release.episode_plan.map((item) => (
      `- ${item.track}: ${"official_hidden_episodes" in item ? item.official_hidden_episodes : "official_hidden_sequences" in item ? item.official_hidden_sequences : item.public_episodes}`
    )),
    "",
    "## Benchmark-program precedents",
    "",
    ...ledgerBenchProgram.precedents.map((precedent) => (
      `- [${precedent.name}](${precedent.source}): ${precedent.practice_adopted}`
    )),
    "",
    "## Machine contracts",
    "",
    `- Program API: ${ledgerBenchLinks.api}`,
    `- Program schema: ${ledgerBenchLinks.program_schema}`,
    `- Episode schema: ${ledgerBenchLinks.episode_schema}`,
    `- Candidate-result schema: ${ledgerBenchLinks.result_schema}`,
    `- Submission schema: ${ledgerBenchLinks.submission_schema}`,
    "",
    "## Rights and review",
    "",
    `- Program record and factual metadata: ${ledgerBenchProgram.licenses.program_record_and_factual_metadata}`,
    `- Original explanatory content: ${ledgerBenchProgram.licenses.original_explanatory_content}`,
    `- Schemas and software: ${ledgerBenchProgram.licenses.schemas_and_software}`,
    `- Review: ${ledgerBenchProgram.provenance.review_process}`,
    "",
  ].join("\n");
}
