import type { EvidenceClassificationId } from "./content-contract";
import { packs } from "../data/open-source-platform.mjs";

export const bankReconciliationTutorialId = "bank-reconciliation-guided-lesson";
export const bankReconciliationTutorialVersion = "1.0.0";
export const bankReconciliationTutorialPreparedAt = "2026-08-27";

const bankReconciliationPack = packs.find((pack) => pack.id === "bank-reconciliation");

if (!bankReconciliationPack) {
  throw new Error("The bank-reconciliation tutorial requires the canonical bank-reconciliation pack.");
}

const fixture = bankReconciliationPack.fixture;
const referenceOutput = bankReconciliationPack.reference_output;

export const bankReconciliationTutorial = {
  id: bankReconciliationTutorialId,
  version: bankReconciliationTutorialVersion,
  title: "Tutorial: prepare and review a synthetic bank reconciliation",
  description:
    "Work through one clean-room bank reconciliation from source register to reviewer disposition, then practice the correct stop when required evidence is missing or belongs to the wrong period.",
  prepared_at: bankReconciliationTutorialPreparedAt,
  review_status: "maintainer-review-pending",
  review_note:
    "Maintainer review and automated integrity checks only. Subject-matter, independent, professional, audit, certification, assurance, and production review are not claimed.",
  primary_mode: "tutorial",
  evidence_classification: "implementation-pattern" as EvidenceClassificationId,
  intended_learner:
    "Accounting practitioners, reviewers, control owners, and agent builders who want one complete, accounting-native example of governed agent preparation and human review.",
  estimated_minutes: 25,
  prerequisites: [
    "Be able to distinguish agent preparation from an accountable person's review and approval.",
    "Use only the bundled fictional fixture; do not substitute employer, client, engagement, bank, vendor, customer, employee, or taxpayer data.",
    "Treat every amount as whole US dollars for this lesson and preserve the named entity, account, period, and source IDs.",
  ],
  learning_objectives: [
    "Freeze a bounded evidence register before preparing a reconciliation.",
    "Reperform the adjusted-bank calculation and compare it with adjusted book cash.",
    "Preserve reconciling-item support, exceptions, and action limits in a prepared workpaper.",
    "Stop rather than force a tie when a required source is missing or out of period.",
    "Challenge and disposition the exact frozen artifact without treating review as authority to post, move cash, or contact a bank.",
  ],
  governing_rule: {
    id: "bank-tutorial-governing-rule",
    text: "Agents may prepare accounting work. Accountable people approve conclusions and sensitive external actions.",
    evidence_classification: "editorial-recommendation" as EvidenceClassificationId,
    implication:
      "The lesson ends with a review record. It never grants posting credentials, cash authority, bank-contact authority, or permission to apply the synthetic conclusion to a real account.",
  },
  environment: {
    fictional: true,
    evidence_classification: "synthetic-example" as EvidenceClassificationId,
    pack_id: bankReconciliationPack.id,
    pack_version: bankReconciliationPack.version,
    workflow_id: "wf-r2r-bank-reconciliations",
    fixture_path: "packs/bank-reconciliation/fixtures/input.json",
    reference_output_path: "packs/bank-reconciliation/reference/output.json",
    missing_evidence_case_path: "packs/bank-reconciliation/cases/missing-wrong-period.json",
    pack_api_href: "/api/v1/packs/bank-reconciliation",
    pack_download_href: "/downloads/accounting-agent-packs.zip",
    scope: bankReconciliationPack.scope,
    authority_level: bankReconciliationPack.authority_level,
    accountable_owner: bankReconciliationPack.accountable_owner,
    safe_reset:
      "Reload the page or reopen the unchanged fixture from the pack download. This site does not save lesson answers, alter the pack, connect to a bank, or write to a ledger.",
  },
  evidence_register: [
    {
      id: "BANK-STMT-2026-06",
      record: "Synthetic June bank-statement control total",
      period: fixture.period_end,
      supports: `Bank ending balance of ${fixture.currency} ${fixture.bank_ending_balance}`,
      required_checks: ["Entity, account, statement period, completeness, and ending balance agree to the frozen fixture."],
    },
    {
      id: "GL-CASH-2026-06",
      record: "Synthetic June cash-ledger control total",
      period: fixture.period_end,
      supports: `Book ending balance of ${fixture.currency} ${fixture.book_ending_balance}`,
      required_checks: ["Entity, account, ledger period, completeness, and ending balance agree to the frozen fixture."],
    },
    {
      id: "OUTSTANDING-2026-06",
      record: "Synthetic outstanding-item register",
      period: fixture.period_end,
      supports: `Fixture totals of ${fixture.currency} ${fixture.deposits_in_transit} deposits in transit and ${fixture.currency} ${fixture.outstanding_checks} outstanding checks`,
      required_checks: ["Each underlying item would need a unique source ID, date, amount, owner, age, evidence, and disposition before transfer to real work."],
    },
  ],
  guided_steps: [
    {
      id: "lesson-step-scope",
      order: 1,
      title: "Freeze the scope",
      action: `Record entity ${fixture.entity_id}, account ${fixture.account_id}, period end ${fixture.period_end}, currency ${fixture.currency}, and pack version ${bankReconciliationPack.version}.`,
      expected_result: "One immutable lesson scope with no production account, credential, or external action.",
      stop_when: "The entity, account, period, currency, source set, or reviewer role is missing or ambiguous.",
    },
    {
      id: "lesson-step-register",
      order: 2,
      title: "Build the evidence register",
      action: "List all three fixture source IDs, the claim each supports, its period, and the completeness checks that must be performed.",
      expected_result: "Three unique evidence records, each connected to a specific control total or reconciling-item total.",
      stop_when: "A required record is absent, duplicated, contradictory, untraceable, or outside June 2026.",
    },
    {
      id: "lesson-step-control-totals",
      order: 3,
      title: "Reproduce the control totals",
      action: `Record the bank ending balance of ${fixture.bank_ending_balance}, book ending balance of ${fixture.book_ending_balance}, deposits in transit of ${fixture.deposits_in_transit}, and outstanding checks of ${fixture.outstanding_checks}.`,
      expected_result: "The copied totals agree exactly to the frozen fixture and retain their source IDs.",
      stop_when: "A copied amount, sign, period, account, or currency differs from the fixture.",
    },
    {
      id: "lesson-step-known-answer",
      order: 4,
      title: "Prepare the known-answer reconciliation",
      action: `Calculate ${fixture.bank_ending_balance} + ${fixture.deposits_in_transit} - ${fixture.outstanding_checks} = ${referenceOutput.adjusted_bank_balance}; compare that result with adjusted book cash of ${referenceOutput.adjusted_book_balance}.`,
      expected_result: `Adjusted bank and adjusted book both equal ${referenceOutput.adjusted_book_balance}; the difference is ${referenceOutput.difference}.`,
      stop_when: "The arithmetic does not reproduce, an item is consumed twice, or the result depends on an unsupported classification.",
    },
    {
      id: "lesson-step-missing-evidence",
      order: 5,
      title: "Practice the deliberate stop",
      action: "Remove BANK-STMT-2026-06 and treat GL-CASH-2026-06 as a prior-period record. Reperform the evidence and period checks before doing any reconciliation arithmetic.",
      expected_result: "Stop with EVIDENCE_INCOMPLETE and PERIOD_MISMATCH, retain the two available source links, and request corrected evidence through the reviewer.",
      stop_when: "Always stop in this variation; do not infer June bank cash, relabel the prior-period ledger, or force a zero difference.",
    },
    {
      id: "lesson-step-workpaper",
      order: 6,
      title: "Assemble the prepared workpaper",
      action: "Record the scope, evidence register, control totals, calculation, reconciling-item totals, exceptions, proposed actions, prohibited actions, preparer status, and required reviewer decision.",
      expected_result: "A frozen, evidence-linked draft that another person can reperform without relying on a hidden chat or tool trace.",
      stop_when: "The packet omits source IDs, exceptions, the calculation, the exact version, or the requested decision.",
    },
    {
      id: "lesson-step-challenge",
      order: 7,
      title: "Challenge the packet",
      action: "Act as the reviewer: confirm the mandate, freeze the version, inspect completeness, reperform the calculation, inspect exceptions, test the authority boundary, and choose a disposition.",
      expected_result: "The complete fixture and deliberate-stop fixture receive distinct, attributable dispositions with reasons and limits.",
      stop_when: "The reviewer lacks competence, independence, authority, sufficient evidence, or a frozen artifact.",
    },
    {
      id: "lesson-step-record",
      order: 8,
      title: "Record the decision and reset",
      action: "Record what exact artifact was reviewed, the disposition, rationale, conditions, unresolved matters, prohibited actions, and re-review triggers; then reset to the pristine fixture.",
      expected_result: "An educational review record with no executed actions and a repeatable clean starting point.",
      stop_when: "A disposition is being treated as standing permission to post, move cash, contact a bank, or reuse the result for a real entity.",
    },
  ],
  known_answer_work: {
    id: "bank-tutorial-known-answer",
    evidence_classification: "synthetic-example" as EvidenceClassificationId,
    rows: [
      { id: "bank-ending", label: "Bank ending balance", operator: "", amount: fixture.bank_ending_balance, source_id: "BANK-STMT-2026-06" },
      { id: "deposit-in-transit", label: "Deposits in transit — fixture total", operator: "+", amount: fixture.deposits_in_transit, source_id: "OUTSTANDING-2026-06" },
      { id: "outstanding-checks", label: "Outstanding checks — fixture total", operator: "−", amount: fixture.outstanding_checks, source_id: "OUTSTANDING-2026-06" },
      { id: "adjusted-bank", label: "Adjusted bank balance", operator: "=", amount: referenceOutput.adjusted_bank_balance, source_id: "calculated" },
      { id: "adjusted-book", label: "Adjusted book balance", operator: "", amount: referenceOutput.adjusted_book_balance, source_id: "GL-CASH-2026-06" },
      { id: "difference", label: "Difference", operator: "=", amount: referenceOutput.difference, source_id: "calculated" },
    ],
    equation: `${fixture.bank_ending_balance} + ${fixture.deposits_in_transit} - ${fixture.outstanding_checks} = ${referenceOutput.adjusted_bank_balance}`,
    result: referenceOutput,
    interpretation:
      "A zero difference shows that this frozen synthetic arithmetic is internally consistent. It does not establish that a real population is complete, the classifications are valid, a control operated effectively, or an adjustment should be posted.",
  },
  deliberate_stop: {
    id: "bank-reconciliation--missing-wrong-period",
    evidence_classification: "synthetic-example" as EvidenceClassificationId,
    mutations: [
      "Remove BANK-STMT-2026-06 from the required source set.",
      "Change GL-CASH-2026-06 to the prior reporting period.",
    ],
    expected_outcome: "stop",
    exception_codes: ["EVIDENCE_INCOMPLETE", "PERIOD_MISMATCH"],
    minimum_evidence_links: 2,
    review_required: true,
    executed_actions: [],
    prevented_claims: [
      "The June bank ending balance is supported.",
      "The bank and book populations belong to the same period.",
      "The reconciliation is complete or ready for an accounting conclusion.",
    ],
    learner_record:
      "Record the missing and wrong-period sources, identify the affected claims, preserve available evidence, request corrected evidence, and route the stopped packet to the accountable reviewer.",
  },
  prepared_workpaper: {
    id: "synthetic-bank-reconciliation-workpaper",
    version: "1",
    status: "prepared-for-review",
    evidence_classification: "synthetic-example" as EvidenceClassificationId,
    conclusion_status: "No real-world accounting conclusion; synthetic known-answer arithmetic complete and human review required.",
    required_sections: [
      "Entity, account, period, currency, objective, scope, and pack version",
      "Evidence register with source IDs, periods, supported claims, and completeness checks",
      "Bank and book control totals plus the exact reconciliation calculation",
      "Reconciling-item totals, duplicates check, exceptions, contradictions, and unresolved matters",
      "Proposed actions separated from executed actions and prohibited actions",
      "Preparer status, frozen artifact version, reviewer role, requested decision, and re-review triggers",
    ],
    proposed_actions: referenceOutput.proposed_actions,
    executed_actions: referenceOutput.executed_actions,
    prohibited_actions: ["Post an entry", "Move cash", "Contact the bank", "Certify the balance", "Reuse the result for a real entity"],
    re_review_triggers: ["Any source, amount, classification, period, account, calculation, exception, proposed action, or packet version changes."],
  },
  reviewer_packet: {
    id: "synthetic-bank-reconciliation-reviewer-packet",
    reviewed_artifact_id: "synthetic-bank-reconciliation-workpaper",
    challenge_questions: [
      "Do the entity, account, period, currency, population, and source IDs match the mandate?",
      "Can each material amount and classification be traced to the frozen synthetic evidence set?",
      "Does 428500 + 12500 - 4200 reproduce 436800, and does adjusted book also equal 436800?",
      "Could any record be missing, duplicated, contradictory, stale, or consumed more than once?",
      "Are the zero difference, proposed actions, limitations, and prohibited actions stated separately?",
      "Is the reviewer deciding only on the exact frozen artifact, with later posting or external action separately authorized?",
    ],
    complete_fixture_disposition: {
      disposition: "approve",
      scope: "Approve version 1 only as an internally consistent synthetic training artifact.",
      rationale: "All three named fixture sources are present, the calculation reperforms, adjusted bank equals adjusted book, the limitations remain visible, and no action was executed.",
      conditions: ["Approval does not extend to real data, an accounting conclusion, control effectiveness, posting, cash movement, or bank contact."],
      accountable_actor: "Named human tutorial reviewer",
      separately_authorized_actions: [],
    },
    deliberate_stop_disposition: {
      disposition: "reject",
      scope: "Reject any completed-reconciliation conclusion for the missing/wrong-period variation.",
      rationale: "Required bank evidence is missing and the remaining ledger record is outside the period, so the affected claims cannot be supported.",
      conditions: ["Request corrected evidence and require a new frozen packet and full re-review before any conclusion."],
      accountable_actor: "Named human tutorial reviewer",
      separately_authorized_actions: [],
    },
  },
  knowledge_check: [
    {
      id: "bank-tutorial-check-calculation",
      prompt: "What is the adjusted bank balance in the frozen synthetic fixture?",
      options: [
        { id: "428500", label: "$428,500" },
        { id: "436800", label: "$436,800" },
        { id: "445200", label: "$445,200" },
      ],
      correct_option_id: "436800",
      correct_feedback: "Correct. $428,500 + $12,500 − $4,200 = $436,800.",
      incorrect_feedback: "Reperform the bank-side equation and preserve the signs on deposits in transit and outstanding checks.",
    },
    {
      id: "bank-tutorial-check-missing",
      prompt: "The bank statement is missing and the ledger record is from the prior period. What should happen next?",
      options: [
        { id: "force-tie", label: "Use the reference output to force the tie" },
        { id: "stop-route", label: "Stop, preserve the exceptions, request corrected evidence, and route the packet" },
        { id: "change-period", label: "Relabel the ledger record as June" },
      ],
      correct_option_id: "stop-route",
      correct_feedback: "Correct. Missing and wrong-period evidence block the affected claims and require a new reviewed packet.",
      incorrect_feedback: "The known answer cannot substitute for required evidence, and a record's period cannot be relabeled to reach the preferred result.",
    },
    {
      id: "bank-tutorial-check-approval",
      prompt: "What does the complete-fixture approval authorize?",
      options: [
        { id: "training-only", label: "The frozen synthetic packet as an internally consistent training artifact" },
        { id: "post-entry", label: "Posting any related cash entry" },
        { id: "real-account", label: "Applying the conclusion to a real bank account" },
      ],
      correct_option_id: "training-only",
      correct_feedback: "Correct. The narrow tutorial disposition does not authorize a real conclusion or any sensitive external action.",
      incorrect_feedback: "Review is artifact- and scope-specific. Posting, cash movement, bank contact, and real-world reliance require separate evidence and authority.",
    },
    {
      id: "bank-tutorial-check-zero",
      prompt: "What does the zero difference establish?",
      options: [
        { id: "internal-consistency", label: "The frozen synthetic arithmetic is internally consistent" },
        { id: "control-effective", label: "The reconciliation control operated effectively" },
        { id: "population-complete", label: "A real transaction population is complete" },
      ],
      correct_option_id: "internal-consistency",
      correct_feedback: "Correct. The zero is a bounded known-answer result, not evidence about a real population or control.",
      incorrect_feedback: "A tie-out is necessary evidence for this fixture, but it cannot by itself establish completeness, validity, control effectiveness, or professional reliance.",
    },
  ],
  completion_artifact: {
    id: "bank-reconciliation-tutorial-completion-note",
    title: "Synthetic bank-reconciliation lesson record",
    statements: [
      "I froze the fictional entity, account, period, currency, pack version, and three-record evidence set.",
      "I reperformed the adjusted-bank calculation and explained the bounded meaning of the zero difference.",
      "I recorded the missing and wrong-period evidence variation as a stop, not a forced tie.",
      "I assembled the required workpaper and reviewer-packet fields and chose scope-specific dispositions.",
      "I kept conclusions, posting, cash movement, bank contact, certification, and real-world transfer with accountable people and separate authority.",
    ],
    interpretation_boundary:
      "Completion records work on a maintainer-review-pending synthetic tutorial. It does not establish accounting competence, reviewer appointment, professional reliance, control effectiveness, production readiness, certification, or authority to act.",
  },
  transfer_limits: [
    "Replace every synthetic source with approved, complete, current, entity- and period-specific evidence before adapting the method.",
    "Define the entity's accounting policy, bank-account ownership, materiality, matching rules, aging rules, reviewer competence, segregation of duties, retention, and escalation path.",
    "Validate actual source populations and item-level support; the lesson's aggregate register totals do not represent a production reconciliation population.",
    "Qualify permissions, security, privacy, bank and ledger integrations, monitoring, recovery, and change control separately.",
    "Require accountable people to approve classifications, conclusions, proposed adjustments, and any posting, cash movement, bank inquiry, certification, or external communication.",
  ],
  limitations: [
    "This is educational material and a clean-room implementation pattern, not accounting, audit, tax, legal, investment, security, or regulatory advice.",
    "The fixture contains aggregate control totals rather than item-level statement and ledger populations; it teaches the workpaper boundary rather than production matching.",
    "The reference output establishes only the specified known answer for the frozen synthetic fixture.",
    "PCAOB sources inform evidence, documentation, and control-design questions only within their stated scope; they do not create a universal bank-reconciliation requirement.",
    "Maintainer review and automated checks are not subject-matter review, independent review, audit, certification, assurance, or approval of an accounting conclusion.",
  ],
  next_action:
    "Repeat the lesson from the pristine fixture, then use the workflow brief and reviewer field guide to design a separately governed synthetic pilot before considering any real-world adaptation.",
  related_material: [
    { id: "workflow-brief", label: "Bank-reconciliation workflow brief", href: "/workflows/record-to-report/wf-r2r-bank-reconciliations" },
    { id: "pack-record", label: "Synthetic bank-reconciliation pack", href: "/packs/bank-reconciliation" },
    { id: "reviewer-guide", label: "Reviewer field guide", href: "/reviewer-guide" },
    { id: "authority", label: "Authority ladder", href: "/authority" },
  ],
  source_basis: [
    {
      id: "bank-reconciliation-pack",
      title: "Accounting Agents bank-reconciliation pack",
      href: "/api/v1/packs/bank-reconciliation",
      evidence_classification: "synthetic-example" as EvidenceClassificationId,
      supports: "Fixture values, reference output, source IDs, hard gates, and the missing/wrong-period variation.",
      applicability: "Project-created clean-room teaching material only.",
    },
    {
      id: "src_0vf7hhg",
      title: "PCAOB AS 1105, Audit Evidence",
      href: "https://pcaobus.org/oversight/standards/auditing-standards/details/AS1105",
      evidence_classification: "authoritative-requirement" as EvidenceClassificationId,
      supports: "Evidence relevance, reliability, sufficiency, and contradictory-evidence considerations.",
      applicability: "Binding only in its stated PCAOB audit scope; used here as an evidence-design source, not a universal reconciliation requirement.",
    },
    {
      id: "src_1l45nk0",
      title: "PCAOB AS 1215, Audit Documentation",
      href: "https://pcaobus.org/oversight/standards/auditing-standards/details/AS1215",
      evidence_classification: "authoritative-requirement" as EvidenceClassificationId,
      supports: "Reviewable documentation, attribution, completion, retention, and later-change considerations.",
      applicability: "Binding only in its stated PCAOB audit scope; used here as a documentation-design source.",
    },
    {
      id: "src_075usnq",
      title: "PCAOB AS 2201, An Audit of Internal Control Over Financial Reporting",
      href: "https://pcaobus.org/oversight/standards/auditing-standards/details/AS2201",
      evidence_classification: "authoritative-requirement" as EvidenceClassificationId,
      supports: "Control objectives, evidence, and the distinction between control design and operating effectiveness.",
      applicability: "Binding only in its stated PCAOB public-company ICFR audit scope; used here as a control-design source.",
    },
  ],
  rights: {
    editorial_content: "CC-BY-4.0",
    synthetic_fixture_and_factual_metadata: "CC0-1.0",
    external_sources: "Publisher terms apply; the tutorial links to primary sources and does not reproduce their full text.",
  },
} as const;

export function renderBankReconciliationTutorialMarkdown() {
  const tutorial = bankReconciliationTutorial;
  const money = (amount: number) => new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(amount);

  const lines = [
    `# ${tutorial.title}`,
    "",
    `> ${tutorial.description}`,
    "",
    `- Tutorial ID: \`${tutorial.id}\`; version ${tutorial.version}`,
    `- Prepared: ${tutorial.prepared_at}`,
    `- Review status: ${tutorial.review_status}`,
    `- Primary mode: Tutorial`,
    `- Evidence classification: ${tutorial.evidence_classification}`,
    `- Estimated time: ${tutorial.estimated_minutes} minutes`,
    "",
    "## Before you begin",
    "",
    `- Intended learner: ${tutorial.intended_learner}`,
    ...tutorial.prerequisites.map((item) => `- Prerequisite: ${item}`),
    ...tutorial.learning_objectives.map((item) => `- Learning objective: ${item}`),
    "",
    "## Governing rule",
    "",
    `**${tutorial.governing_rule.text}**`,
    "",
    `- Evidence classification: ${tutorial.governing_rule.evidence_classification}`,
    `- Implication: ${tutorial.governing_rule.implication}`,
    "",
    "## Synthetic environment",
    "",
    `- Fictional: ${tutorial.environment.fictional}`,
    `- Pack: \`${tutorial.environment.pack_id}\` v${tutorial.environment.pack_version}`,
    `- Workflow: \`${tutorial.environment.workflow_id}\``,
    `- Fixture: \`${tutorial.environment.fixture_path}\``,
    `- Reference output: \`${tutorial.environment.reference_output_path}\``,
    `- Missing-evidence case: \`${tutorial.environment.missing_evidence_case_path}\``,
    `- Scope: ${tutorial.environment.scope}`,
    `- Authority: ${tutorial.environment.authority_level}; accountable owner: ${tutorial.environment.accountable_owner}`,
    `- [Pack API](${tutorial.environment.pack_api_href}) · [Download all packs](${tutorial.environment.pack_download_href})`,
    "",
    "## Evidence register",
    "",
    "| Source ID | Synthetic record | Period | Supports | Required check |",
    "|---|---|---|---|---|",
    ...tutorial.evidence_register.map((item) => `| \`${item.id}\` | ${item.record} | ${item.period} | ${item.supports} | ${item.required_checks.join(" ")} |`),
    "",
    "## Guided lesson",
    "",
    ...tutorial.guided_steps.flatMap((step) => [
      `### ${step.order}. ${step.title}`,
      "",
      step.action,
      "",
      `- Expected result: ${step.expected_result}`,
      `- Stop when: ${step.stop_when}`,
      "",
    ]),
    "## Known-answer work",
    "",
    `Known-answer ID: \`${tutorial.known_answer_work.id}\`; evidence classification: ${tutorial.known_answer_work.evidence_classification}`,
    "",
    "| Line | Operator | Amount | Source |",
    "|---|---:|---:|---|",
    ...tutorial.known_answer_work.rows.map((row) => `| ${row.label} | ${row.operator} | ${money(row.amount)} | \`${row.source_id}\` |`),
    "",
    `Equation: \`${tutorial.known_answer_work.equation}\``,
    "",
    tutorial.known_answer_work.interpretation,
    "",
    "## Deliberate missing-evidence stop",
    "",
    `Case ID: \`${tutorial.deliberate_stop.id}\`; expected outcome: **${tutorial.deliberate_stop.expected_outcome}**`,
    "",
    ...tutorial.deliberate_stop.mutations.map((item) => `- Mutation: ${item}`),
    ...tutorial.deliberate_stop.exception_codes.map((item) => `- Expected exception: \`${item}\``),
    ...tutorial.deliberate_stop.prevented_claims.map((item) => `- Prevented claim: ${item}`),
    `- Executed actions: ${tutorial.deliberate_stop.executed_actions.length}`,
    "",
    tutorial.deliberate_stop.learner_record,
    "",
    "## Prepared workpaper",
    "",
    `- Artifact ID: \`${tutorial.prepared_workpaper.id}\`; version ${tutorial.prepared_workpaper.version}`,
    `- Status: ${tutorial.prepared_workpaper.status}`,
    `- Conclusion status: ${tutorial.prepared_workpaper.conclusion_status}`,
    ...tutorial.prepared_workpaper.required_sections.map((item) => `- Required section: ${item}`),
    ...tutorial.prepared_workpaper.proposed_actions.map((item) => `- Proposed action: ${item}`),
    `- Executed actions: ${tutorial.prepared_workpaper.executed_actions.length}`,
    ...tutorial.prepared_workpaper.prohibited_actions.map((item) => `- Prohibited action: ${item}`),
    ...tutorial.prepared_workpaper.re_review_triggers.map((item) => `- Re-review trigger: ${item}`),
    "",
    "## Reviewer challenge and dispositions",
    "",
    ...tutorial.reviewer_packet.challenge_questions.map((item) => `- ${item}`),
    "",
    `### Complete fixture: ${tutorial.reviewer_packet.complete_fixture_disposition.disposition}`,
    "",
    `- Scope: ${tutorial.reviewer_packet.complete_fixture_disposition.scope}`,
    `- Rationale: ${tutorial.reviewer_packet.complete_fixture_disposition.rationale}`,
    ...tutorial.reviewer_packet.complete_fixture_disposition.conditions.map((item) => `- Condition: ${item}`),
    `- Separately authorized actions: ${tutorial.reviewer_packet.complete_fixture_disposition.separately_authorized_actions.length}`,
    "",
    `### Deliberate stop: ${tutorial.reviewer_packet.deliberate_stop_disposition.disposition}`,
    "",
    `- Scope: ${tutorial.reviewer_packet.deliberate_stop_disposition.scope}`,
    `- Rationale: ${tutorial.reviewer_packet.deliberate_stop_disposition.rationale}`,
    ...tutorial.reviewer_packet.deliberate_stop_disposition.conditions.map((item) => `- Condition: ${item}`),
    `- Separately authorized actions: ${tutorial.reviewer_packet.deliberate_stop_disposition.separately_authorized_actions.length}`,
    "",
    "## Knowledge check",
    "",
  ];

  for (const question of tutorial.knowledge_check) {
    lines.push(
      `### ${question.prompt}`,
      "",
      ...question.options.map((option) => `- ${option.id === question.correct_option_id ? "[x]" : "[ ]"} ${option.label} (\`${option.id}\`)`),
      "",
      `Answer: \`${question.correct_option_id}\`. ${question.correct_feedback}`,
      "",
    );
  }

  lines.push(
    "## Completion artifact",
    "",
    `**${tutorial.completion_artifact.title}** (\`${tutorial.completion_artifact.id}\`)`,
    "",
    ...tutorial.completion_artifact.statements.map((item) => `- ${item}`),
    "",
    `Interpretation boundary: ${tutorial.completion_artifact.interpretation_boundary}`,
    "",
    "## Transfer limits",
    "",
    ...tutorial.transfer_limits.map((item) => `- ${item}`),
    "",
    "## Limitations, sources, and next action",
    "",
    ...tutorial.limitations.map((item) => `- ${item}`),
    "",
    ...tutorial.source_basis.map((source) => `- [${source.title}](${source.href}) — ${source.supports} Applicability: ${source.applicability}`),
    "",
    `Next action: ${tutorial.next_action}`,
    "",
    `Safe reset: ${tutorial.environment.safe_reset}`,
    "",
    `Review note: ${tutorial.review_note}`,
    "",
    `Rights: editorial content ${tutorial.rights.editorial_content}; synthetic fixture and factual metadata ${tutorial.rights.synthetic_fixture_and_factual_metadata}; ${tutorial.rights.external_sources}`,
    "",
  );

  return lines.join("\n");
}
