import {
  corpusReviewedAt,
  type ControlPattern,
  type SensitiveActionRecord,
} from "./domain-model";

const commonApprovalEvidence = [
  "Named approver identity, role, and authority",
  "Immutable action payload or decision package",
  "Approval time, scope, conditions, and expiration",
];

const commonLogging = [
  "Record request, evidence, configuration, decision, tool call, result, actor, and timestamp",
  "Reconcile the completed action to the approved payload and authoritative system",
  "Route failures, overrides, and post-action differences to an accountable reviewer",
];

export const sensitiveActions: SensitiveActionRecord[] = [
  {
    id: "sa-journal-posting",
    version: "1",
    name: "Journal posting",
    summary: "A ledger write changes the entity's books and may affect close, reporting, controls, and external statements.",
    default_authority: "A3",
    agent_may_prepare: ["Balanced entry lines", "Support and calculation", "Description, dimensions, and reversal", "Immutable approval payload"],
    agent_may_execute: ["Submit the exact approved payload through a constrained posting or staging interface"],
    human_only_conditions: ["Approval of the accounting conclusion", "Manual top-side, unusual, material, executive, or closed-period entry", "Final approval or self-approval"],
    identity_and_sod: ["Preparer cannot approve their own entry", "Posting credential is separate from the model", "Approver has entity and amount authority"],
    limits: ["Approved entities, periods, accounts, dimensions, amount, and entry type", "No closed-period or prohibited-account posting"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Debits equal credits", "Payload hash matches approval", "Period and accounts remain open and valid", "Duplicate-entry key is unused"],
    rollback_or_compensation: ["Do not delete a posted entry", "Prepare an attributable reversal or correcting entry under the same approval controls"],
    logging_and_review: commonLogging,
    source_ids: ["src_1v1zwt5", "src_gaogb25", "src_066cphd", "src_0pywo86"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-cash-movement",
    version: "1",
    name: "Cash movement and payment release",
    summary: "A payment or transfer creates an immediate fiduciary and fraud exposure and may be difficult to reverse.",
    default_authority: "A3",
    agent_may_prepare: ["Payment proposal", "Verified beneficiary record", "Cash and fraud checks", "Immutable bank payload"],
    agent_may_execute: ["Submit the exact approved payment once through a least-privilege interface when the bank and policy engine independently enforce authorization"],
    human_only_conditions: ["Fiduciary approval or signer attestation", "New or changed beneficiary not independently verified", "Material, unusual, urgent, related-party, or control-override payment"],
    identity_and_sod: ["Requester, vendor maintainer, preparer, and releaser are separated", "Dual approval applies where policy requires", "The agent never possesses a human signer's credential"],
    limits: ["Approved account, beneficiary, amount, currency, value date, purpose, and transaction type", "Bank, sanctions, fraud, and liquidity limits"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Beneficiary independently verified", "Payload hash and approval match", "Idempotency and duplicate tests pass", "Bank and fraud holds are clear"],
    rollback_or_compensation: ["Attempt recall only through authorized treasury procedures", "Escalate immediately and preserve bank acknowledgment and communication evidence"],
    logging_and_review: commonLogging,
    source_ids: ["src_1v1zwt5", "src_nachafm", "src_fincenbe", "src_fedocirc", "src_ofaccomp", "src_0zwe7na", "src_06fwpim", "src_1wj6irw"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-external-filings",
    version: "1",
    name: "External filings and submissions",
    summary: "A filing makes a representation to a regulator, tax authority, investor, or other external party.",
    default_authority: "A3",
    agent_may_prepare: ["Draft form and attachments", "Field-to-source map", "Validation results", "Immutable submission package"],
    agent_may_execute: ["Transmit the exact approved package through a constrained interface after the authorized signer completes any required attestation"],
    human_only_conditions: ["Signature, attestation, certification, or legal representation", "Material disclosure or tax-position judgment", "Amendment, waiver, or response to regulator inquiry"],
    identity_and_sod: ["Authorized preparer, reviewer, signer, and submitter are recorded", "Submission credential and signer identity remain outside the model"],
    limits: ["Approved entity, jurisdiction, form version, period, attachments, and deadline", "One idempotent submission unless an amendment is separately approved"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Package hash matches approval", "Form version and deadline are current", "All validation errors and open items are resolved", "Signer and submitter authority is current"],
    rollback_or_compensation: ["Preserve acknowledgment or rejection", "Use the authority's formal amendment, withdrawal, or correction process"],
    logging_and_review: commonLogging,
    source_ids: ["src_edgarfm", "src_sec8124", "src_irs8879c", "src_0yxfsz4", "src_1xqtx2m", "src_1v1zwt5"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-deletion",
    version: "1",
    name: "Deletion and destructive changes",
    summary: "Deletion may destroy accounting evidence, impair reproducibility, or violate retention and legal-hold requirements.",
    default_authority: "A3",
    agent_may_prepare: ["Exact object list", "Reason and authority", "Retention and legal-hold check", "Backup or archive confirmation"],
    agent_may_execute: ["Perform a narrowly approved, reversible soft-delete or archival action when policy explicitly allows it"],
    human_only_conditions: ["Permanent deletion", "Records subject to legal hold, audit, investigation, dispute, retention, or certification", "Bulk or cross-entity destructive action"],
    identity_and_sod: ["Record owner and legal or retention owner approve where applicable", "Requester cannot approve their own destructive action"],
    limits: ["Exact objects, system, entity, date range, retention class, and deletion method", "No wildcard, inferred, or model-expanded target"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Object list and count match approval", "Retention and legal-hold checks pass", "Recoverable archive or backup is verified", "Downstream references are identified"],
    rollback_or_compensation: ["Restore from verified archive when possible", "Preserve deletion manifest and escalate unrecoverable loss as an incident"],
    logging_and_review: commonLogging,
    source_ids: ["src_nist88r2", "src_gdpr2016", "src_secr206", "src_irsrecord", "src_0pywo86", "src_16b4w7b", "src_05o8995"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-master-data",
    version: "1",
    name: "Master-data changes",
    summary: "Vendor, customer, bank, account, entity, and other master changes can redirect transactions or corrupt accounting logic.",
    default_authority: "A3",
    agent_may_prepare: ["Validated current and proposed values", "Independent identity and bank verification", "Duplicate and conflict analysis", "Exact change payload"],
    agent_may_execute: ["Apply the exact approved fields through a constrained interface with field-level permission"],
    human_only_conditions: ["Relationship, legal-entity, bank, signer, chart-of-accounts, or policy decision", "Unverified or conflicting source evidence", "Emergency override"],
    identity_and_sod: ["Maintenance is separate from transaction and payment release", "Sensitive changes require independent verification and approval"],
    limits: ["Approved object, fields, values, effective date, and entity", "No creation or field expansion beyond the approval payload"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Current value has not changed since approval", "Proposed value matches verified evidence", "Duplicate and incompatible-role tests pass"],
    rollback_or_compensation: ["Restore prior version through an approved change", "Identify and review transactions processed under the incorrect master value"],
    logging_and_review: commonLogging,
    source_ids: ["src_1v1zwt5", "src_fincenbe", "src_irsw9tin", "src_irstinm", "src_0pywo86", "src_0zwe7na"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-credits-writeoffs",
    version: "1",
    name: "Write-offs, refunds, and credit decisions",
    summary: "These actions reduce assets or revenue, move cash, change customer rights, or create fraud and override risk.",
    default_authority: "A3",
    agent_may_prepare: ["Reason and evidence", "Remaining balance and calculation", "Prior concessions and anomaly analysis", "Exact action payload"],
    agent_may_execute: ["Apply a separately approved credit or write-off through a constrained interface", "Initiate an approved refund only through payment controls"],
    human_only_conditions: ["Commercial concession, collectability, legal dispute, or fraud judgment", "Beneficiary mismatch", "Material or unusual action"],
    identity_and_sod: ["Sales or collections request is separate from accounting approval", "Refund release is separate from customer and bank maintenance"],
    limits: ["Approved customer, source transaction, amount, reason, tax, beneficiary, and effective date"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Original transaction and remaining balance agree", "Duplicate action test passes", "Approver authority and beneficiary are verified"],
    rollback_or_compensation: ["Reverse through an approved correcting transaction", "Use authorized recall or recovery procedures for cash refunds"],
    logging_and_review: commonLogging,
    source_ids: ["src_ifrs09a", "src_1v1zwt5", "src_1wj6irw", "src_066cphd"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-final-approval",
    version: "1",
    name: "Final approval",
    summary: "Final approval assigns accountability for the conclusion, action, or reporting outcome.",
    default_authority: "human-only",
    agent_may_prepare: ["Reviewer packet", "Evidence and calculation index", "Exceptions and contradictory evidence", "Decision alternatives"],
    agent_may_execute: [],
    human_only_conditions: ["Always human-only when the approval carries accounting, legal, fiduciary, control, professional, or external accountability"],
    identity_and_sod: ["Approver is named, authorized, independent where required, and directly reviews the work", "The agent cannot approve its own output"],
    limits: ["Approval applies only to the stated entity, period, population, payload, and version"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["All required review criteria and open matters are visible", "The approval interface requires an attributable human action"],
    rollback_or_compensation: ["Supersede through a new attributable decision; never rewrite the prior approval record"],
    logging_and_review: commonLogging,
    source_ids: ["src_1v1zwt5", "src_gaogb25", "src_075usnq", "src_10b9y2x"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-certification",
    version: "1",
    name: "ICFR and other legal certification",
    summary: "Certification is a personal or organizational attestation with legal, governance, and professional consequences.",
    default_authority: "human-only",
    agent_may_prepare: ["Certification support package", "Subcertification completeness check", "Deficiency and change summary", "Evidence index"],
    agent_may_execute: [],
    human_only_conditions: ["Signature, attestation, certification, or acceptance of legal or professional responsibility is always human-owned"],
    identity_and_sod: ["Only the legally or organizationally authorized certifier acts", "No credential delegation, impersonation, or inferred approval"],
    limits: ["The agent may not sign, click, attest, or submit as the certifier"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Required subcertifications, changes, and deficiencies are complete and prominent", "The certifier directly reviews the current package"],
    rollback_or_compensation: ["Use formal correction, amendment, disclosure, and governance procedures if a certification is later found incorrect"],
    logging_and_review: commonLogging,
    source_ids: ["src_sec13a15", "src_sec8238", "src_sec8124", "src_0yxfsz4", "src_075usnq", "src_1v1zwt5"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-unsupervised-close",
    version: "1",
    name: "Unsupervised close activity",
    summary: "Close activity combines many dependent accounting decisions; hidden failures can propagate into reporting.",
    default_authority: "human-only",
    agent_may_prepare: ["Task status and dependency checks", "Tie-outs and exception queues", "Draft workpapers and entries", "Close-readiness summary"],
    agent_may_execute: ["Update reversible, non-accounting task status under A4 policy when evidence criteria are deterministic"],
    human_only_conditions: ["Final close, period lock, material override, conclusion approval, certification, or release of financial results"],
    identity_and_sod: ["Task ownership, accounting approval, posting, and final close roles remain separated", "Override authority belongs to named people"],
    limits: ["No unapproved posting, deletion, period lock, report release, or suppression of open exceptions"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Dependencies and required evidence are complete", "All material exceptions and overrides remain open and visible"],
    rollback_or_compensation: ["Reopen affected tasks or period through authorized procedures", "Trace and correct every downstream output affected by an error"],
    logging_and_review: commonLogging,
    source_ids: ["src_1v1zwt5", "src_gaogb25", "src_066cphd", "src_16b4w7b"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "sa-company-communications",
    version: "1",
    name: "Communications in the company's name",
    summary: "External messages may create representations, commitments, disclosure, privacy, legal, or reputational effects.",
    default_authority: "A3",
    agent_may_prepare: ["Draft message", "Factual source map", "Audience and confidentiality check", "Approved template payload"],
    agent_may_execute: ["Send a pre-approved, low-risk, template-bound message to an approved recipient when policy allows"],
    human_only_conditions: ["Legal, investor, regulator, customer-dispute, employment, certification, or material financial communication", "Commitment, admission, waiver, or nonpublic information"],
    identity_and_sod: ["Sender identity, audience, channel, and approver are explicit", "The agent does not impersonate an employee or conceal automation"],
    limits: ["Approved recipient, template, facts, attachments, channel, and expiration", "No recipient expansion or free-form material statement"],
    approval_evidence: commonApprovalEvidence,
    pre_execution_checks: ["Facts and attachments match approved sources", "Recipient and data classification are authorized", "Template has not expired"],
    rollback_or_compensation: ["Preserve the sent message", "Use an approved correction or disclosure process; do not silently delete the record"],
    logging_and_review: commonLogging,
    source_ids: ["src_06qnpc3", "src_1xqtx2m", "src_05o8995"],
    reviewed_at: corpusReviewedAt,
  },
];

export const controlPatterns: ControlPattern[] = [
  {
    id: "ctrl-input-completeness",
    version: "1",
    name: "Input completeness and control totals",
    risk: "The agent works from a partial, duplicated, stale, or wrong-scope population.",
    objective: "Establish the authoritative source, extraction parameters, and independent population totals before work begins.",
    procedure: ["Record source system, entity, period, query, and timestamp", "Reproduce counts and amounts", "Reconcile transformations and exclusions", "Stop on unexplained difference"],
    evidence: ["Source register", "Raw and transformed control totals", "Exclusion and transformation log"],
    exceptions: ["Untied total", "Unknown extraction logic", "Missing or duplicate records"],
    owner: "Workflow owner",
    frequency: "Every run",
    source_ids: ["src_1v1zwt5", "src_0vf7hhg", "src_08a3eqe"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-source-authenticity",
    version: "1",
    name: "Source authenticity and applicability",
    risk: "Evidence is altered, unauthoritative, inapplicable, or from the wrong entity, period, or jurisdiction.",
    objective: "Use identifiable, current, applicable evidence and preserve its provenance.",
    procedure: ["Identify source owner and custody", "Verify version and effective date", "Confirm entity, period, jurisdiction, and claim linkage", "Retain contradictory evidence"],
    evidence: ["Source URL or system identifier", "Version and retrieval date", "Applicability rationale"],
    exceptions: ["Unknown provenance", "Superseded source", "Scope or jurisdiction mismatch"],
    owner: "Preparer and reviewer",
    frequency: "Every source and run",
    source_ids: ["src_0vf7hhg", "src_08a3eqe", "src_09rekxe"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-change-management",
    version: "1",
    name: "Model, prompt, policy, and configuration change",
    risk: "A change alters behavior without evaluation, approval, or reproducibility.",
    objective: "Release only identified, tested, approved versions with a rollback path.",
    procedure: ["Record changed artifact and reason", "Run regression and workflow evaluations", "Approve release against risk criteria", "Monitor and retain prior version"],
    evidence: ["Versioned change record", "Evaluation results", "Approval and deployment record"],
    exceptions: ["Unversioned prompt or policy", "Failed regression", "Missing rollback or owner"],
    owner: "System owner and accounting process owner",
    frequency: "Every change",
    source_ids: ["src_0nrsy1i", "src_0ao5x0t", "src_00l4vrq"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-tool-authorization",
    version: "1",
    name: "Tool authorization and least privilege",
    risk: "The agent reads or changes data outside its approved objective or authority.",
    objective: "Expose only the minimum task-specific tools, data, fields, actions, and duration.",
    procedure: ["Separate read and write tools", "Enforce identity, scope, field, amount, and time limits outside the model", "Deny by default", "Review denials and entitlements"],
    evidence: ["Tool inventory and permissions", "Authorization decision log", "Periodic access review"],
    exceptions: ["Shared or human credential", "Wildcard permission", "Write access without approval enforcement"],
    owner: "System and security owner",
    frequency: "Before release and periodically",
    source_ids: ["src_0zwe7na", "src_0pywo86", "src_06fwpim", "src_1efrues"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-human-approval",
    version: "1",
    name: "Attributable human approval",
    risk: "The agent infers, fabricates, reuses, or expands approval.",
    objective: "Require a named authorized person to approve the exact decision or payload before sensitive action.",
    procedure: ["Present evidence, exceptions, and exact payload", "Authenticate approver and authority", "Record approval conditions and expiration", "Reject payload drift"],
    evidence: ["Reviewer packet", "Approval event", "Immutable payload identifier"],
    exceptions: ["Approval inferred from chat", "Approver lacks authority", "Payload changed after approval"],
    owner: "Accountable process owner",
    frequency: "Every required approval",
    source_ids: ["src_1v1zwt5", "src_1i38fu6", "src_1jqxy83"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-segregation-duties",
    version: "1",
    name: "Segregation of duties",
    risk: "One person or agent can initiate, alter master data, approve, execute, and conceal a transaction.",
    objective: "Separate incompatible responsibilities and prevent the agent from collapsing them through shared credentials or tools.",
    procedure: ["Map request, maintenance, preparation, approval, execution, custody, and reconciliation roles", "Block incompatible combinations", "Review emergency access and overrides"],
    evidence: ["Role matrix", "Authorization policy", "Conflict and override report"],
    exceptions: ["Self-approval", "Vendor maintainer can release payment", "Agent can both execute and suppress evidence"],
    owner: "Process and security owners",
    frequency: "At design, access change, and periodic review",
    source_ids: ["src_1v1zwt5", "src_0pywo86", "src_122i1et"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-deterministic-validation",
    version: "1",
    name: "Deterministic recalculation and tie-outs",
    risk: "A plausible narrative hides a calculation, schema, completeness, or balancing error.",
    objective: "Use deterministic code and source totals for arithmetic, validation, permissions, and completion criteria.",
    procedure: ["Recalculate independently", "Validate schemas and allowed values", "Tie inputs, outputs, and proposed effects", "Block action when a hard check fails"],
    evidence: ["Validation result", "Independent calculation", "Tie-out and error log"],
    exceptions: ["Untied balance", "Invalid schema", "Calculation performed only in model text"],
    owner: "Workflow owner",
    frequency: "Every run and before action",
    source_ids: ["src_066cphd", "src_04tonzv", "src_00l4vrq"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-exception-routing",
    version: "1",
    name: "Exception routing and stop conditions",
    risk: "The agent guesses through uncertainty, hides exceptions, or completes work outside policy.",
    objective: "Stop and route defined missing, contradictory, material, unauthorized, or high-risk conditions.",
    procedure: ["Define stop conditions before run", "Preserve the failed state and evidence", "Assign owner and due date", "Resume only after explicit resolution"],
    evidence: ["Stop event", "Exception record", "Resolution and rerun approval"],
    exceptions: ["Silent fallback", "Auto-cleared material item", "Retry without changed facts or approval"],
    owner: "Workflow owner and reviewer",
    frequency: "Continuous",
    source_ids: ["src_0nrsy1i", "src_1i38fu6", "src_0d24qh0"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-override-monitoring",
    version: "1",
    name: "Override and reviewer-disagreement monitoring",
    risk: "Recurring model errors or control bypasses are normalized instead of corrected.",
    objective: "Measure overrides, disagreements, exceptions, and downstream corrections by version and workflow.",
    procedure: ["Record human disposition and reason", "Trend by model, prompt, tool, source, and workflow", "Set escalation thresholds", "Feed resolved cases into evaluation"],
    evidence: ["Override log", "Trend report", "Remediation and evaluation result"],
    exceptions: ["Unrecorded reviewer change", "Rising override rate", "Repeated policy exception"],
    owner: "Product, accounting, and control owners",
    frequency: "Every run with periodic trend review",
    source_ids: ["src_038j28b", "src_00l4vrq", "src_0k6ht8q"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-version-evidence",
    version: "1",
    name: "Configuration, version, and run evidence",
    risk: "The work cannot be reproduced or attributed after a model, source, tool, or policy changes.",
    objective: "Preserve the exact configuration, sources, actions, results, and actors for each run.",
    procedure: ["Record model, prompt, policy, tool, template, evaluator, and source versions", "Capture tool calls and results", "Link approvals and final disposition"],
    evidence: ["Technical trace", "Accounting run record", "Workpaper and approval history"],
    exceptions: ["Unknown version", "Mutable evidence link", "Missing tool result or actor"],
    owner: "System and workflow owners",
    frequency: "Every run",
    source_ids: ["src_066cphd", "src_1l45nk0", "src_1px43va"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-third-party-risk",
    version: "1",
    name: "Third-party and vendor risk",
    risk: "A provider's model, service, subprocessor, availability, or terms create unassessed accounting, security, or continuity risk.",
    objective: "Understand the service boundary, data use, controls, dependencies, change process, and exit plan.",
    procedure: ["Inventory data, tools, subprocessors, and claims", "Review assurance and contract evidence", "Test failure and exit scenarios", "Monitor material changes"],
    evidence: ["Due-diligence record", "Contract and assurance evidence", "Continuity and exit plan"],
    exceptions: ["Unsupported product claim", "Unknown data use", "No export or continuity path"],
    owner: "Vendor, security, legal, and accounting owners",
    frequency: "Before use and periodically",
    source_ids: ["src_0np8u4i", "src_1bwn6bv", "src_068k4kv"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-data-governance",
    version: "1",
    name: "Data classification, privacy, and retention",
    risk: "Sensitive, personal, privileged, or regulated data is exposed, retained, reused, or destroyed improperly.",
    objective: "Limit data to the approved purpose, access, location, retention period, and disposal method.",
    procedure: ["Classify inputs and outputs", "Minimize and redact where possible", "Enforce access and retention", "Honor legal hold and disposal approval"],
    evidence: ["Data-flow and classification map", "Retention and deletion record", "Access and incident log"],
    exceptions: ["Unapproved sensitive data", "Unknown training or reuse", "Deletion during legal hold"],
    owner: "Data, privacy, legal, and system owners",
    frequency: "At design, every new data source, and periodic review",
    source_ids: ["src_gdpr2016", "src_nist88r2", "src_secr206", "src_irsrecord", "src_05o8995", "src_0pywo86", "src_1i8bgo4"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-release-evaluation",
    version: "1",
    name: "Evaluation before release",
    risk: "The agent performs poorly on material, adversarial, rare, or workflow-specific cases.",
    objective: "Demonstrate acceptable behavior on representative and high-risk cases before use expands.",
    procedure: ["Define task, risk, and evaluator criteria", "Use held-out normal, edge, and adversarial cases", "Measure end-to-end outcomes and stop behavior", "Approve against release thresholds"],
    evidence: ["Evaluation set and provenance", "Scored results", "Failure analysis and release decision"],
    exceptions: ["Only happy-path testing", "Evaluation uses training examples", "Critical failure hidden by average score"],
    owner: "System, accounting, and control owners",
    frequency: "Before first release and every material change",
    source_ids: ["src_00l4vrq", "src_18pyuyd", "src_038j28b"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-production-monitoring",
    version: "1",
    name: "Production monitoring and kill switch",
    risk: "Behavior, data, tools, cost, or controls degrade after release without detection.",
    objective: "Detect material change, policy breach, failure, and drift early enough to contain impact.",
    procedure: ["Monitor quality, exceptions, overrides, latency, tool errors, and denied actions", "Set alert and pause thresholds", "Preserve affected runs", "Require approval to resume"],
    evidence: ["Operational metrics", "Alerts and pause events", "Review and resume decision"],
    exceptions: ["Unmonitored write action", "Alert without owner", "Resume before root cause or containment"],
    owner: "Production system and accounting process owners",
    frequency: "Continuous",
    source_ids: ["src_nist137m", "src_nist137a", "src_16b4w7b", "src_0ocni66", "src_0nrsy1i"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-incident-response",
    version: "1",
    name: "Incident containment, rollback, and evidence preservation",
    risk: "An erroneous or unauthorized action continues, evidence is lost, or affected accounting records remain uncorrected.",
    objective: "Stop impact, preserve evidence, determine scope, correct records, and learn before resuming.",
    procedure: ["Disable affected tools or policy path", "Preserve runs, approvals, and system evidence", "Identify affected populations and outputs", "Reverse or compensate through authorized procedures", "Retest and approve resume"],
    evidence: ["Incident timeline", "Affected-record register", "Correction, evaluation, and resume approval"],
    exceptions: ["Evidence deleted", "Unbounded affected population", "Silent correction or premature resume"],
    owner: "Incident commander with accounting, security, legal, and system owners",
    frequency: "On incident with periodic exercises",
    source_ids: ["src_nist61r3", "src_16b4w7b", "src_0pywo86", "src_0fa9af9"],
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "ctrl-assessment-separation",
    version: "1",
    name: "Control performance and assessment separation",
    risk: "The system that performs or prepares a control also concludes that the control operated effectively.",
    objective: "Keep preparation and performance evidence separate from management's or the auditor's final assessment.",
    procedure: ["Identify preparer, performer, owner, tester, and assessor", "Preserve exceptions and limitations", "Require independent human evaluation where the framework demands it"],
    evidence: ["Role assignment", "Control workpaper", "Independent assessment and sign-off"],
    exceptions: ["Self-assessment by the agent", "Exception suppressed before assessor review", "Unattributed conclusion"],
    owner: "Management evaluator, internal audit, or external auditor as applicable",
    frequency: "Every control assessment",
    source_ids: ["src_sec13a15", "src_sec8238", "src_075usnq", "src_1qpx6gc", "src_122i1et"],
    reviewed_at: corpusReviewedAt,
  },
];

function assertUniqueIds(records: Array<{ id: string }>, label: string) {
  if (new Set(records.map((record) => record.id)).size !== records.length) {
    throw new Error(`${label} IDs must be unique`);
  }
}

assertUniqueIds(sensitiveActions, "Sensitive action");
assertUniqueIds(controlPatterns, "Control pattern");
