import {
  corpusReviewedAt,
  type GlossaryEntry,
  type TemplateRecord,
} from "./domain-model";

function fields(items: Array<[string, string]>) {
  return items.map(([heading, prompt]) => ({ heading, prompt }));
}

export const templates: TemplateRecord[] = [
  {
    id: "tpl-workflow-specification",
    version: "1",
    name: "Workflow specification",
    purpose: "Define the accounting objective, evidence, procedure, limits, checks, outputs, and accountable roles before building or running an agent workflow.",
    use_when: "Before a pilot, material change, or expansion of data, tools, scope, or authority.",
    sections: fields([
      ["Objective", "State the accounting outcome and why it matters."],
      ["Scope", "Name entity, period, population, jurisdiction, and explicit exclusions."],
      ["Owners", "Name preparer, process owner, reviewer, approver, and system owner."],
      ["Inputs", "List authoritative sources, expected fields, control totals, and access."],
      ["Procedure", "Describe ordered agent and deterministic steps."],
      ["Authority", "Assign A0–A4 or human-only to each action."],
      ["Checks", "List calculations, schema tests, tie-outs, and policy gates."],
      ["Exceptions", "Define materiality, tolerance, routing, and stop conditions."],
      ["Outputs", "Define workpaper, proposed effects, and reviewer packet."],
      ["Record", "Specify source lineage, versions, tool calls, approvals, and retention."],
      ["Evaluation", "Define normal, edge, adversarial, and regression cases."],
      ["Production", "Define monitoring, kill switch, incident owner, and recovery."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-authority-matrix",
    version: "1",
    name: "Authority matrix",
    purpose: "Map each workflow action to agent permission, human responsibility, system enforcement, and evidence.",
    use_when: "Designing tools, approvals, segregation of duties, or expansion beyond read-only work.",
    sections: fields([
      ["Action", "Name the smallest independently authorizable action."],
      ["Risk", "State reversibility, materiality, external effect, and legal or fiduciary impact."],
      ["Authority level", "Assign A0, A1, A2, A3, A4, or human-only."],
      ["Agent role", "State what the agent may read, prepare, recommend, or execute."],
      ["Human role", "Name the person who decides, approves, attests, or certifies."],
      ["Enforcement", "Name the deterministic permission, limit, and approval check."],
      ["Evidence", "Specify payload, approval, execution, and reconciliation records."],
      ["Recovery", "Define reversal, compensation, escalation, and kill switch."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-source-register",
    version: "1",
    name: "Source register",
    purpose: "Preserve the origin, scope, version, authority, control totals, and use of every material input.",
    use_when: "Every evidence-linked accounting, control, audit, tax, or research workflow.",
    sections: fields([
      ["Source ID", "Assign a stable identifier."],
      ["Owner and system", "Name the source owner, system, repository, or publisher."],
      ["Description", "Describe the population or document and intended use."],
      ["Entity and period", "Record scope, jurisdiction, dates, and extraction parameters."],
      ["Version", "Record file, query, form, rule, or publication version."],
      ["Control totals", "Record counts, amounts, balances, hashes, or page totals."],
      ["Authority", "Classify as rule, official guidance, technical reference, evidence, or practice example."],
      ["Access and rights", "Record access limits, confidentiality, and publisher terms."],
      ["Limitations", "State missing data, reliability concerns, and applicability limits."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-agent-run-record",
    version: "1",
    name: "Agent run record",
    purpose: "Create a reproducible accounting record of what the system attempted, used, decided, produced, and stopped on.",
    use_when: "Every governed agent run.",
    sections: fields([
      ["Run identity", "Record workflow ID, run ID, timestamp, entity, period, and owner."],
      ["Objective and scope", "Record the approved objective, population, and exclusions."],
      ["Configuration", "Record model, prompt, policy, tool, template, and evaluator versions."],
      ["Sources", "Link the source register and reproduced control totals."],
      ["Plan and procedures", "Record selected steps and deviations from the approved method."],
      ["Tool calls", "Record inputs, authorization decision, result, and error for each call."],
      ["Calculations", "Link deterministic calculations and tie-outs."],
      ["Exceptions", "List missing, contradictory, material, and prohibited conditions."],
      ["Output", "Link the workpaper, recommendation, proposed payload, and limitations."],
      ["Disposition", "Record reviewer decision, approvals, execution receipt, and final status."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-reviewer-packet",
    version: "1",
    name: "Workpaper and reviewer packet",
    purpose: "Give the accountable reviewer enough evidence to understand, challenge, reproduce, and decide the work.",
    use_when: "Before any conclusion, approval, posting, filing, payment, control assessment, or external use.",
    sections: fields([
      ["Executive summary", "State objective, result, proposed effects, and decision required."],
      ["Scope and materiality", "State entity, period, population, thresholds, and exclusions."],
      ["Sources", "Provide source register and control totals."],
      ["Procedure", "Describe work performed and deterministic checks."],
      ["Results", "Show calculations, matches, classifications, and tie-outs."],
      ["Exceptions", "Present unresolved, contradictory, unusual, and prohibited matters prominently."],
      ["Proposed effects", "Show exact entry, action, communication, or filing payload."],
      ["Review decision", "Capture approve, modify, reject, escalate, conditions, actor, and time."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-proposed-journal-entry",
    version: "1",
    name: "Proposed journal entry",
    purpose: "Present the exact supported accounting effect for review without implying approval or posting.",
    use_when: "A workflow identifies a needed ledger adjustment.",
    sections: fields([
      ["Purpose", "State the business event and accounting objective."],
      ["Entity and period", "Record ledger, entity, period, currency, and posting date."],
      ["Lines", "List account, debit, credit, dimensions, counterparty, and line explanation."],
      ["Reversal", "State whether, when, and how the entry reverses."],
      ["Calculation", "Link the independently reproducible calculation."],
      ["Support", "Link authoritative and transaction evidence."],
      ["Policy basis", "State applicable policy and judgment."],
      ["Checks", "Record balance, duplicate, period, account, threshold, and payload validation."],
      ["Approval", "Name required reviewer, approver, and authority limit."],
      ["Posting result", "After execution, record document ID, receipt, tie-out, and any correction."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-exception-log",
    version: "1",
    name: "Exception log",
    purpose: "Keep unresolved and unusual matters visible, owned, evidenced, and traceable to final disposition.",
    use_when: "A source, calculation, policy, permission, threshold, or result does not meet the expected condition.",
    sections: fields([
      ["Exception ID", "Assign stable ID and link affected workflow and run."],
      ["Condition", "State the observed fact, expected condition, and difference."],
      ["Population impact", "Quantify affected records, amount, entities, periods, and downstream outputs."],
      ["Evidence", "Link source and contradictory evidence."],
      ["Risk", "State accounting, control, security, legal, tax, or operational effect."],
      ["Severity", "Apply approved materiality and escalation criteria."],
      ["Owner", "Name accountable resolver and due date."],
      ["Action", "Record hold, investigate, correct, compensate, or accept."],
      ["Resolution", "Link evidence, approval, correction, and retest."],
      ["Status", "Record open, contained, resolved, accepted, or superseded with timestamp."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-evaluation-plan",
    version: "1",
    name: "Evaluation plan",
    purpose: "Define how the workflow will be tested before release and after material change.",
    use_when: "Building, changing, or expanding an agent workflow.",
    sections: fields([
      ["Decision", "State the release or expansion decision the evaluation informs."],
      ["Tasks", "Define end-to-end objectives and public interfaces under test."],
      ["Risks", "Rank material, irreversible, rare, adversarial, and control-bypass failures."],
      ["Cases", "Specify normal, edge, contradictory, malicious, and stop-condition cases."],
      ["Source of truth", "State independent expected results and provenance."],
      ["Evaluators", "Define deterministic and human scoring criteria."],
      ["Metrics", "Set per-risk thresholds, not only average scores."],
      ["Regression", "Identify fixed cases that every version must continue to pass."],
      ["Failure review", "Require root cause, affected scope, and remediation."],
      ["Release decision", "Record approver, conditions, residual risk, and monitoring."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-pilot-scorecard",
    version: "1",
    name: "Pilot scorecard",
    purpose: "Compare the agent-assisted workflow with the approved baseline and decide whether to stop, continue, or expand.",
    use_when: "During shadow, draft-only, supervised, and limited-production stages.",
    sections: fields([
      ["Scope", "Record workflow version, population, period, users, and authority."],
      ["Coverage", "Measure processed, excluded, unresolved, and failed items."],
      ["Quality", "Measure calculation, classification, citation, and exception accuracy."],
      ["Control", "Measure tie-outs, stops, denied actions, and approval integrity."],
      ["Review", "Measure reviewer rework, overrides, disagreement, and time."],
      ["Operations", "Measure cycle time, latency, tool errors, and cost."],
      ["Incidents", "Record material errors, near misses, security events, and downstream corrections."],
      ["Decision", "Record stop, continue, remediate, or expand with owner and conditions."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-production-change",
    version: "1",
    name: "Production change record",
    purpose: "Make every material model, prompt, policy, tool, source, template, or evaluator change attributable and reversible.",
    use_when: "Before changing a production workflow or its dependency.",
    sections: fields([
      ["Change", "Identify old and new artifact, version, owner, and reason."],
      ["Affected scope", "List workflows, data, tools, entities, users, and controls."],
      ["Risk", "Describe changed behavior and worst credible failure."],
      ["Testing", "Link unit, integration, regression, and adversarial results."],
      ["Data", "Record new data use, rights, privacy, retention, and migration."],
      ["Authority", "Confirm permission and approval behavior is unchanged or separately approved."],
      ["Deployment", "State rollout, canary, monitoring, and pause thresholds."],
      ["Rollback", "Name prior version, rollback steps, and data reconciliation."],
      ["Approval", "Record accounting, control, security, and system approvals."],
      ["Post-change review", "Record actual metrics, incidents, and final acceptance."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-incident-report",
    version: "1",
    name: "Incident report",
    purpose: "Contain impact, preserve evidence, correct accounting records, and prevent recurrence.",
    use_when: "A workflow performs or attempts an unauthorized, erroneous, misleading, insecure, or unreproducible action.",
    sections: fields([
      ["Detection", "Record time, reporter, alert, and observed condition."],
      ["Containment", "Record tools, credentials, workflows, or versions paused."],
      ["Scope", "Identify affected runs, records, entities, periods, users, and external parties."],
      ["Timeline", "Record source, model, tool, approval, execution, and response events."],
      ["Evidence", "Preserve traces, workpapers, approvals, payloads, system logs, and communications."],
      ["Accounting impact", "Quantify entries, balances, reports, controls, filings, payments, and disclosures."],
      ["Correction", "Record reversal, compensation, restatement, notification, and validation."],
      ["Root cause", "Separate model, data, prompt, policy, tool, authorization, process, and review causes."],
      ["Remediation", "Assign changes, tests, owners, due dates, and residual risk."],
      ["Resume decision", "Record retest, approval, monitoring, and conditions for restoration."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-control-design",
    version: "1",
    name: "Control design and walkthrough",
    purpose: "Document the risk, control objective, population, procedure, precision, evidence, ownership, and system dependencies.",
    use_when: "Designing or changing an agent-assisted control or a control that depends on agent output.",
    sections: fields([
      ["Risk", "State the risk of material misstatement or other controlled risk."],
      ["Objective", "State what the control prevents or detects."],
      ["Owner", "Name performer, reviewer, assessor, and system owner."],
      ["Frequency", "State trigger and timing."],
      ["Population", "Define source, completeness, scope, and control totals."],
      ["Procedure", "Describe human, agent, tool, and deterministic steps."],
      ["Precision", "State threshold, expectation, and level of aggregation."],
      ["Evidence", "Define workpaper, source, review, approval, and retention."],
      ["Exceptions", "Define identification, routing, resolution, and escalation."],
      ["Dependencies", "List reports, models, prompts, policies, tools, access, and dependent controls."],
      ["Walkthrough", "Trace a representative transaction and confirm current operation."],
      ["Assessment", "Keep performance evidence separate from final design or effectiveness assessment."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-control-test",
    version: "1",
    name: "Control test",
    purpose: "Test specified control attributes against an approved population and plan without allowing the system to assess itself.",
    use_when: "Management, internal audit, or an auditor tests control performance.",
    sections: fields([
      ["Control and objective", "Identify control version, risk, assertion, and owner."],
      ["Period and population", "Record source, parameters, control totals, and completeness evidence."],
      ["Test plan", "State nature, timing, extent, sample, and attributes."],
      ["Selection", "Document independently reproducible sample or full-population logic."],
      ["Procedure", "Record work performed for each attribute."],
      ["Evidence", "Link source evidence for each item and result."],
      ["Exceptions", "State fact, criterion, population effect, and owner response."],
      ["Additional procedures", "Record expansion, corroboration, or retest."],
      ["Result", "Summarize results without making an unassigned assurance conclusion."],
      ["Review", "Capture attributable tester and reviewer sign-off."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
  {
    id: "tpl-technical-memo",
    version: "1",
    name: "Technical-accounting memo",
    purpose: "Document a fact-specific, source-linked accounting analysis and accountable conclusion.",
    use_when: "A transaction or policy question requires authoritative research and material judgment.",
    sections: fields([
      ["Issue", "State the accounting question and requested decision."],
      ["Scope", "State entity, transaction, period, framework, jurisdiction, and exclusions."],
      ["Facts", "Present verified facts separately from assumptions and unknowns."],
      ["Literature", "Cite current authoritative requirements and applicability."],
      ["Analysis", "Apply facts to requirements step by step."],
      ["Alternatives", "Present reasonable alternatives and contrary evidence."],
      ["Conclusion", "State the approved conclusion, significant judgments, and uncertainty."],
      ["Accounting effects", "Show recognition, measurement, presentation, disclosure, and entries."],
      ["Controls and follow-up", "State evidence, monitoring, reassessment, and policy implications."],
      ["Approval", "Capture preparer, technical reviewer, accountable approver, version, and date."],
    ]),
    reviewed_at: corpusReviewedAt,
  },
];

const glossarySeeds: Array<[string, string, string[]]> = [
  ["Accounting agent", "A system that pursues a defined accounting objective, selects steps, uses approved tools and evidence, inspects results, and continues until completion or a stop condition.", ["authority level", "run record", "tool"]],
  ["Accounting objective", "The specific recognition, measurement, presentation, disclosure, control, audit, tax, or operational outcome a workflow is intended to support.", ["workflow specification", "scope"]],
  ["Agent trace", "Technical event history used to diagnose model, tool, policy, and orchestration behavior. It does not replace an accounting workpaper.", ["run record", "workpaper"]],
  ["Approval payload", "The exact decision or action content presented for approval, preserved so later execution cannot silently differ.", ["human approval", "payload drift", "A3"]],
  ["Authority level", "A classification of what an agent may explain, prepare, recommend, or execute and what remains human-owned.", ["A0", "A1", "A2", "A3", "A4", "human-only"]],
  ["A0", "Explain using approved sources without changing a work record or taking an action.", ["authority level"]],
  ["A1", "Prepare evidence-linked work using read-only or draft-only tools; a person performs any external action.", ["authority level"]],
  ["A2", "Recommend a conclusion or action while a named person decides.", ["authority level", "judgment"]],
  ["A3", "Execute one constrained action only after approval of the exact payload and independent system validation.", ["authority level", "approval payload"]],
  ["A4", "Execute low-risk, reversible actions inside deterministic policy with monitoring and exception routing.", ["authority level", "policy engine"]],
  ["Human-only", "A responsibility that may be supported but not delegated, such as final approval, legal attestation, fiduciary authority, or certification.", ["authority level", "accountability"]],
  ["Accountability", "Attributable responsibility for a conclusion, action, representation, control, or certification.", ["approval", "owner"]],
  ["Authoritative source", "A rule, standard, regulation, contract, system of record, or other source that has authority for the question being answered.", ["applicability", "source register"]],
  ["Applicability", "The basis for concluding that a source or requirement pertains to the entity, transaction, period, jurisdiction, and question.", ["authoritative source", "jurisdiction"]],
  ["Control total", "An independently reproducible count, amount, balance, hash, or other total used to establish population completeness and accuracy.", ["population", "tie-out"]],
  ["Contradictory evidence", "Information that conflicts with a proposed fact, classification, estimate, or conclusion and must remain visible to the reviewer.", ["evidence", "exception"]],
  ["Deterministic check", "A reproducible rule, calculation, permission, schema validation, or tie-out that does not depend on model judgment.", ["policy engine", "tie-out"]],
  ["Evidence", "Information used to support an observation, claim, procedure, conclusion, approval, or action.", ["source register", "workpaper"]],
  ["Exception", "A missing, contradictory, out-of-policy, material, unauthorized, or otherwise unresolved condition requiring disposition.", ["stop condition", "exception routing"]],
  ["Exception routing", "Assignment of an exception to an accountable owner, procedure, deadline, and escalation path.", ["exception", "stop condition"]],
  ["External action", "An act that changes a system or record, moves cash, submits a filing, sends a communication, or otherwise affects a party outside the draft workpaper.", ["A3", "sensitive action"]],
  ["Human in the loop", "A specific attributable human decision or action embedded at the point where authority is required, not merely general oversight.", ["human approval", "authority level"]],
  ["Human approval", "An authenticated and attributable decision by an authorized person over the exact scope, evidence, and payload.", ["approval payload", "accountability"]],
  ["ICFR", "Internal control over financial reporting: the processes and controls that support reliable external financial reporting under the applicable framework.", ["control", "management review control"]],
  ["Idempotency", "A property that prevents repeated requests from creating duplicate effects, commonly through a unique action key and system enforcement.", ["A3", "sensitive action"]],
  ["Jurisdiction", "The legal, regulatory, tax, accounting, or professional regime applicable to the entity or activity.", ["applicability"]],
  ["Least privilege", "Granting only the minimum data, fields, tools, actions, limits, and duration necessary for the approved objective.", ["tool", "zero trust"]],
  ["Management review control", "A control in which management evaluates information at a defined level of precision and follows up on identified matters.", ["ICFR", "precision"]],
  ["Materiality", "The magnitude and nature threshold used by accountable people to determine whether information or error could influence a decision under the applicable framework.", ["threshold", "judgment"]],
  ["Model output", "Content produced by the model. It is a proposal or input until validated and assigned authority through the workflow.", ["deterministic check", "authority level"]],
  ["Payload drift", "A difference between the content approved and the content later executed or submitted.", ["approval payload", "A3"]],
  ["Policy engine", "Deterministic software that evaluates identity, approval, scope, limits, and allowed actions outside the model.", ["A4", "deterministic check"]],
  ["Population", "The complete set of records, transactions, controls, or items to which a procedure or conclusion applies.", ["control total", "scope"]],
  ["Precision", "How specifically a control or procedure defines its expectation, threshold, and follow-up so it can detect the relevant error.", ["management review control", "threshold"]],
  ["Provenance", "The origin, custody, version, transformation, and retrieval history of data, evidence, or content.", ["source register", "evidence"]],
  ["Reviewer packet", "The evidence, procedure, calculation, exceptions, proposed effects, and decision interface given to the accountable reviewer.", ["workpaper", "human approval"]],
  ["Run record", "The durable record of objective, sources, procedures, versions, tool calls, calculations, exceptions, approvals, and disposition for one run.", ["agent trace", "workpaper"]],
  ["Segregation of duties", "Separation of incompatible responsibilities so one person or system cannot initiate, approve, execute, record, and conceal the same action.", ["least privilege", "sensitive action"]],
  ["Sensitive action", "An action with material, irreversible, externally attributable, fiduciary, legal, privacy, security, or certification consequences.", ["A3", "human-only"]],
  ["Source register", "A structured inventory of material inputs and references with owner, version, scope, control totals, authority, access, and limitations.", ["provenance", "authoritative source"]],
  ["Stop condition", "A predefined condition that blocks continuation and requires exception routing rather than model improvisation.", ["exception", "policy engine"]],
  ["System of record", "The authoritative application or repository for a defined business object or accounting record.", ["authoritative source", "provenance"]],
  ["Threshold", "A deterministic or human-approved limit for materiality, tolerance, escalation, action, or exception.", ["materiality", "precision"]],
  ["Tie-out", "A reproducible demonstration that two related totals, balances, schedules, or reports agree or that every difference is explained.", ["control total", "deterministic check"]],
  ["Tool", "A constrained interface through which the system reads data, performs a deterministic function, or requests an action.", ["least privilege", "policy engine"]],
  ["Workpaper", "The accounting-facing record that explains the objective, evidence, procedures, results, exceptions, conclusion, preparer, and reviewer.", ["run record", "reviewer packet"]],
  ["Zero trust", "An access approach that authenticates and authorizes each request under least privilege rather than trusting network location or prior access.", ["least privilege", "tool"]],
];

export const glossary: GlossaryEntry[] = glossarySeeds.map(([term, definition, related]) => ({
  id: `term-${term.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
  term,
  definition,
  related,
}));

if (templates.length !== 14) throw new Error(`Expected 14 templates; received ${templates.length}`);
if (new Set(templates.map((template) => template.id)).size !== templates.length) throw new Error("Template IDs must be unique");
if (new Set(glossary.map((entry) => entry.id)).size !== glossary.length) throw new Error("Glossary IDs must be unique");
