export const readingRoomScholarshipResources = [
  {
    id: "src_0bneozy",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Commerford, Eilifsen, Hatfield, Holmstrom, and Kinserdal",
    title: "Control issues: How providing input affects auditors' reliance on artificial intelligence",
    date: "Peer-reviewed; 2024",
    jurisdiction: "Experienced-auditor experiment; Norway and United States context",
    access: "Abstract open; article access varies",
    note: "Experienced-auditor experiments and interviews find that consequential input can change reliance on AI-produced estimate evidence. The study tests perceived control in a bounded estimate task, not production-agent accuracy or longitudinal audit quality.",
    href: "https://doi.org/10.1111/1911-3846.12974",
  },
  {
    id: "src_0vks953",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Li, Brazel, Gold, and Leiby",
    title: "Inheriting Versus Developing Data Analytic Tests and Auditors' Professional Skepticism",
    date: "Peer-reviewed; 2026",
    jurisdiction: "Experiment with experienced Dutch auditors",
    access: "Open access",
    note: "Auditors who inherited an analytic test took fewer skeptical actions than those who developed it; a development memo mitigated part of the effect. The study concerns audit analytics and psychological ownership, not generative agents.",
    href: "https://doi.org/10.1111/1475-679X.70014",
  },
  {
    id: "src_1vsed7d",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Ulla and Commerford",
    title: "Reliance on Algorithmic Estimates: The Joint Influence of Algorithm Adaptability and Estimation Uncertainty",
    date: "Peer-reviewed; 2025",
    jurisdiction: "Auditor and preparer experiments",
    access: "Abstract open; article access varies",
    note: "Two experiments show that professionals' willingness to use learning rather than static algorithms depends on estimation uncertainty. Reliance is not correctness, and the stylized setting omits live-agent drift and production controls.",
    href: "https://doi.org/10.2308/TAR-2024-0109",
  },
  {
    id: "src_037ngna",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Peecher, Pietsch, Stirnkorb, and Yamoah",
    title: "Coping With Changing Skill Requirements: Does Disaffirmation Versus Affirmation Affect Auditors' Reliance on AI-Supported Advice From Specialists?",
    date: "Peer-reviewed; online 2026",
    jurisdiction: "Experiments with highly experienced auditors",
    access: "Abstract open; article access varies",
    note: "Experiments suggest that threats to professional self-concept can cause experienced auditors to discount useful AI-supported specialist advice. A short experimental affirmation is not evidence for a firmwide training program.",
    href: "https://doi.org/10.1111/1911-3846.70040",
  },
  {
    id: "src_0vuruu2",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Joe Croom",
    title: "Interactivity and Illusions of Ability: How Using Generative AI Affects Investor Judgments",
    date: "Peer-reviewed; online 2025",
    jurisdiction: "Investor laboratory experiments",
    access: "Abstract open; article access varies",
    note: "Interactive GenAI interfaces increased users' self-assessed ability and, in some tasks, hindered processing or inflated willingness to invest. The participants were investors in controlled tasks, so transfer to accountant review interfaces is a design warning rather than direct accounting evidence.",
    href: "https://doi.org/10.1111/1475-679X.70017",
  },
  {
    id: "src_1abvnlq",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Libby and Witz",
    title: "Can artificial intelligence reduce the effect of independence conflicts on audit firm liability?",
    date: "Peer-reviewed; 2024",
    jurisdiction: "United States juror experiments",
    access: "Publisher abstract and PDF; access varies",
    note: "Juror experiments show that AI use can change perceptions of objectivity, trust, and liability when independence is questioned. Perceived liability does not establish actual independence, audit quality, or a safe basis for replacing professional judgment.",
    href: "https://doi.org/10.1111/1911-3846.12941",
  },
  {
    id: "src_095yto0",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Musaib Ashraf",
    title: "Does automation improve financial reporting? Evidence from internal controls",
    date: "Peer-reviewed; 2025",
    jurisdiction: "United States public companies and ICFR",
    access: "Abstract open; article access varies",
    note: "Archival evidence associates disclosed accounting automation with fewer ICFR material weaknesses, while later monitoring declines and remaining failures can be more consequential. Automation is text-inferred and combines several technologies, so the study does not isolate generative agents or prove causality.",
    href: "https://doi.org/10.1007/s11142-024-09822-y",
  },
  {
    id: "src_1leuoiu",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Alsaif, Phan, Kend, and Alharbi",
    title: "Emerging Technologies in External Audit and How They Are Challenging Auditors' Judgements and Decision-Making Processes",
    date: "Peer-reviewed; 2025",
    jurisdiction: "Exploratory study with external auditors",
    access: "Open access",
    note: "Verbal-protocol and interview evidence links easy-to-obtain analytics with heuristics, overreliance, and loss of objectivity when tool understanding is limited. The sample is small and concerns broad audit analytics rather than generative agents.",
    href: "https://doi.org/10.1111/acfi.70043",
  },
  {
    id: "src_10ub0wu",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Zhang, Cho, and Vasarhelyi",
    title: "Explainable Artificial Intelligence (XAI) in auditing",
    date: "Peer-reviewed; 2022",
    jurisdiction: "General audit methods",
    access: "Abstract open; article access varies",
    note: "A methods paper connects LIME and SHAP explanations to audit evidence and documentation through a risk-of-material-misstatement demonstration. Post-hoc attribution does not prove causal reasoning, data quality, or model validity and can create unwarranted confidence.",
    href: "https://doi.org/10.1016/j.accinf.2022.100572",
  },
  {
    id: "src_18zatvq",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Barr-Pulliam, Calvin, Eulerich, and Maghakyan",
    title: "Audit evidence, technology, and judgement: A review of the literature in response to ED-500",
    date: "Peer-reviewed review; 2024",
    jurisdiction: "International audit evidence",
    access: "Open access",
    note: "A standards-adjacent synthesis of technology, audit evidence, judgment, and skepticism research, including whether machine-generated evidence is primary or corroborative. Its literature window predates the current agent wave and responds to an exposure draft.",
    href: "https://doi.org/10.1111/jifm.12192",
  },
  {
    id: "src_1uogv2b",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Dahabiyeh and Mowafi",
    title: "Challenges of using RPA in auditing: A socio-technical systems approach",
    date: "Peer-reviewed; 2023",
    jurisdiction: "Jordan; external audit firms",
    access: "Abstract open; article access varies",
    note: "Interviews surface client-system readiness, data-format, false-positive, privacy, skill, and acceptance constraints across audit phases. The small Jordanian study concerns rule-based RPA, not generative agents, but its boundary problems transfer to deployment design.",
    href: "https://doi.org/10.1002/isaf.1537",
  },
  {
    id: "src_0hqji5v",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Faulconbridge and Sarwar",
    title: "How Professionals Adapt to Artificial Intelligence: The Role of Intertwined Boundary Work",
    date: "Peer-reviewed; 2025",
    jurisdiction: "United Kingdom professional-services firms",
    access: "Open access",
    note: "Document and interview evidence from accounting and law firms shows AI adoption changing tasks, services, professional boundaries, career paths, and collaboration with technologists. The study predates generative AI and does not measure productivity or employment outcomes.",
    href: "https://doi.org/10.1111/joms.12936",
  },
  {
    id: "src_17ktxqn",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Amaya and Holweg",
    title: "Using algorithms to improve knowledge work",
    date: "Peer-reviewed; 2024",
    jurisdiction: "Multinational energy company; includes internal audit",
    access: "Publisher full text; access varies",
    note: "A two-year field study distinguishes task automation from process redesign; an internal-audit NLP project failed when terminology and surrounding work were not redesigned. It is one-firm evidence from pre-agent ML, NLP, and RPA projects.",
    href: "https://doi.org/10.1002/joom.1296",
  },
  {
    id: "src_14drdzw",
    topic: "Audit and assurance",
    kind: "Research paper",
    owner: "Lajoie and Gendron",
    title: "From audit machines to tech-savvy auditors: Auditors' quest for professional security with respect to digital transformation",
    date: "Peer-reviewed; online 2025",
    jurisdiction: "Canadian Big Four audit",
    access: "Abstract open; article access varies",
    note: "Interviews examine autonomy, deskilling, identity, and the institutional narrative that technology complements professionals. One national Big Four context and retrospective accounts limit generalization to current agent deployments.",
    href: "https://doi.org/10.1111/1911-3846.70002",
  },
  {
    id: "src_1mqbz47",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Humlum and Vestergaard",
    title: "Still Waters, Rapid Currents: Early Labor Market Transformation under Generative AI",
    date: "NBER working paper; revised Mar 2026",
    jurisdiction: "Denmark; exposed occupations",
    access: "Open abstract; NBER PDF policy applies",
    note: "Linked surveys and administrative records show widespread AI-related task reorganization but no detectable earnings or hours effects over two years. It is a non-peer-reviewed working paper about exposed occupations, not accountants specifically.",
    href: "https://www.nber.org/papers/w33777",
  },
  {
    id: "src_09438v4",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Khalid Abbas",
    title: "Management accounting and artificial intelligence: A comprehensive literature review and recommendations for future research",
    date: "Peer-reviewed; 2026",
    jurisdiction: "Global management-accounting literature",
    access: "Open access",
    note: "A systematic review of 91 studies maps AI effects on information, structures, privacy, skills, professional boundaries, and multidisciplinary collaboration in management accounting. The heterogeneous literature spans digitalization through LLMs and is synthesis rather than causal evidence.",
    href: "https://doi.org/10.1016/j.bar.2025.101551",
  },
  {
    id: "src_06v2vde",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Rautiainen, Scapens, Järvenpää, Auvinen, and Sajasalo",
    title: "Towards fluid role identity of management accountants: A case study of a Finnish bank",
    date: "Peer-reviewed; 2024",
    jurisdiction: "Finland; regulated bank",
    access: "Open access",
    note: "A bank case study finds controllers moving among accounting, business-partner, and IT-specialist identities in cross-disciplinary teams amid digitalization, AI, and RPA. One organization cannot establish performance gains or isolate AI's contribution.",
    href: "https://doi.org/10.1016/j.bar.2024.101341",
  },
  {
    id: "src_06ouxpb",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Radcliffe, Spence, and Stein",
    title: "Tax, Technology, and Craftsmanship",
    date: "Peer-reviewed; article in advance 2025",
    jurisdiction: "Professional tax practice",
    access: "Publisher marks article free",
    note: "A multimethod qualitative study finds greater automation acceptance in tax compliance than in advisory work, explained through professional craftsmanship. It is not agent-specific, and professional narratives and adoption patterns can change.",
    href: "https://doi.org/10.2308/TAR-2024-0499",
  },
  {
    id: "src_0crvww7",
    topic: "Law and policy",
    kind: "Research paper",
    owner: "Battaglini, Guiso, Lacava, Miller, and Patacchini",
    title: "Refining public policies with machine learning: The case of tax auditing",
    date: "Peer-reviewed; 2025",
    jurisdiction: "Italy; sole-proprietor tax audits",
    access: "Open access",
    note: "Population tax-return and audit data support counterfactual audit-selection analysis while making selective labels and fairness explicit. Historical Italian data and simulated policy substitutions do not establish live-deployment legitimacy or causal effects.",
    href: "https://doi.org/10.1016/j.jeconom.2024.105847",
  },
  {
    id: "src_0731a9b",
    topic: "Law and policy",
    kind: "Research paper",
    owner: "Koivula, Shamsuzzoha, and Shamsuzzaman",
    title: "Application of artificial intelligence as a knowledge creation instrument in tax procedures",
    date: "Peer-reviewed; 2024",
    jurisdiction: "Finnish Tax Administration",
    access: "Open access",
    note: "Action-design research built and evaluated ML artifacts for a narrow income-tax claim, then bounded them to knowledge creation for legal and ethical reasons. Reported classification performance does not establish fair or lawful automated decisions.",
    href: "https://doi.org/10.1016/j.engappai.2024.108417",
  },
  {
    id: "src_0b5xcz9",
    topic: "Law and policy",
    kind: "Research paper",
    owner: "Aula, Hillo, and Erkkilä",
    title: "AI in Taxation — Experimental evidence on citizen design preferences and perceptions of legitimacy",
    date: "Peer-reviewed; 2026",
    jurisdiction: "Finland; citizen survey experiments",
    access: "Open access",
    note: "Probability-sample experiments find lower support for independent AI decisions, private involvement, and commercial or social-media data in taxation. The outcomes are perceptions in fictional scenarios, not accuracy or compliance effects.",
    href: "https://doi.org/10.1016/j.giq.2026.102147",
  },
  {
    id: "src_19wwipt",
    topic: "Law and policy",
    kind: "Research paper",
    owner: "Stephen Daly",
    title: "Artificial Intelligence, the Rule of Law and Public Administration: The Case of Taxation",
    date: "Peer-reviewed legal analysis; 2024",
    jurisdiction: "Germany, Netherlands, Slovakia, and United Kingdom",
    access: "Open access",
    note: "Comparative legal analysis frames legality, reasons, guidance, opacity, and finality for AI in tax administration. It is doctrinal rather than technical or outcome validation, and jurisdiction-specific conclusions require current-law checks.",
    href: "https://doi.org/10.1017/S0008197324000448",
  },
  {
    id: "src_0lu0n1e",
    topic: "Law and policy",
    kind: "Research paper",
    owner: "Faúndez-Ugalde, Mellado-Silva, and Aldunate-Lizana",
    title: "Use of artificial intelligence by tax administrations: An analysis regarding taxpayers' rights in Latin American countries",
    date: "Peer-reviewed legal analysis; 2020",
    jurisdiction: "Latin America",
    access: "Abstract open; article access varies",
    note: "Comparative legal analysis argues that taxpayers need sufficient information to contest AI-influenced risk characterization and robotized audits. It reflects heterogeneous legal systems as of 2020 and does not evaluate model accuracy.",
    href: "https://doi.org/10.1016/j.clsr.2020.105441",
  },
  {
    id: "src_1ajsfuw",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Guenther, Peterson, Searcy, and Williams",
    title: "How Useful Are Tax Disclosures in Predicting Effective Tax Rates? A Machine Learning Approach",
    date: "Peer-reviewed; 2023",
    jurisdiction: "Public-company tax disclosures",
    access: "Abstract open; article access varies",
    note: "An archival study compares machine and analyst-implied effective-tax-rate forecasts and uses Shapley values to examine disclosure usefulness. Forecasting is not tax advice or administration, and feature importance is not causal explanation.",
    href: "https://doi.org/10.2308/TAR-2021-0398",
  },
  {
    id: "src_0hwi8yi",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Blondeel, Bullock, Gaskin, Schuetzler, Serre, Steffen, Wells, and Wood",
    title: "The effects of generative artificial intelligence on learning in an accounting data analytics course",
    date: "Peer-reviewed; 2025",
    jurisdiction: "One undergraduate accounting course",
    access: "Abstract open; article access varies",
    note: "Course and survey data associate ChatGPT expertise, rather than mere access or use frequency, with performance, especially for students with lower prior GPA. The one-cohort observational design does not support causal learning claims.",
    href: "https://doi.org/10.1016/j.jaccedu.2025.100987",
  },
  {
    id: "src_1376dbb",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Ballantine, Boyce, and Stoner",
    title: "A critical review of AI in accounting education: Threat and opportunity",
    date: "Peer-reviewed essay; 2024",
    jurisdiction: "Accounting education",
    access: "Open access",
    note: "A critical review argues that GenAI can move accounting education toward judgment, critique, ethics, and accounting's social consequences rather than technical reductionism. It is conceptual and does not measure student learning or workplace performance.",
    href: "https://doi.org/10.1016/j.cpa.2024.102711",
  },
  {
    id: "src_1smh725",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Tharapos, Lau, Peszynski, Nguyen, Magdziarz, Morton, Borg, and Duan",
    title: "Generative AI in Accounting Education: Evaluating ChatGPT's Role in Assessment and Skill Development",
    date: "Peer-reviewed; online 2025",
    jurisdiction: "One Australian undergraduate accounting program",
    access: "Abstract open; article access varies",
    note: "A GPT-3.5 assessment study found stronger performance on lower- and mid-order tasks than higher-order analysis and evaluation, informing process evidence and assessment redesign. It is a one-program snapshot of an obsolete model, not student-learning evidence.",
    href: "https://doi.org/10.1111/acfi.70051",
  },
  {
    id: "src_0h6k5hk",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "McBride and Rose",
    title: "Let's chat about ChatGPT: exploring accounting educators' perceptions of nascent generative AI",
    date: "Peer-reviewed; online 2026",
    jurisdiction: "United Kingdom, Ireland, South Africa, Australia, and New Zealand",
    access: "Publisher full text",
    note: "Educator reflections and focus groups add cross-jurisdiction evidence on assessment, pedagogy, integrity, and uncertainty during early GenAI adoption. The self-selected perceptions contain no student outcomes and reflect rapidly changing tools and policies.",
    href: "https://doi.org/10.1080/09639284.2026.2657407",
  },
  {
    id: "src_04s75ox",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Mökander, Schuett, Kirk, and Floridi",
    title: "Auditing large language models: a three-layered approach",
    date: "Peer-reviewed; 2024",
    jurisdiction: "General AI governance",
    access: "Open access",
    note: "A review and stakeholder-informed framework separates provider governance, model audits, and continuous application audits. It is a governance blueprint, not tested accounting assurance, and predates current tool-using agent architectures.",
    href: "https://doi.org/10.1007/s43681-023-00289-2",
  },
  {
    id: "src_1igc1rp",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Raji, Smart, White, Mitchell, Gebru, Hutchinson, Smith-Loud, Theron, and Barnes",
    title: "Closing the AI accountability gap: defining an end-to-end framework for internal algorithmic auditing",
    date: "Peer-reviewed conference paper; 2020",
    jurisdiction: "General algorithmic systems",
    access: "Open proceedings page and PDF",
    note: "A lifecycle framework defines audit stages, documentation artifacts, roles, and reporting from development through deployment. It predates LLMs and does not provide the independence, criteria, or opinion model of external financial-statement assurance.",
    href: "https://doi.org/10.1145/3351095.3372873",
  },
  {
    id: "src_17r8k3y",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Jonas Schuett",
    title: "Three lines of defense against risks from AI",
    date: "Peer-reviewed; 2025",
    jurisdiction: "General organizational AI governance",
    access: "Open access",
    note: "A conceptual application of the three-lines model assigns governing-body, first-line, second-line, and internal-audit responsibilities for AI risk. The paper is theoretical, centered on advanced-AI developers, and notes limited effectiveness evidence.",
    href: "https://doi.org/10.1007/s00146-023-01811-0",
  },
] as const;
