export const readingRoomSystemsResources = [
  {
    id: "src_aaif2026",
    topic: "Agent engineering",
    kind: "Technical reference",
    owner: "Agentic AI Foundation",
    title: "Agentic AI Foundation projects and working groups",
    date: "Living foundation site; reviewed Aug 2026",
    jurisdiction: "Open agent standards ecosystem",
    access: "Open",
    note: "The official foundation site separates hosted projects, focused working groups, governance, current material, and participation routes. It is useful for ecosystem orientation and information architecture; foundation participation or project hosting does not establish accounting suitability, security, or control effectiveness.",
    href: "https://aaif.io/",
  },
  {
    id: "src_agentsmd",
    topic: "Agent engineering",
    kind: "Technical reference",
    owner: "AGENTS.md project",
    title: "AGENTS.md open format for coding-agent instructions",
    date: "Living open format; reviewed Aug 2026",
    jurisdiction: "Open-source software projects",
    access: "Open site and repository",
    note: "Defines a predictable Markdown location for repository context, build steps, tests, conventions, and security notes used by coding agents. It is intentionally flexible rather than a typed runtime policy, so it does not grant production permissions or replace accounting-domain instructions, API contracts, or authorization controls.",
    href: "https://agents.md/",
  },
  {
    id: "src_0j5fy58",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Kapoor, Stroebl, Siegel, Nadgir, and Narayanan",
    title: "AI Agents That Matter",
    date: "Peer-reviewed; TMLR 2025",
    jurisdiction: "General agent evaluation",
    access: "Open paper, code, and project page",
    note: "Separates model evaluation from downstream agent evaluation and makes cost, holdouts, reproducibility, and shortcuts first-class concerns. Its demonstrations are not accounting workflows, so it supplies evaluation method rather than accounting evidence.",
    href: "https://openreview.net/forum?id=Zy4uFzMviZ",
  },
  {
    id: "src_03c2qkm",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Yao and collaborators",
    title: "τ-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains",
    date: "Peer-reviewed; ICLR 2025",
    jurisdiction: "Retail and airline simulations",
    access: "Open paper and code",
    note: "A stateful tool-use benchmark scores database state, policy adherence, and repeated-run consistency. Its domains and simulated users are cleaner than accounting work, but the state-and-policy pattern transfers well to controlled finance actions.",
    href: "https://proceedings.iclr.cc/paper_files/paper/2025/hash/1b126cc38b8638e07bef37e7b2bb72bf-Abstract-Conference.html",
  },
  {
    id: "src_023hddn",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Lu and collaborators",
    title: "ToolSandbox: A Stateful, Conversational, Interactive Evaluation Benchmark for LLM Tool Use Capabilities",
    date: "Peer-reviewed; Findings of NAACL 2025",
    jurisdiction: "Synthetic tool environment",
    access: "Open paper, data, and code",
    note: "Tests state dependencies, canonical tool arguments, multi-turn interaction, and recognition of insufficient information. The environment is synthetic and does not test ledger posting, close, or audit controls directly.",
    href: "https://aclanthology.org/2025.findings-naacl.65/",
  },
  {
    id: "src_18lep20",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Drouin and collaborators",
    title: "WorkArena: How Capable Are Web Agents at Solving Common Knowledge Work Tasks?",
    date: "Peer-reviewed; ICML 2024",
    jurisdiction: "Enterprise-software benchmark",
    access: "Open paper and code",
    note: "Benchmarks forms, lists, knowledge bases, dashboards, catalogs, and menus with state-based validation. ServiceNow is not an accounting system and mostly atomic task success does not establish financial correctness or control compliance.",
    href: "https://proceedings.mlr.press/v235/drouin24a.html",
  },
  {
    id: "src_0ztzbym",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Xu and collaborators",
    title: "TheAgentCompany: Benchmarking LLM Agents on Consequential Real World Tasks",
    date: "Peer-reviewed; NeurIPS 2025",
    jurisdiction: "Simulated software-company workplace",
    access: "Open paper, code, and environment",
    note: "Tests sustained work across web, code, office tools, communication, administration, and some finance tasks. The simulated small software company and benchmark-specific graders do not establish accounting deployment reliability.",
    href: "https://papers.nips.cc/paper_files/paper/2025/hash/0d744742f6fac4d1134c019b7cef3c8a-Abstract-Datasets_and_Benchmarks_Track.html",
  },
  {
    id: "src_0bztogd",
    topic: "Security and identity",
    kind: "Research paper",
    owner: "Debenedetti and collaborators",
    title: "AgentDojo: A Dynamic Environment to Evaluate Prompt Injection Attacks and Defenses for LLM Agents",
    date: "Peer-reviewed; NeurIPS 2024",
    jurisdiction: "General tool-using agents",
    access: "Open paper, supplemental material, and code",
    note: "A dynamic benchmark jointly tests task utility and security over untrusted tool content. Its simplified environments and evolving attacks mean that passing the benchmark is not proof that an accounting agent is secure.",
    href: "https://proceedings.neurips.cc/paper_files/paper/2024/hash/97091a5177d8dc64b1da8bf3e1f6fb54-Abstract-Datasets_and_Benchmarks_Track.html",
  },
  {
    id: "src_0tfuqlv",
    topic: "Security and identity",
    kind: "Research paper",
    owner: "Greshake and collaborators",
    title: "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
    date: "Peer-reviewed; ACM AISec 2023",
    jurisdiction: "General LLM-integrated applications",
    access: "DOI record; open author preprint available",
    note: "Seminal threat analysis shows how instructions embedded in retrieved data can influence tools and application behavior without direct attacker access. Early-system demonstrations establish the attack class, not current incidence or defense effectiveness in accounting.",
    href: "https://doi.org/10.1145/3605764.3623985",
  },
  {
    id: "src_18xd8ll",
    topic: "Security and identity",
    kind: "Research paper",
    owner: "Debenedetti and collaborators",
    title: "Defeating Prompt Injections by Design",
    date: "Preprint; revised Jun 2025",
    jurisdiction: "General tool-using agents",
    access: "Open paper and implementation",
    note: "CaMeL separates control flow from untrusted data and applies capability policies to tool calls. It remains a preprint evaluated mainly in AgentDojo; guarantees depend on correct policies, data-flow extraction, implementation, and threat-model assumptions.",
    href: "https://arxiv.org/abs/2503.18813",
  },
  {
    id: "src_06l7uy3",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Vaccaro, Almaatouq, and Malone",
    title: "When combinations of humans and AI are useful: A systematic review and meta-analysis",
    date: "Peer-reviewed; 2024",
    jurisdiction: "Cross-domain human–AI studies",
    access: "Open access",
    note: "A meta-analysis tests whether combined human–AI work outperforms people or AI alone rather than assuming complementarity. The underlying studies are heterogeneous and mostly pre-agentic, so accounting teams still need local comparison tests.",
    href: "https://www.nature.com/articles/s41562-024-02024-1",
  },
  {
    id: "src_05shm3i",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Parasuraman and Riley",
    title: "Humans and Automation: Use, Misuse, Disuse, Abuse",
    date: "Peer-reviewed synthesis; 1997",
    jurisdiction: "Cross-domain human factors",
    access: "Abstract open; article access varies",
    note: "Foundational vocabulary for overreliance, underuse, monitoring failure, false alarms, trust, and workload. It predates modern AI and draws heavily from safety-critical automation, so it is a design foundation rather than direct LLM-agent evidence.",
    href: "https://doi.org/10.1518/001872097778543886",
  },
  {
    id: "src_16fb52v",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Parasuraman, Sheridan, and Wickens",
    title: "A model for types and levels of human interaction with automation",
    date: "Peer-reviewed framework; 2000",
    jurisdiction: "Cross-domain human factors",
    access: "Abstract open; article access varies",
    note: "Distinguishes automation of information acquisition, analysis, decision selection, and action implementation at different autonomy levels. It supports granular authority design but is not an accounting-agent control standard.",
    href: "https://doi.org/10.1109/3468.844354",
  },
  {
    id: "src_092a1wl",
    topic: "Agent engineering",
    kind: "Rule or standard",
    owner: "World Wide Web Consortium",
    title: "PROV-O: The PROV Ontology",
    date: "W3C Recommendation; 2013",
    jurisdiction: "Open web standard",
    access: "Open standard, examples, and implementation report",
    note: "A vendor-neutral vocabulary for entities, activities, agents, derivation, attribution, plans, revisions, and primary sources. The ontology enables interoperable lineage but does not make records complete, truthful, immutable, or legally sufficient.",
    href: "https://www.w3.org/TR/prov-o/",
  },
  {
    id: "src_10wzswi",
    topic: "Security and identity",
    kind: "Research paper",
    owner: "Saltzer and Schroeder",
    title: "The Protection of Information in Computer Systems",
    date: "Peer-reviewed tutorial; 1975",
    jurisdiction: "General computer security",
    access: "DOI access varies; open author copy available",
    note: "Foundational principles include fail-safe defaults, complete mediation, separation of privilege, least privilege, and usable controls. The architecture predates probabilistic models and prompt injection but remains a stronger permission basis than model instructions alone.",
    href: "https://doi.org/10.1109/PROC.1975.9939",
  },
  {
    id: "src_1hgp2bd",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Staufer and collaborators",
    title: "The 2025 AI Agent Index: Documenting Technical and Safety Features of Deployed Agentic AI Systems",
    date: "Peer-reviewed; ACM FAccT 2026",
    jurisdiction: "Thirty deployed agent systems",
    access: "Open interactive index, methods, and data",
    note: "A structured study documents architecture, autonomy, ecosystem interaction, safety, evaluation, and transparency for deployed agents. It relies on public information and developer correspondence rather than independent testing and is a dated market snapshot.",
    href: "https://doi.org/10.1145/3805689.3806728",
  },
  {
    id: "src_0w2pi9z",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Brynjolfsson, Rock, and Syverson",
    title: "The Productivity J-Curve: How Intangibles Complement General Purpose Technologies",
    date: "Peer-reviewed; 2021",
    jurisdiction: "Macroeconomic and historical evidence",
    access: "Abstract open; open NBER version available",
    note: "Explains why process, software, business-model, and human-capital investments can delay visible productivity from a general-purpose technology. It is not a causal estimate for generative AI or a specific finance deployment.",
    href: "https://doi.org/10.1257/mac.20180386",
  },
  {
    id: "src_0v7x0m1",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Breck and collaborators",
    title: "The ML Test Score: A Rubric for ML Production Readiness and Technical Debt Reduction",
    date: "Peer-reviewed; IEEE Big Data 2017",
    jurisdiction: "Predictive-ML production systems",
    access: "Open author page and paper",
    note: "Twenty-eight tests cover data, models, infrastructure, serving, and production behavior. The rubric needs extensions for trajectories, tool side effects, approvals, prompt injection, cost, and evidence lineage before use with accounting agents.",
    href: "https://research.google/pubs/the-ml-test-score-a-rubric-for-ml-production-readiness-and-technical-debt-reduction/",
  },
  {
    id: "src_13huwb6",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Agrawal, Gans, and Goldfarb",
    title: "AI Adoption and System-Wide Change",
    date: "NBER working paper; 2021",
    jurisdiction: "General organizational adoption",
    access: "Open",
    note: "A formal model explains interacting tasks, modularity, coordination, and why task-level feasibility does not equal system-level adoption. It is theoretical and not an observed accounting implementation.",
    href: "https://www.nber.org/papers/w28811",
  },
  {
    id: "src_14lw1ez",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Barres and collaborators",
    title: "τ²-Bench: Evaluating Conversational Agents in a Dual-Control Environment",
    date: "Peer-reviewed; ICML 2026 oral",
    jurisdiction: "Simulated telecom workflows",
    access: "Open paper and code",
    note: "Extends tool-agent evaluation so the user and agent both act in a shared environment, matching workflows where humans supply evidence or authorize steps. The telecom domain and simulated user require accounting-specific replication.",
    href: "https://arxiv.org/abs/2506.07982",
  },
  {
    id: "src_10l42lc",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Cemri and collaborators",
    title: "Why Do Multi-Agent LLM Systems Fail?",
    date: "Preprint; revised 2025",
    jurisdiction: "General multi-agent frameworks",
    access: "Open paper and dataset",
    note: "An empirical taxonomy covers specification, inter-agent alignment, verification, and termination failures across multi-agent systems. It remains a preprint based on software, math, and general frameworks rather than accounting workflows.",
    href: "https://arxiv.org/abs/2503.13657",
  },
  {
    id: "src_1jal1ad",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Lisanne Bainbridge",
    title: "Ironies of Automation",
    date: "Peer-reviewed brief paper; 1983",
    jurisdiction: "Industrial process control",
    access: "DOI access varies; open IFAC copy available",
    note: "Explains why automating routine work can leave people responsible for rare, difficult cases while eroding the context and skill needed to intervene. The process-control setting is conceptual transfer, not LLM-agent evidence.",
    href: "https://doi.org/10.1016/0005-1098(83)90046-8",
  },
  {
    id: "src_0mz74m6",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Green and Chen",
    title: "The Principles and Limits of Algorithm-in-the-Loop Decision Making",
    date: "Peer-reviewed; 2019",
    jurisdiction: "Lending and pretrial decision experiments",
    access: "Abstract open; article access varies",
    note: "Controlled studies show why model evaluation alone is insufficient when people must interpret, calibrate, and act on algorithmic advice. The tasks and participants differ from accounting, so whole-workflow testing is the transferable lesson.",
    href: "https://doi.org/10.1145/3359152",
  },
  {
    id: "src_113zjrs",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Mosier and collaborators",
    title: "Automation Bias: Decision Making and Performance in High-Tech Cockpits",
    date: "Peer-reviewed; 1998",
    jurisdiction: "Aviation simulation",
    access: "Abstract open; article access varies",
    note: "Professional simulation evidence examines omission and commission errors and verification around automated cues. The aviation setting and small population make it a reviewer-design analogy, not accounting outcome evidence.",
    href: "https://doi.org/10.1207/s15327108ijap0801_3",
  },
  {
    id: "src_1ttzngc",
    topic: "Agent engineering",
    kind: "Research paper",
    owner: "Sculley and collaborators",
    title: "Hidden Technical Debt in Machine Learning Systems",
    date: "Peer-reviewed; NeurIPS 2015",
    jurisdiction: "Production ML systems",
    access: "Open",
    note: "A system-level account of data dependencies, feedback loops, undeclared consumers, configuration debt, and boundary erosion. It concerns predictive ML rather than LLM agents but transfers to finance systems spanning ERPs, spreadsheets, and workpapers.",
    href: "https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html",
  },
  {
    id: "src_07s1t5x",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Ribeiro, Wu, Guestrin, and Singh",
    title: "Beyond Accuracy: Behavioral Testing of NLP Models with CheckList",
    date: "Peer-reviewed; ACL 2020 Best Paper",
    jurisdiction: "NLP model testing",
    access: "Open paper and code",
    note: "Introduces capability-by-test matrices and invariance, directional, and minimum-functionality tests. It targets NLP classifiers rather than stateful agents, and accounting experts still must define valid behaviors and oracles.",
    href: "https://aclanthology.org/2020.acl-main.442/",
  },
  {
    id: "src_12dhkyt",
    topic: "Agent engineering",
    kind: "Thought piece",
    owner: "Rich Sutton",
    title: "The Bitter Lesson",
    date: "Independent research essay; 2019",
    jurisdiction: "General AI history",
    access: "Open",
    note: "An influential argument that general methods using computation, search, and learning tend to outlast hand-coded domain structure. It is not a universal law and should not be used to dismiss accounting standards, controls, or domain-specific evaluation.",
    href: "https://www.incompleteideas.net/IncIdeas/BitterLesson.html",
  },
] as const;
