export const readingRoomProfessionResources = [
  {
    id: "src_0a4kx0d",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Tax Practitioners Board, Australia",
    title: "TPB(GS) 55/2026: The use of Artificial Intelligence and the Code of Professional Conduct",
    date: "Final guidance; Jul 2026",
    jurisdiction: "Australia; registered tax practitioners",
    access: "Open HTML and PDF",
    note: "Maps AI, including autonomous functionality, to competence, reasonable care, confidentiality, recordkeeping, quality management, supervision, and judgment. It interprets existing Australian duties; governing law and engagement facts still control.",
    href: "https://www.tpb.gov.au/tpbgs-552026-use-artificial-intelligence-and-code-professional-conduct",
  },
  {
    id: "src_133sxln",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "CPA Ontario",
    title: "The Responsible Use of AI in Professional Practice",
    date: "Regulatory Standard; Jun 2026",
    jurisdiction: "Ontario CPAs",
    access: "Open HTML",
    note: "Applies Ontario CPA rules to understanding tools, verifying outputs, exercising judgment, protecting confidentiality, disclosure, and documenting due diligence. It is a provincial regulator interpretation, not a global standard or effectiveness study.",
    href: "https://www.cpaontario.ca/members/regulations-guidance/regulatory-publications/the-responsible-use-of-ai",
  },
  {
    id: "src_0n6voou",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Seven UK professional tax and accountancy bodies",
    title: "Professional Conduct in Relation to Taxation: topical guidance on the ethical use of artificial intelligence tools",
    date: "Topical guidance; Jan 2026",
    jurisdiction: "United Kingdom; members of participating bodies",
    access: "Open index and PDF",
    note: "Applies PCRT principles to integrity, accuracy, bias, due care, confidentiality, tool limitations, and safeguards. The AI document is implementation guidance; mandatory force arises from the bodies' underlying membership regimes, not tax law.",
    href: "https://www.att.org.uk/professional-standards/professional-conduct-relation-taxation",
  },
  {
    id: "src_0yyp4cb",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "HM Revenue & Customs",
    title: "Guidelines for using generative artificial intelligence if you're a software developer",
    date: "Guidance; Jan 2026",
    jurisdiction: "United Kingdom; software supporting HMRC submissions",
    access: "Open HTML",
    note: "Sets expectations for transparent AI use, reliable legal sources, version control, monitoring, human oversight, privacy, security, and ethical design in tax software. It is neither certification nor a replacement for law and filing specifications.",
    href: "https://www.gov.uk/guidance/guidelines-for-using-generative-artificial-intelligence-if-youre-a-software-developer",
  },
  {
    id: "src_09imui4",
    topic: "Audit and assurance",
    kind: "Official guidance",
    owner: "Accounting and Corporate Regulatory Authority, Singapore",
    title: "Audit Practice Guidance No. 1 of 2025: Delivering Quality Audits in a Technology-Driven Environment",
    date: "Practice guidance; Dec 2025",
    jurisdiction: "Singapore audit firms",
    access: "Open page and PDF",
    note: "Connects AI, analytics, and automation to quality management, risk assessment, monitoring, competence, and understanding audited entities' IT. It is Singapore-specific practice guidance, not an auditing standard or agent-outcome study.",
    href: "https://www.acra.gov.sg/news-events/news-announcements/906/",
  },
  {
    id: "src_1bu97ex",
    topic: "Audit and assurance",
    kind: "Official guidance",
    owner: "Netherlands Authority for the Financial Markets",
    title: "12 building blocks for safer use of advanced (GenAI) audit tools",
    date: "Supervisory good practice; Dec 2025",
    jurisdiction: "Netherlands; Dutch language",
    access: "Open HTML and PDF",
    note: "A regulator-developed model spans security foundations, data and analysis quality, controlled use, human responsibility, and traceability. It is nonbinding good practice and does not show that compliant tools improve audit quality.",
    href: "https://www.afm.nl/nl-nl/sector/actueel/2025/dec/pb-12-bouwstenen-beheerst-gebruik-audit-tooling",
  },
  {
    id: "src_0qw4qgy",
    topic: "Audit and assurance",
    kind: "Official guidance",
    owner: "Wirtschaftsprüferkammer",
    title: "Questions and answers on the use of artificial intelligence in auditing practice",
    date: "Current German revision; May 2026",
    jurisdiction: "Germany; audit practice",
    access: "Open German HTML and PDF; older English translation",
    note: "Professional-chamber Q&A addresses confidentiality, external service providers, responsibility, and acting as an AI representative. The German text is current; the English translation lags, and this is professional-law guidance rather than an audit standard.",
    href: "https://www.wpk.de/wissen/ki/",
  },
  {
    id: "src_1tcpuh2",
    topic: "Audit and assurance",
    kind: "Official guidance",
    owner: "Independent Regulatory Board for Auditors, South Africa",
    title: "Staff Audit Practice Alert 11: The Use of Generative Artificial Intelligence and Emerging Technologies in Audits",
    date: "Staff alert; Sep 2025",
    jurisdiction: "South Africa; audit engagements",
    access: "Open PDF from first-party index",
    note: "A regulator staff alert focuses on GenAI risks and auditor responsibilities. IRBA expressly states that staff alerts are not authoritative pronouncements and do not amend auditing standards or practice statements.",
    href: "https://irba.co.za/audit-practice-alerts/",
  },
  {
    id: "src_03h0e21",
    topic: "Law and policy",
    kind: "Rule or standard",
    owner: "US Internal Revenue Service",
    title: "IRM 10.24.1, IRS Policy for Artificial Intelligence Governance",
    date: "Revised and effective Aug 2026",
    jurisdiction: "United States; internally binding within IRS",
    access: "Open HTML",
    note: "IRS-wide policy covers inventories, high-impact AI, prohibited GenAI uses, records, privacy, security, taxpayer rights, monitoring, and termination. It binds IRS personnel and vendors, not taxpayers or private accounting firms, and does not establish model outcomes.",
    href: "https://www.irs.gov/irm/part10/irm_10-024-001r",
  },
  {
    id: "src_179f1cz",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "UK National Audit Office",
    title: "Good practice guide for organisations using AI",
    date: "Good-practice guide; May 2026",
    jurisdiction: "United Kingdom public sector",
    access: "Open HTML and PDF",
    note: "Questions for audit and risk committees span AI planning, deployment, scaling, governance, data, people, and benefits. It is public-sector good practice, not a formal standard or evidence that the listed controls are sufficient.",
    href: "https://www.nao.org.uk/insights/good-practice-guide-for-organisations-using-ai/",
  },
  {
    id: "src_1klaq4c",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "International Monetary Fund",
    title: "Understanding Artificial Intelligence in Tax and Customs Administration",
    date: "Technical Notes and Manuals; Nov 2024",
    jurisdiction: "International tax and customs administration",
    access: "Open HTML, PDF, and ePub",
    note: "A primer for revenue officials covers use cases, legal and ethical constraints, strategy, a sample policy, and risk assessment. It is cross-country implementation guidance, not field evaluation; local law, data, capacity, and taxpayer rights differ.",
    href: "https://www.imf.org/en/publications/tnm/issues/2024/11/21/understanding-artificial-intelligence-in-tax-and-customs-administration-555097",
  },
  {
    id: "src_0cn4sq6",
    topic: "Accounting and reporting",
    kind: "Evidence",
    owner: "UK Financial Reporting Council, Lancaster University, and Loughborough University",
    title: "The use of Artificial Intelligence Technologies in Corporate Reporting",
    date: "Mixed-method research; Jul 2026",
    jurisdiction: "United Kingdom corporate reporting",
    access: "Open report, survey instrument, and tables",
    note: "Thirty-nine interviews and 103 survey responses cover GenAI reporting tasks, governance, oversight, and barriers. The small non-probability sample reports adoption and perceptions, not output accuracy, productivity, or causal effects.",
    href: "https://www.frc.org.uk/library/research-and-insights/the-use-of-artificial-intelligence-technologies-in-corporate-reporting/",
  },
  {
    id: "src_1ayxpgh",
    topic: "Audit and assurance",
    kind: "Evidence",
    owner: "UK Financial Reporting Council",
    title: "Thematic Review: Certification of Automated Tools and Techniques",
    date: "Thematic review; Jun 2025",
    jurisdiction: "Six largest United Kingdom audit firms",
    access: "Open PDF",
    note: "Regulator observations cover lifecycle certification, testing, training, monitoring, and vendor controls for automated tools. The review is neither exhaustive nor evidence that certification caused better audit outcomes, and it covers more than AI.",
    href: "https://www.frc.org.uk/documents/8383/Thematic_Review_on_the_Certification_of_Automated_Tools_and_Techniques.pdf",
  },
  {
    id: "src_04sc6cz",
    topic: "Accounting and reporting",
    kind: "Evidence",
    owner: "UK Financial Reporting Council",
    title: "Structured Digital Reporting: Insights 2025/26",
    date: "Regulator review; May 2026",
    jurisdiction: "United Kingdom listed-company reporting",
    access: "Open HTML, PDF, and tables",
    note: "A targeted filing review and market-wide analysis cover tagging meaning, extensions, anchoring, scaling, and accessibility for machine reuse. It is not an AI-model evaluation, and structured data alone does not make an agent reliable.",
    href: "https://www.frc.org.uk/library/digital-reporting/structured-digital-reporting-insights-202526/",
  },
  {
    id: "src_0w8mvx4",
    topic: "Controls and governance",
    kind: "Evidence",
    owner: "US Government Accountability Office",
    title: "Artificial Intelligence: IRS Actions Needed to Address Skills Gaps, Information Quality, and Strategic Management",
    date: "Independent public audit; Mar 2026",
    jurisdiction: "United States Internal Revenue Service",
    access: "Open HTML and PDF",
    note: "GAO evaluates IRS use-case inventories, workforce skills, information quality, strategy, and corrective actions. The point-in-time review does not test the accuracy, fairness, or tax outcomes of every use case, and sensitive uses are not fully visible.",
    href: "https://www.gao.gov/products/gao-26-107522",
  },
  {
    id: "src_1ubjvso",
    topic: "Evaluation and evidence",
    kind: "Evidence",
    owner: "ICAS",
    title: "Shaping the Profession: Generative AI and professional judgement in accounting",
    date: "Field study; Mar 2026",
    jurisdiction: "One mid-tier United Kingdom accounting firm",
    access: "Open report, interactive material, and case studies",
    note: "A year-long study uses surveys, interviews, skills activities, and cases to separate perceived task speed from end-to-end throughput and examine judgment and learning. One firm and self-report limit causal productivity claims.",
    href: "https://www.icas.com/news-insights-events/documents/shaping-the-profession-generative-ai-and-professional-judgement-in-accounting-2026",
  },
  {
    id: "src_0qnpuy0",
    topic: "Accounting and reporting",
    kind: "Evidence",
    owner: "ACCA and Chartered Accountants Australia and New Zealand",
    title: "Enabling finance insight: Bridging skills and data gaps for AI-enabled finance",
    date: "Global study; Jul 2026",
    jurisdiction: "Global finance profession",
    access: "Open page and report",
    note: "A survey of 1,600 finance professionals plus roundtables and interviews covers data quality, GenAI skills, governance, verifiability, and ROI barriers. It measures self-reported experience, not output accuracy, control effectiveness, or realized return.",
    href: "https://www.accaglobal.com/gb/en/professional-insights/technology/enabling-finance-insight.html",
  },
  {
    id: "src_0rz6w00",
    topic: "Audit and assurance",
    kind: "Technical reference",
    owner: "Japanese Institute of Certified Public Accountants",
    title: "Technology Committee Research Report No. 11: The Study into the Use of AI in Audits",
    date: "Japanese report 2024; English translation Apr 2025",
    jurisdiction: "Japan; audit profession",
    access: "Open first-party page and PDF",
    note: "Profession research describes audit use cases, challenges, and implications for CPA roles, adding a Japan-specific perspective. It is neither a standard nor regulator inspection and predates much of the agentic wave.",
    href: "https://jicpa.or.jp/english/news/2025/20250417afu.html",
  },
  {
    id: "src_0aksrfb",
    topic: "Practice examples",
    kind: "Evidence",
    owner: "Autorité des marchés financiers, France",
    title: "AI and supervision: insights from experiments on automated processing of regulatory reporting",
    date: "Regulator experiment report; Mar 2025",
    jurisdiction: "France; securities supervision",
    access: "Open English HTML and report",
    note: "AMF describes experiments using information extraction and AI on regulatory reporting, relevant to document-to-data workflows and traceability. It is a regulator self-account of experimental supervisory work, not production outcome evidence.",
    href: "https://www.amf-france.org/en/news-publications/publications/reports-research-and-analysis/ai-and-supervision-insights-learned-amf-experiments-possibility-automated-processing-regulatory",
  },
  {
    id: "src_0p9wfhe",
    topic: "Audit and assurance",
    kind: "Official guidance",
    owner: "UK National Audit Office and five partner supreme audit institutions",
    title: "AI auditing tool",
    date: "Good-practice tool; Feb 2026",
    jurisdiction: "International public-sector audit",
    access: "Open HTML and companion tools",
    note: "A cross-audit-office lifecycle catalogue covers governance, data, model development, predeployment evaluation, change, and monitoring. It is public-sector AI assurance guidance, not a financial-statement auditing standard.",
    href: "https://www.nao.org.uk/insights/ai-auditing-tool/",
  },
  {
    id: "src_1gp1ika",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "International Monetary Fund",
    title: "Harnessing Emerging Digital Technologies toward a New Frontier of Public Financial Management",
    date: "Technical Notes and Manuals; Apr 2026",
    jurisdiction: "International public financial management",
    access: "Open HTML, PDF, and ePub",
    note: "An objective-driven guide connects AI and other technologies to budgeting, treasury, accounting, and reporting. It is broad implementation guidance rather than causal field evidence, and government readiness varies substantially.",
    href: "https://www.imf.org/en/publications/tnm/issues/2026/04/07/harnessing-emerging-digital-technologies-toward-a-new-frontier-of-public-financial-574910",
  },
  {
    id: "src_12f6y8x",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "New Zealand Inland Revenue",
    title: "Inland Revenue's use of artificial intelligence — information release",
    date: "Information release; Mar 2026",
    jurisdiction: "New Zealand tax administration",
    access: "Open HTML and PDF",
    note: "Released internal papers document agency AI use and governance, including human oversight and Algorithm Charter commitments. This is selected and potentially redacted agency self-disclosure, not independent assurance or private-practice guidance.",
    href: "https://www.taxpolicy.ird.govt.nz/publications/2026/ir-use-of-ai",
  },
  {
    id: "src_03uuh5o",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Agencia Tributaria, Spain",
    title: "Questions about Artificial Intelligence in the Tax Agency",
    date: "Operating position; updated Dec 2025",
    jurisdiction: "Spain; Spanish language",
    access: "Open HTML and PDF",
    note: "The agency distinguishes deterministic automation from AI and describes human involvement, data quality, bias, security, transparency, and current limits on determinative AI. It is a changeable self-description, not independent assurance.",
    href: "https://sede.agenciatributaria.gob.es/Sede/gobierno-abierto/transparencia/informacion-institucional-organizativa-planificacion/inteligencia-artificial.html",
  },
  {
    id: "src_0vnrcf0",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Canada Revenue Agency",
    title: "2026–27 Departmental Plan",
    date: "Departmental plan; 2026–27",
    jurisdiction: "Canada tax administration",
    access: "Open HTML",
    note: "An official plan reports AI project activity and describes GenAI chatbots, governance, training, automation, and workforce initiatives. It is a forward plan and agency self-report; project maturity and realized outcomes are unclear.",
    href: "https://www.canada.ca/en/revenue-agency/corporate/about-canada-revenue-agency-cra/departmental-plan/2026-27-cra-departmental-plan.html",
  },
  {
    id: "src_00voro6",
    topic: "Evaluation and evidence",
    kind: "Official guidance",
    owner: "Accounting and Corporate Regulatory Authority, Singapore",
    title: "Refreshed Skills Framework for Accountancy",
    date: "Workforce framework; May 2026",
    jurisdiction: "Singapore accountancy profession",
    access: "Open page and linked framework",
    note: "The framework embeds AI competencies across 44 accountancy roles and 11 career tracks. It is curriculum and role design, not evidence of adoption, learning, performance, or transfer to other labor markets.",
    href: "https://www.acra.gov.sg/news-events/news-announcements/acra-launches-refreshed-skills-framework-for-accountancy/",
  },
  {
    id: "src_0ygxsr4",
    topic: "Audit and assurance",
    kind: "Evidence",
    owner: "International Auditing and Assurance Standards Board",
    title: "Technology Quality Management Roundtables: Outcomes and Next Steps",
    date: "Consultation outcomes; Feb 2026",
    jurisdiction: "International audit quality management",
    access: "Open HTML and PDF",
    note: "Summarizes input from more than 240 stakeholders on six continents about technology and AI in firms' quality-management systems. Consultation feedback is not a representative survey, inspection report, standard, or effectiveness study.",
    href: "https://www.iaasb.org/publications/technology-quality-management-roundtables-outcomes-and-next-steps",
  },
  {
    id: "src_05rfnyc",
    topic: "Evaluation and evidence",
    kind: "Evidence",
    owner: "CPA Australia",
    title: "Business Technology Report 2025",
    date: "Profession survey; 2025",
    jurisdiction: "Nine Asia-Pacific markets",
    access: "Open PDF from research index",
    note: "A survey of 1,117 accounting and finance respondents covers AI adoption, integration, hiring, skills, cyber risk, data, and business technology. Cross-sectional self-report and profit associations do not establish causal effects.",
    href: "https://www.cpaaustralia.com.au/tools-and-resources/digital-and-ai/research-reports",
  },
  {
    id: "src_0w0lkv7",
    topic: "Audit and assurance",
    kind: "Evidence",
    owner: "Internal Audit Foundation and The Institute of Internal Auditors with AuditBoard",
    title: "Internal Audit and AI-Enabled Fraud",
    date: "Profession survey; Feb 2026",
    jurisdiction: "North American internal audit",
    access: "Public report page; download conditions vary",
    note: "A survey of 373 senior internal-audit leaders covers AI-enabled fraud risk, readiness, and internal-audit use. Vendor partnership, regional selection, and self-report mean preparedness perceptions are not fraud-detection performance.",
    href: "https://www.theiia.org/en/content/research/foundation/2026/internal-audit-and-ai-enabled-fraud/",
  },
  {
    id: "src_16glm4r",
    topic: "Audit and assurance",
    kind: "Evidence",
    owner: "ICAEW",
    title: "Analytics in external audit: current practice and trends",
    date: "Profession field research; Jul 2026",
    jurisdiction: "United Kingdom external audit",
    access: "Open page and report",
    note: "A qualitative practice study covers audit platforms, analytics, data quality, methodology, skills, regulation, and barriers. It is broader than agentic AI and documents perspectives rather than causal audit-quality outcomes.",
    href: "https://www.icaew.com/technical/technology/data/data-analytics-articles/analytics-in-external-audit-current-practice-and-trends",
  },
  {
    id: "src_01qcdrn",
    topic: "Controls and governance",
    kind: "Thought piece",
    owner: "Financial Executives International, Committee on Corporate Reporting",
    title: "AI Framework: Internal Control Over Financial Reporting",
    date: "Practitioner framework; Jun 2026",
    jurisdiction: "United States SOX and ICFR context",
    access: "Public overview; full framework paid",
    note: "A preparer-built framework covers scoping, outcome validation, human review, testing, multi-model validation, drift, bias, and outliers. It is not regulator authority or outcome evidence, and the full paywall limits use as a primary reading.",
    href: "https://daily.financialexecutives.org/About-FEI/For-the-Press/2026/fei-ccr-ai-framework-internal-control-financial.aspx",
  },
  {
    id: "src_0wzrm6k",
    topic: "Controls and governance",
    kind: "Thought piece",
    owner: "ACCA and EY",
    title: "AI assessments: enhancing confidence in the use of AI",
    date: "Thought leadership; 2025",
    jurisdiction: "Global AI assessment policy",
    access: "Open page and report",
    note: "A taxonomy distinguishes governance, conformity, and performance assessments and proposes policy measures. It is co-produced profession and audit-firm thought leadership, not a standard, inspection finding, or outcome study.",
    href: "https://www.accaglobal.com/in/en/professional-insights/technology/ai-assessments.html",
  },
  {
    id: "src_0j5ntza",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "European Federation of Accountants and Auditors for SMEs",
    title: "AI in Accounting I: A Short Guide to Privacy, Security, and Best Practices",
    date: "Professional guide; May 2025",
    jurisdiction: "European Union; small and medium practices",
    access: "Open guide and translations",
    note: "Accessible guidance covers privacy, security, and responsible AI use for smaller practices. It is high-level professional guidance, not law, legal advice, or empirical evidence; national and product-specific requirements still need verification.",
    href: "https://efaa.com/ai-in-accounting-a-short-guide-to-privacy-security-and-best-practices/",
  },
  {
    id: "src_0h0x1hw",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "European Federation of Accountants and Auditors for SMEs",
    title: "AI in Accounting II: Short Overview of Regulatory and Legal Implications",
    date: "Professional guide; updated Apr 2026",
    jurisdiction: "European Union; small and medium practices",
    access: "Open guide and translations",
    note: "A companion overview introduces EU legal and regulatory implications for smaller accounting practices. It is not legal advice or a substitute for current national implementation and product-specific analysis.",
    href: "https://efaa.com/ai-in-accounting-ii-short-overview-of-regulatory-and-legal-implications/",
  },
  {
    id: "src_0cip0z9",
    topic: "Practice examples",
    kind: "Official guidance",
    owner: "Consiglio Nazionale dei Dottori Commercialisti e degli Esperti Contabili",
    title: "Operational guide to artificial intelligence #3: The intelligent helper for the accountant",
    date: "Professional guide; Oct 2025",
    jurisdiction: "Italy; Italian language",
    access: "Open publication page and document",
    note: "National professional-body guidance adds a practical small-firm perspective for Italian accountants. It is not a regulator rule, independent evidence, or a tested implementation, and the publication metadata is limited.",
    href: "https://commercialisti.it/documenti-studio/guida-operativa-di-intelligenza-artificiale-3-laiuto-intelligente-al-commercialista/",
  },
  {
    id: "src_1v28wbc",
    topic: "Practice examples",
    kind: "Thought piece",
    owner: "Accountancy Europe",
    title: "5 ways professional accountancy organisations support the technological transformation of auditing",
    date: "Thought leadership; Feb 2024",
    jurisdiction: "European professional accountancy organizations",
    access: "Open page and publication",
    note: "Examples show how professional organizations can support training, tools, standards engagement, and institutional adoption. The material predates the current agent wave and describes initiatives rather than evaluated outcomes.",
    href: "https://accountancyeurope.eu/publications/5-ways-professional-accountancy-organisations-support-the-technological-transformation-of-auditing/",
  },
  {
    id: "src_0a038hj",
    topic: "Law and policy",
    kind: "Thought piece",
    owner: "Inter-American Center of Tax Administrations",
    title: "From Conversational Agents to Tax Assistants: A roadmap towards simpler, traceable and accessible tax compliance",
    date: "Independent institutional blog essay; Oct 2025",
    jurisdiction: "International tax administration",
    access: "Open English HTML",
    note: "A tax-agent roadmap discusses traceability, accessibility, and progression from chat interfaces to bounded assistants. It is an authored CIATBlog opinion, not an institutional standard, survey, or deployment evaluation.",
    href: "https://www.ciat.org/from-conversational-agents-to-tax-assistants-a-roadmap-towards-simpler-traceable-and-accessible-tax-compliance/?lang=en",
  },
  {
    id: "src_0mfdgla",
    topic: "Law and policy",
    kind: "Technical reference",
    owner: "Inter-American Development Bank",
    title: "Revolucionando la tributación: la administración tributaria 3.0 ya está aquí",
    date: "Technical note; Oct 2024",
    jurisdiction: "Latin America and Caribbean; Spanish language",
    access: "Open",
    note: "A regional technical note covers data-driven tax administration, e-invoicing, AI, automation, and governance. It is broad Spanish-language synthesis rather than an independent field evaluation of one system.",
    href: "https://publications.iadb.org/es/revolucionando-la-tributacion-la-administracion-tributaria-30-ya-esta-aqui",
  },
  {
    id: "src_0l1dez7",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "World Bank Centre for Financial Reporting Reform",
    title: "Leveraging Artificial Intelligence in Public Financial Management",
    date: "Training material; Mar 2025",
    jurisdiction: "International public financial management; multilingual",
    access: "Open presentation materials",
    note: "Training material connects AI to public financial management and is available in several languages. It is a slide deck rather than a formal report, standard, or evaluated deployment.",
    href: "https://cfrr.worldbank.org/node/5096",
  },
  {
    id: "src_0yh2b67",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "European Court of Auditors",
    title: "AI Strategy 2026–2030",
    date: "Institutional strategy; 2026–2030",
    jurisdiction: "European Union public-sector audit",
    access: "Open page and PDF",
    note: "An institutional strategy addresses AI use in audit work and capacity to audit AI systems. It is future-facing organizational intent, not an audit method or evidence that planned capabilities are effective.",
    href: "https://eca.europa.eu/en/strategy",
  },
  {
    id: "src_0yr7hbr",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "HM Revenue & Customs",
    title: "Strengthening standards for software that integrates with HMRC",
    date: "Implementation plan; Mar 2026",
    jurisdiction: "United Kingdom tax software",
    access: "Open HTML",
    note: "A proposed direction covers product integrity, correct outcomes, data accountability, error handling, and prevention of fraud and misuse. Detailed standards remain under development during 2026–27, so the record is not final technical requirements.",
    href: "https://www.gov.uk/government/publications/hmrcs-plan-to-strengthen-standards-for-third-party-software/strengthening-standards-for-software-that-integrates-with-hmrc",
  },
] as const;
