export const readingRoomExpansionResources = [
  {
    id: "src_occ26mrm",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Office of the Comptroller of the Currency, Federal Reserve Board, and Federal Deposit Insurance Corporation",
    title: "Model Risk Management: Revised Guidance",
    date: "Interagency guidance; Apr 2026",
    jurisdiction: "United States banking organizations",
    access: "Open HTML and PDF",
    note: "Updates risk-based model development, testing, validation, monitoring, governance, and third-party expectations. The agencies expressly exclude generative and agentic AI from this guidance's model definition, so use it as a boundary reference rather than AI-specific authority.",
    href: "https://www.occ.gov/news-issuances/bulletins/2026/bulletin-2026-13.html",
  },
  {
    id: "src_osfi26agent",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Office of the Superintendent of Financial Institutions Canada",
    title: "Generative and Agentic Artificial Intelligence: Implications for Technology, Cyber Security, and Operational Resilience",
    date: "Technology risk bulletin; Jul 2026",
    jurisdiction: "Canada; federally regulated financial institutions",
    access: "Open HTML",
    note: "Directly addresses limits on autonomy, AI harnessing, human oversight, data provenance, auditability, third-party dependencies, and downstream actions. It is supervisory guidance for Canadian financial institutions, not an accounting standard.",
    href: "https://www.osfi-bsif.gc.ca/en/risks/technology-cyber-risk-management/technology-risk-bulletin/generative-agentic-artificial-intelligence-implications-technology-cyber-security-operational",
  },
  {
    id: "src_iosco26ai",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "International Organization of Securities Commissions",
    title: "Supervisory Toolkit for AI Use in Capital Markets",
    date: "Final report; May 2026",
    jurisdiction: "Global capital-markets supervisors",
    access: "Open PDF",
    note: "A lifecycle-oriented supervisory toolkit covering governance, outsourcing, disclosure, recordkeeping, and monitoring, including generative and agentic AI. It is non-binding and designed for supervisors rather than operating teams.",
    href: "https://www.iosco.org/library/pubdocs/pdf/IOSCOPD823.pdf",
  },
  {
    id: "src_fsb26ai",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Financial Stability Board",
    title: "Sound Practices for Responsible Adoption of Artificial Intelligence",
    date: "Consultation report; Jun 2026",
    jurisdiction: "Global financial institutions",
    access: "Open HTML and PDF",
    note: "Proposes twelve practices across enterprise governance and the AI lifecycle, with implementation case studies. The consultation closed in July 2026; treat it as proposed guidance until a final report replaces it.",
    href: "https://www.fsb.org/2026/06/sound-practices-for-responsible-adoption-of-artificial-intelligence-ai-consultation-report/",
  },
  {
    id: "src_bafin26ai",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "German Federal Financial Supervisory Authority",
    title: "Guidance on ICT Risks in the Use of AI at Financial Entities",
    date: "Non-mandatory guidance; Jan 2026",
    jurisdiction: "Germany and EU-regulated financial entities",
    access: "Open PDF",
    note: "Connects AI use to DORA-oriented ICT risk, change control, data, security, operations, and third-party management. It is supervisory orientation, not a substitute for the governing EU and German requirements.",
    href: "https://www.bafin.de/SharedDocs/Downloads/EN/Anlage/dl_Anlage_orientierungshilfe_IKT_Risiken_bei_KI_en.pdf?__blob=publicationFile&v=1",
  },
  {
    id: "src_finra2409",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Financial Industry Regulatory Authority",
    title: "Regulatory Notice 24-09: Regulatory Obligations When Using Generative AI and Large Language Models",
    date: "Regulatory notice; Jun 2024",
    jurisdiction: "United States broker-dealers",
    access: "Open HTML and PDF",
    note: "Explains that technology-neutral supervision, communications, recordkeeping, privacy, and model-risk obligations continue to apply to GenAI use. Applicability depends on the firm's use case and FINRA rules.",
    href: "https://www.finra.org/rules-guidance/notices/24-09",
  },
  {
    id: "src_finra25uses",
    topic: "Practice examples",
    kind: "Evidence",
    owner: "Financial Industry Regulatory Authority",
    title: "How FINRA Member Firms Use GenAI",
    date: "Observed-use portfolio; Jul 2025",
    jurisdiction: "United States broker-dealers",
    access: "Open PDF",
    note: "A regulator-observed taxonomy spanning workflow automation, classification, data transformation, retrieval, drafting, simulation, and pattern recognition. It reports common use categories, not prevalence, effectiveness, or approval.",
    href: "https://www.finra.org/sites/default/files/2025-07/How-Member-Firms-Use-GenAI.pdf",
  },
  {
    id: "src_finma24ai",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Swiss Financial Market Supervisory Authority",
    title: "FINMA Guidance 08/2024: Governance and Risk Management When Using Artificial Intelligence",
    date: "Supervisory guidance; Dec 2024",
    jurisdiction: "Switzerland; supervised financial institutions",
    access: "Open PDF",
    note: "Reports supervisory observations on inventories, risk classification, data quality, testing, monitoring, documentation, explainability, and independent review. It applies technology-neutral Swiss requirements rather than creating AI-specific law.",
    href: "https://www.finma.ch/en/~/media/finma/dokumente/dokumentencenter/myfinma/4dokumentation/finma-aufsichtsmitteilungen/20241218-finma-aufsichtsmitteilung-08-2024.pdf",
  },
  {
    id: "src_apra26ai",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Australian Prudential Regulation Authority",
    title: "Letter to Industry on Artificial Intelligence",
    date: "Supervisory observations; Apr 2026",
    jurisdiction: "Australia; banks, insurers, and superannuation trustees",
    access: "Open HTML and attachment",
    note: "Finds governance, assurance, literacy, and operational resilience lagging adoption and calls for stronger board challenge and third-party oversight. Observations came from selected large entities and are not population estimates.",
    href: "https://www.apra.gov.au/news-and-publications/apra-letter-industry-artificial-intelligence-ai",
  },
  {
    id: "src_sfc24genai",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Securities and Futures Commission of Hong Kong",
    title: "Circular to Licensed Corporations: Use of Generative AI Language Models",
    date: "Supervisory circular; Nov 2024",
    jurisdiction: "Hong Kong licensed corporations",
    access: "Open HTML",
    note: "Sets risk-based expectations for governance, testing, monitoring, human review, data protection, third parties, and high-risk client-facing uses. Its mandatory effect is limited to the stated regulated scope.",
    href: "https://apps.sfc.hk/edistributionWeb/gateway/EN/circular/doc?refNo=24EC55",
  },
  {
    id: "src_boe24aisurvey",
    topic: "Evaluation and evidence",
    kind: "Evidence",
    owner: "Bank of England and Financial Conduct Authority",
    title: "Artificial Intelligence in UK Financial Services — 2024",
    date: "Joint survey; Nov 2024",
    jurisdiction: "United Kingdom financial services",
    access: "Open HTML and workbook",
    note: "Reports adoption, autonomy, materiality, third-party concentration, governance, and risk perceptions across regulated firms. The results are self-reported and describe financial services broadly rather than accounting agents specifically.",
    href: "https://www.bankofengland.co.uk/report/2024/artificial-intelligence-in-uk-financial-services-2024",
  },
  {
    id: "src_boe22aippf",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "Bank of England and Financial Conduct Authority AI Public-Private Forum",
    title: "The AI Public-Private Forum: Final Report",
    date: "Expert forum report; Feb 2022",
    jurisdiction: "United Kingdom financial services",
    access: "Open HTML and PDF",
    note: "Organizes deployment issues around data, model risk, and governance with practitioner examples. Outputs reflect forum participants' views, not formal Bank of England or FCA policy, and predate current agent architectures.",
    href: "https://www.bankofengland.co.uk/research/fintech/ai-public-private-forum",
  },
  {
    id: "src_pra23mrm",
    topic: "Controls and governance",
    kind: "Rule or standard",
    owner: "Bank of England Prudential Regulation Authority",
    title: "SS1/23, Model Risk Management Principles for Banks",
    date: "Supervisory statement; May 2023",
    jurisdiction: "United Kingdom banks within stated scope",
    access: "Open policy statement and PDF",
    note: "Sets five principles for model identification, governance, development, validation, and risk mitigation, including AI and machine learning where they meet the model scope. Check current scope and later amendments before relying on it.",
    href: "https://www.bankofengland.co.uk/prudential-regulation/publication/2023/may/model-risk-management-principles-for-banks",
  },
  {
    id: "src_bis24regai",
    topic: "Law and policy",
    kind: "Technical reference",
    owner: "Bank for International Settlements Financial Stability Institute",
    title: "Regulating AI in the Financial Sector: Recent Developments and Main Challenges",
    date: "FSI Insights No. 63; Dec 2024",
    jurisdiction: "International financial regulation",
    access: "Open PDF",
    note: "Compares emerging policy approaches and implementation challenges across governance, explainability, third parties, data, and resilience. The analysis is authored by FSI staff and does not itself create supervisory requirements.",
    href: "https://www.bis.org/fsi/publ/insights63.pdf",
  },
  {
    id: "src_bis26dataai",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "Bank for International Settlements Financial Stability Institute",
    title: "In Data We Trust? Emerging Policy and Supervisory Approaches to AI Data Use in Financial Services",
    date: "FSI Insights No. 73; Mar 2026",
    jurisdiction: "International financial regulation",
    access: "Open HTML and PDF",
    note: "Examines privacy, quality, security, synthetic data, third-party dependence, and supervisory expectations for AI data. It is a comparative policy study, not a control certification method.",
    href: "https://www.bis.org/fsi/publ/insights73.htm",
  },
  {
    id: "src_bis25xai",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "Bank for International Settlements Financial Stability Institute",
    title: "Managing Explanations: How Regulators Can Address AI Explainability",
    date: "FSI Occasional Paper No. 24; Sep 2025",
    jurisdiction: "International financial regulation",
    access: "Open HTML and PDF",
    note: "Explains limitations and tradeoffs in model explanations and links them to governance, validation, monitoring, and independent review. It cautions that explanation techniques can be unstable or misleading.",
    href: "https://www.bis.org/fsi/fsipapers24.htm",
  },
  {
    id: "src_bis25cashagents",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Bank for International Settlements and Bank of Canada researchers",
    title: "AI Agents for Cash Management in Payment Systems",
    date: "BIS Working Paper No. 1310; Nov 2025",
    jurisdiction: "Simulated wholesale payment-system liquidity management",
    access: "Open PDF",
    note: "Tests prompt-based agent recommendations under liquidity shocks and competing priorities. The simulation does not establish safe autonomous operation, and the authors call for regulatory and policy safeguards.",
    href: "https://www.bis.org/publ/work1310.pdf",
  },
  {
    id: "src_bis25aigov",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "Bank for International Settlements Consultative Group on Risk Management",
    title: "Governance of AI Adoption in Central Banks",
    date: "Risk-management report; Jan 2025",
    jurisdiction: "Central banks; international",
    access: "Open HTML and PDF",
    note: "Proposes an adaptive governance framework and ten practical actions using three-lines structures, portfolios, inventories, and lifecycle risk management. Central-bank mandates and data sensitivity limit direct transfer to corporate finance.",
    href: "https://www.bis.org/publ/othp90.htm",
  },
  {
    id: "src_fsb24ai",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Financial Stability Board",
    title: "The Financial Stability Implications of Artificial Intelligence",
    date: "Final report; Nov 2024",
    jurisdiction: "Global financial system",
    access: "Open HTML and PDF",
    note: "Identifies third-party concentration, correlated behavior, cyber risk, model risk, data quality, governance, fraud, and disinformation as potential systemic vulnerabilities. It is macroprudential analysis, not entity-level control criteria.",
    href: "https://www.fsb.org/2024/11/the-financial-stability-implications-of-artificial-intelligence/",
  },
  {
    id: "src_fsb25monitor",
    topic: "Evaluation and evidence",
    kind: "Official guidance",
    owner: "Financial Stability Board",
    title: "Monitoring Adoption of Artificial Intelligence and Related Vulnerabilities in the Financial Sector",
    date: "Final report; Oct 2025",
    jurisdiction: "Global financial authorities",
    access: "Open HTML and PDF",
    note: "Offers indicators and jurisdiction examples for monitoring adoption and vulnerabilities, including third-party concentration. It supports system-level surveillance rather than testing one accounting workflow.",
    href: "https://www.fsb.org/2025/10/monitoring-adoption-of-artificial-intelligence-and-related-vulnerabilities-in-the-financial-sector/",
  },
  {
    id: "src_xbrlvalid",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL International",
    title: "XBRL Validation",
    date: "Living technical guidance",
    jurisdiction: "Global digital reporting",
    access: "Open HTML",
    note: "Explains layered automated checks from data types through calculations and business rules. Validation flags require review; passing them does not establish accounting correctness or audit assurance.",
    href: "https://www.xbrl.org/the-standard/what/key-concepts-in-xbrl/validation/",
  },
  {
    id: "src_ixbrl",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL International",
    title: "Inline XBRL",
    date: "Living technical overview",
    jurisdiction: "Global digital reporting",
    access: "Open HTML",
    note: "Describes the open format that combines human-readable reports with structured machine-readable facts. Taxonomy selection, extensions, filing rules, and data quality remain jurisdiction-specific.",
    href: "https://www.xbrl.org/the-standard/what/ixbrl/",
  },
  {
    id: "src_xbrlformula",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL International",
    title: "XBRL Formula Rules Tutorial",
    date: "Public draft; living guidance",
    jurisdiction: "Global digital reporting",
    access: "Open HTML",
    note: "Shows how domain rules can be published as executable taxonomy validation constraints. The tutorial is a public draft and does not replace the normative Formula specifications or filing-system rules.",
    href: "https://www.xbrl.org/guidance/xbrl-formula-rules-tutorial/",
  },
  {
    id: "src_xbrlgl",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL International",
    title: "XBRL Global Ledger Taxonomy Framework 2017",
    date: "Public working draft; Dec 2016",
    jurisdiction: "Global accounting and operational data",
    access: "Open specification",
    note: "Defines a modular format for journal, master-data, multicurrency, tax-audit, inventory, and fixed-asset fields. It is an older public working draft and should be evaluated against current implementation needs before adoption.",
    href: "https://www.xbrl.org/int/gl/2016-12-01/gl-framework-2017-PWD-2016-12-01.html",
  },
  {
    id: "src_ifrs26taxarch",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "IFRS Foundation",
    title: "Using the IFRS Digital Taxonomies — The Taxonomy Architecture",
    date: "Technical guide; Jun 2026",
    jurisdiction: "Global IFRS digital reporting",
    access: "Open PDF; taxonomy commercial use may require a licence",
    note: "Explains the models, relationships, extensions, and architecture behind machine-readable IFRS reporting. The guide states that some commercial uses of taxonomy files require permission from the IFRS Foundation.",
    href: "https://www.ifrs.org/content/dam/ifrs/standards/taxonomy/general-resources/ifrs-taxonomy-architecture/taxonomy-architecture-2026.pdf",
  },
  {
    id: "src_sec26xbrl",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "US Securities and Exchange Commission",
    title: "EDGAR XBRL Guide",
    date: "Technical guide; Aug 2026",
    jurisdiction: "United States SEC filings",
    access: "Open PDF",
    note: "Provides EDGAR XBRL formatting and validation specifications. Filers must still follow the EDGAR Filer Manual, forms, rules, and current technical specifications.",
    href: "https://www.sec.gov/files/edgar/filer-information/specifications/xbrl-guide.pdf",
  },
  {
    id: "src_xbrlusdqc",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL US Data Quality Committee",
    title: "Approved XBRL Validation Rules",
    date: "Living ruleset; v30.0.3 reviewed Aug 2026",
    jurisdiction: "United States SEC filings; selected ESEF mappings",
    access: "Open documentation and rules",
    note: "Publishes reviewed business-validation rules for common filing issues such as calculation, dates, dimensions, signs, and duplicates. A rule alert is evidence for review, not a compliance or misstatement conclusion.",
    href: "https://xbrl.us/home/priorities/data-quality/rules-guidance/",
  },
  {
    id: "src_xbrlcalc11",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "XBRL International",
    title: "Calculations 1.1",
    date: "Recommendation; Feb 2023, errata Feb 2024",
    jurisdiction: "Global digital reporting",
    access: "Open specification",
    note: "Defines calculation-consistency checks that address rounding and duplicate-fact weaknesses in earlier XBRL calculations. Consistency under the specification does not prove the underlying accounting treatment is correct.",
    href: "https://www.xbrl.org/Specification/calculation-1.1/REC-2023-02-22+corrected-errata-2024-02-14/calculation-1.1-REC-2023-02-22+corrected-errata-2024-02-14.html",
  },
  {
    id: "src_saft140",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "Norwegian Tax Administration",
    title: "SAF-T Financial 1.40 Documentation",
    date: "Technical documentation; Apr 2026",
    jurisdiction: "Norway; financial accounting data",
    access: "Open documentation, schemas, examples, and code lists",
    note: "A current implementation package for standardized general-ledger and master-data exchange, required in Norway from January 2027. It is jurisdiction-specific but useful as a concrete machine-readable accounting contract.",
    href: "https://www.skatteetaten.no/en/business-and-organisation/start-and-run/best-practices-accounting-and-cash-register-systems/saf-t-financial/documentation/",
  },
  {
    id: "src_esef2019",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "European Union",
    title: "European Single Electronic Format Regulation",
    date: "Consolidated text; Jan 2025",
    jurisdiction: "European Union regulated annual financial reports",
    access: "Open official text",
    note: "Requires XHTML annual reports and XBRL markup for in-scope IFRS consolidated financial statements. Scope, taxonomy versions, extensions, and filing obligations must be checked against current EU and national rules.",
    href: "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A02019R0815-20250101",
  },
  {
    id: "src_far26badadvice",
    topic: "Audit and assurance",
    kind: "Evidence",
    owner: "Foundation for Auditing Research",
    title: "When Do Auditors Rely on (Bad) AI Advice?",
    date: "Practitioner research summary; Feb 2026",
    jurisdiction: "Professional-auditor experiment",
    access: "Open HTML and PDF",
    note: "Summarizes experimental evidence that accuracy-versus-error framing changes reliance on high- and low-quality AI advice. Use the underlying study for complete methods, sample, and statistical results.",
    href: "https://foundationforauditingresearch.org/publications/when-do-auditors-rely-on-bad-ai-advice/",
  },
  {
    id: "src_aicpa26resp",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "AICPA & CIMA",
    title: "Responsible Use of Gen AI for Finance Teams",
    date: "Professional guidance; Jun 2026",
    jurisdiction: "United States and global finance profession",
    access: "Open HTML",
    note: "A concise profession-facing route from finance risks to COSO's GenAI control guidance. It is introductory and should be used with the underlying COSO framework already indexed in this library.",
    href: "https://www.aicpa-cima.com/resources/article/responsible-use-of-gen-ai-for-finance-teams",
  },
  {
    id: "src_saicagenai",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "South African Institute of Chartered Accountants",
    title: "Professional Ethical Responsibilities in the Use and Adoption of Generative AI",
    date: "Professional guidance; 2025",
    jurisdiction: "South Africa; SAICA members and associates",
    access: "Open PDF",
    note: "Applies professional competence, skepticism, judgment, confidentiality, and accountability across use, development, operation, and control of GenAI. Binding effect arises from the SAICA Code and membership regime, not the guide alone.",
    href: "https://saicawebprstorage.blob.core.windows.net/uploads/Professional-ethics-in-the-use-of-Generative-AI-language.pdf",
  },
  {
    id: "src_ccab26draft",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Consultative Committee of Accountancy Bodies",
    title: "Draft Statement on the Ethical Use of Artificial Intelligence",
    date: "Exposure draft; Jun 2026",
    jurisdiction: "United Kingdom accountancy profession",
    access: "Open PDF",
    note: "Extends IESBA-based ethical analysis across development, procurement, deployment, monitoring, and autonomous agents and discloses AI assistance in drafting. It remains consultation material, not final guidance.",
    href: "https://www.ccab.org.uk/wp-content/uploads/2026/06/CCAB.Draft-Statement-to-the-Profession-on-Use-of-AI.-Exposure-Draft.6.6.26-002.pdf",
  },
  {
    id: "src_joa26ethics",
    topic: "Law and policy",
    kind: "Thought piece",
    owner: "Journal of Accountancy",
    title: "Accounting Ethics in the Age of AI",
    date: "Practitioner article; Aug 2026",
    jurisdiction: "United States CPAs",
    access: "Open HTML",
    note: "Maps competence, due care, confidentiality, independence, and professional judgment to everyday AI use. It is explanatory journalism, not authoritative ethics guidance; follow the cited AICPA Code provisions.",
    href: "https://www.journalofaccountancy.com/issues/2026/aug/accounting-ethics-in-the-age-of-ai/",
  },
  {
    id: "src_kpmgaireporting",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "KPMG",
    title: "AI and Automation in Financial Reporting",
    date: "Implementation guide; 2024",
    jurisdiction: "Financial reporting processes; jurisdiction-neutral framing",
    access: "Open PDF",
    note: "A detailed control-oriented guide covering process understanding, AI risks, governance, program change, and IT controls in financial reporting. It is firm-authored guidance, not a standard or independent effectiveness study.",
    href: "https://assets.kpmg.com/content/dam/kpmgsites/ba/pdf/2024/11/ai-in-finance-implementation-guide.pdf.coredownload.inline.pdf",
  },
  {
    id: "src_digitalktp",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Digital Audit Knowledge Transfer Partnership and Beever and Struthers",
    title: "ChatGPT Trials in Audit at Beever and Struthers",
    date: "Practitioner field note; Sep 2024",
    jurisdiction: "United Kingdom audit practice",
    access: "Open blog post",
    note: "Documents a small volunteer pilot using enterprise ChatGPT for minutes, standards, Excel, and workpaper drafting, including errors and confidentiality concerns. Self-selection, short duration, and self-report prevent causal performance claims.",
    href: "https://www.digital-audit.uk/blog/chatgpt-trials-in-audit-at-beever-and-struthers",
  },
  {
    id: "src_bdochat",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "TechTarget reporting on BDO USA",
    title: "Chat BDO's Journey from Pilot to Production",
    date: "Reported case study; Apr 2026",
    jurisdiction: "United States accounting and advisory firm",
    access: "Open article",
    note: "A reported implementation account covering secure hosting, internal knowledge retrieval, personas, adoption, and workflow integration. The article is descriptive, relies on firm interviews, and does not independently validate business outcomes.",
    href: "https://www.techtarget.com/searchenterpriseai/feature/GenAI-in-accounting-Chat-BDOs-journey-from-pilot-to-production",
  },
  {
    id: "src_hapaggenai",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Hapag-Lloyd and Databricks",
    title: "Hapag-Lloyd Uses GenAI to Enhance Corporate Audit Efficiency",
    date: "Provider-hosted customer story; 2025",
    jurisdiction: "Corporate internal audit",
    access: "Open HTML",
    note: "Reports measured reductions in drafting and review time for audit findings and executive summaries. Results are customer and provider claims from two prototypes, not an independent audit-quality evaluation.",
    href: "https://www.databricks.com/customers/hapag-lloyd",
  },
  {
    id: "src_rivianagents",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Rivian and Amazon Web Services",
    title: "How Rivian Accelerated Finance Operations with AI Agents",
    date: "Co-authored implementation case; Aug 2026",
    jurisdiction: "United States corporate finance and SAP operations",
    access: "Open blog post",
    note: "Describes purchase-order accrual, close-document, forecasting, and supplier workflows with audit trails and claimed time savings. It is a provider-hosted case co-authored by Rivian, not independent assurance over accuracy or controls.",
    href: "https://aws.amazon.com/blogs/awsforsap/how-rivian-accelerated-finance-operations-with-ai-agents-on-amazon-bedrock/",
  },
  {
    id: "src_icis25judgment",
    topic: "Accounting and reporting",
    kind: "Research paper",
    owner: "Chai, Nicholson, Salijeni, and Sokolovskyy",
    title: "Understanding the Impact of Generative AI on Professional Judgement",
    date: "Peer-reviewed conference short paper; Dec 2025",
    jurisdiction: "One mid-tier United Kingdom accounting firm",
    access: "Open proceedings page",
    note: "Ethnographic fieldwork and 22 interviews identify AI as sparring partner, feedback loop, and potential encroachment on judgment. The short-paper format and single-firm setting limit generalization.",
    href: "https://aisel.aisnet.org/icis2025/gen_ai/gen_ai/19/",
  },
  {
    id: "src_finverbench",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "FinVerBench research project",
    title: "FinVerBench: Benchmark Validity and Calibration in Large Language Model Financial Statement Verification",
    date: "Preprint; May 2026",
    jurisdiction: "SEC XBRL financial statements",
    access: "Open preprint and code",
    note: "Separates clean-statement calibration from injected-error detection and shows extreme false-positive sensitivity to models, prompts, rounding, and observability. It is an early single-author preprint with a small diagnostic sample.",
    href: "https://arxiv.org/abs/2605.29586",
  },
  {
    id: "src_lrec26trace",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Bloomberg research team",
    title: "Verifiable Financial Enterprise Question Answering via Inference-Time Grounding and Traceability",
    date: "Workshop paper; May 2026",
    jurisdiction: "Production financial enterprise assistant",
    access: "Open proceedings page and PDF",
    note: "Reports a modular grounding and traceability control evaluated with intrinsic metrics and user feedback in production. The paper addresses financial question answering, not accounting actions or assurance conclusions.",
    href: "https://lrec.elra.info/lrec2026-ws-fnp-04",
  },
  {
    id: "src_holstein26",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Holstein, Hemmer, Satzger, and Sun",
    title: "When Thinking Pays Off: Incentive Alignment for Human–AI Collaboration",
    date: "Peer-reviewed conference paper; Jun 2026",
    jurisdiction: "General human–AI decision experiment",
    access: "Abstract open; article access varies",
    note: "Shows that targeted incentives can reduce overreliance while poorly designed incentives can harm performance or invite gaming. The experimental image-classification task is a design analogy, not accounting evidence.",
    href: "https://doi.org/10.1145/3805689.3812250",
  },
  {
    id: "src_certtraces",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Columbia University SecureFinAI Lab",
    title: "No Certificate, No Execution: Certified Traces as a Foundation for Trustworthy AI Agents",
    date: "Preprint; May 2026",
    jurisdiction: "High-stakes policy-governed agent systems",
    access: "Open preprint",
    note: "Proposes separating probabilistic generation from deterministic permission certification before execution. It is a formal research agenda, not an implemented control standard or evaluated accounting system.",
    href: "https://doi.org/10.48550/arxiv.2605.24462",
  },
  {
    id: "src_aadp",
    topic: "Security and identity",
    kind: "Technical reference",
    owner: "Internet Engineering Task Force contributors",
    title: "Agent Action Decision Protocol: Per-Action Authorization for AI Agents",
    date: "Internet-Draft; 2026",
    jurisdiction: "Open internet protocol work",
    access: "Open draft",
    note: "Explores authorization for specific proposed actions under mutable policy rather than relying only on identity or static scopes. It is an expiring Internet-Draft and must not be treated as an IETF standard.",
    href: "https://www.ietf.org/archive/id/draft-saha-aadp-01.html",
  },
  {
    id: "src_oauthagentdraft",
    topic: "Security and identity",
    kind: "Technical reference",
    owner: "Internet Engineering Task Force contributors",
    title: "Agent Authorization Use Cases and Gap Analysis",
    date: "Internet-Draft; Aug 2026",
    jurisdiction: "Open internet protocol work",
    access: "Open draft",
    note: "Documents gaps between OAuth's common user-present model and long-running, chained, dynamic agent delegation. It proposes no protocol and remains work in progress that may be replaced or expire.",
    href: "https://www.ietf.org/archive/id/draft-chen-oauth-agent-authz-use-cases-02.html",
  },
  {
    id: "src_etsi104119",
    topic: "Evaluation and evidence",
    kind: "Technical reference",
    owner: "European Telecommunications Standards Institute",
    title: "ETSI TR 104 119: Guidelines for Documentation of AI-Enabled Systems",
    date: "Technical report; Sep 2025",
    jurisdiction: "European and international AI system documentation",
    access: "Open PDF",
    note: "Provides lifecycle, stakeholder, quality, and documentation-scheme guidance, including links to EU AI Act requirements. It is a technical report rather than a conformity requirement.",
    href: "https://www.etsi.org/deliver/etsi_tr/104100_104199/104119/01.01.01_60/tr_104119v010101p.pdf",
  },
  {
    id: "src_etsi104008",
    topic: "Evaluation and evidence",
    kind: "Rule or standard",
    owner: "European Telecommunications Standards Institute",
    title: "ETSI TS 104 008: Continuous Auditing-Based Conformity Assessment for AI-Enabled Systems",
    date: "Technical specification; Jan 2026",
    jurisdiction: "European and international AI conformity assessment",
    access: "Open PDF",
    note: "Specifies roles and process elements for ongoing conformity assessment through self-assessment, third-party assessment, or certification paths. Applicability depends on the criteria, assurance scope, independence, and governing law.",
    href: "https://www.etsi.org/deliver/etsi_ts/104000_104099/104008/01.01.01_60/ts_104008v010101p.pdf",
  },
  {
    id: "src_dodaite",
    topic: "Evaluation and evidence",
    kind: "Official guidance",
    owner: "US Department of Defense, Developmental Test, Evaluation, and Assessments",
    title: "Developmental Test and Evaluation of Artificial Intelligence-Enabled Systems Guidebook",
    date: "Guidebook; Feb 2025",
    jurisdiction: "United States defense acquisition; transferable testing concepts",
    access: "Open PDF",
    note: "Detailed lifecycle guidance on testable requirements, operational context, formal methods, human-systems integration, calibrated trust, and emergent behavior. Defense acquisition constraints differ materially from finance and accounting.",
    href: "https://www.cto.mil/wp-content/uploads/2025/02/TE_of_AIES_Guidebook_Final_26Feb25.pdf",
  },
  {
    id: "src_treas24aicyber",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "US Department of the Treasury",
    title: "Managing Artificial Intelligence-Specific Cybersecurity Risks in the Financial Services Sector",
    date: "Sector risk report; Mar 2024",
    jurisdiction: "United States financial services",
    access: "Open PDF",
    note: "Grounds AI cyber, fraud, data, governance, and third-party recommendations in interviews with 42 financial-services and technology organizations. Interview evidence and recommendations do not create binding requirements.",
    href: "https://home.treasury.gov/system/files/136/Managing-Artificial-Intelligence-Specific-Cybersecurity-Risks-In-The-Financial-Services-Sector.pdf",
  },
  {
    id: "src_esma24ai",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "European Securities and Markets Authority",
    title: "Public Statement on AI and Investment Services",
    date: "Supervisory statement; May 2024",
    jurisdiction: "European Union investment firms",
    access: "Open HTML and PDF",
    note: "Applies MiFID II organizational, conduct, and client-interest duties to AI uses including support, compliance, risk, advice, and portfolio management. It is sector-specific and should be read with applicable law and national supervision.",
    href: "https://www.esma.europa.eu/press-news/esma-news/esma-provides-guidance-firms-using-artificial-intelligence-investment-services",
  },
  {
    id: "src_eiopa25ai",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "European Insurance and Occupational Pensions Authority",
    title: "Opinion on Artificial Intelligence Governance and Risk Management",
    date: "Supervisory opinion; Aug 2025",
    jurisdiction: "European Union insurance undertakings",
    access: "Open opinion and impact assessment",
    note: "Clarifies risk-based and proportionate governance expectations for insurers' AI systems. Insurance and actuarial use cases are transferable only where the accounting-agent risk and legal context are comparable.",
    href: "https://www.eiopa.europa.eu/publications/opinion-artificial-intelligence-governance-and-risk-management_en",
  },
  {
    id: "src_hkma19ai",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Hong Kong Monetary Authority",
    title: "High-Level Principles on Artificial Intelligence",
    date: "Supervisory circular; Nov 2019, current",
    jurisdiction: "Hong Kong authorized institutions",
    access: "Open PDF",
    note: "Covers board accountability, model design and validation, data quality, explainability, auditability, fairness, human oversight, and third-party AI. It predates generative agents but remains a useful supervisory baseline.",
    href: "https://www.hkma.gov.hk/media/eng/doc/key-information/guidelines-and-circular/2019/20191101e1.pdf",
  },
  {
    id: "src_enisa23ai",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "European Union Agency for Cybersecurity",
    title: "Multilayer Framework for Good Cybersecurity Practices for AI",
    date: "Cybersecurity framework; Jun 2023",
    jurisdiction: "European Union; broadly adaptable",
    access: "Open report",
    note: "Organizes cybersecurity foundations, AI-specific controls, and sector-specific practices into a scalable framework. It is cross-sector guidance and predates current tool-using agent patterns.",
    href: "https://enisa.europa.eu/publications/multilayer-framework-for-good-cybersecurity-practices-for-ai",
  },
  {
    id: "src_uk25aicode",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "UK Department for Science, Innovation and Technology",
    title: "Code of Practice for the Cyber Security of AI",
    date: "Voluntary code; Jan 2025",
    jurisdiction: "United Kingdom; broadly adaptable",
    access: "Open HTML under the Open Government Licence",
    note: "Sets lifecycle provisions for AI developers, system operators, and data custodians covering threats, supply chains, incident management, secure operation, and end-of-life. It is voluntary rather than a certification standard.",
    href: "https://www.gov.uk/government/publications/ai-cyber-security-code-of-practice/code-of-practice-for-the-cyber-security-of-ai",
  },
  {
    id: "src_oecd23acct",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "Organisation for Economic Co-operation and Development",
    title: "Advancing Accountability in AI",
    date: "Policy research paper; Feb 2023",
    jurisdiction: "International AI governance",
    access: "Open PDF",
    note: "Translates lifecycle roles, risk management, system classification, documentation, and accountability into implementation concepts. It is OECD policy analysis rather than an accounting or assurance standard.",
    href: "https://www.oecd.org/content/dam/oecd/en/publications/reports/2023/02/advancing-accountability-in-ai_753bf8c8/2448f04b-en.pdf",
  },
  {
    id: "src_uk21assure",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "UK Centre for Data Ethics and Innovation",
    title: "The Roadmap to an Effective AI Assurance Ecosystem",
    date: "Government roadmap; Dec 2021",
    jurisdiction: "United Kingdom; cross-sector AI assurance",
    access: "Open HTML under the Open Government Licence",
    note: "Maps assurance roles, evidence, standards, skills, liability, market infrastructure, and organizational responsibilities. It is a strategic ecosystem roadmap rather than an assurance engagement standard.",
    href: "https://www.gov.uk/government/publications/the-roadmap-to-an-effective-ai-assurance-ecosystem/the-roadmap-to-an-effective-ai-assurance-ecosystem-extended-version",
  },
  {
    id: "src_g7tprm",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "G7 Cyber Expert Group",
    title: "Fundamental Elements for Third-Party Cyber Risk Management in the Financial Sector",
    date: "Intergovernmental principles; Oct 2022",
    jurisdiction: "G7 financial sector; broadly adaptable",
    access: "Open PDF",
    note: "Covers governance, due diligence, contracting, monitoring, incidents, concentration, continuity, and exit for external providers. It is technology-neutral but directly relevant to model, data, cloud, and agent-tool dependencies.",
    href: "https://assets.publishing.service.gov.uk/media/63dcd54bd3bf7f070ffc1e87/2022-10-13-g7-fundamental-elements-third-party-risk.pdf",
  },
  {
    id: "src_bis21human",
    topic: "Controls and governance",
    kind: "Technical reference",
    owner: "Bank for International Settlements Financial Stability Institute",
    title: "Humans Keeping AI in Check — Emerging Regulatory Expectations in the Financial Sector",
    date: "FSI Insights No. 35; Aug 2021",
    jurisdiction: "International financial regulation",
    access: "Open PDF",
    note: "Synthesizes expectations for boards, senior management, human oversight, validation, explainability, data governance, and internal audit. It predates generative AI and reflects authors' analysis rather than binding BIS policy.",
    href: "https://www.bis.org/fsi/publ/insights35.pdf",
  },
  {
    id: "src_agenticaudit",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Schreyer, Gu, Moffitt, and Vasarhelyi",
    title: "Artificial Intelligence Agentic Auditing",
    date: "Working paper; Jul 2024, revised Jan 2025",
    jurisdiction: "Financial-audit design and synthetic journal-entry case",
    access: "Open SSRN abstract and paper",
    note: "Introduces an agentic-audit framework and a journal-entry-testing case with iterative refinement and specialist tools. It is an exploratory working paper and design demonstration, not evidence of audit-quality outcomes or autonomous production use.",
    href: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4909147",
  },
  {
    id: "src_auditflow26",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "AuditFlow research team",
    title: "AuditFlow: Executable Symbolic Environments for Structured Financial Reporting Verification",
    date: "Preprint; Jun 2026",
    jurisdiction: "US GAAP XBRL filings and three Data Quality Committee rule families",
    access: "Open preprint",
    note: "Evaluates graph-grounded agents with deterministic checks on 67 FinAuditing-derived cases. Reported joint accuracy is strong for the tested setup, but the sample is small, derived from one benchmark task, and partly scored by an LLM judge.",
    href: "https://arxiv.org/abs/2606.03031",
  },
  {
    id: "src_finagentbench",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Vals AI and Stanford University research team",
    title: "Finance Agent Benchmark: Benchmarking LLMs on Real-World Financial Research Tasks",
    date: "Preprint; Aug 2025",
    jurisdiction: "US public-company filings and investment-research workflows",
    access: "Open preprint; limited public benchmark split",
    note: "Tests tool-using agents on 537 expert-authored questions grounded in recent SEC filings. The best reported system remained below 50% accuracy; the work emphasizes investment research rather than accounting preparation, and most test items are not public.",
    href: "https://arxiv.org/abs/2508.00828",
  },
  {
    id: "src_nocodeacct25",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Miguel Resende, FinTech",
    title: "AI Agents and No-Code Tools in Accounting: A Case Study",
    date: "Peer-reviewed open-access article; Nov 2025",
    jurisdiction: "Synthetic income-statement vertical analysis",
    access: "Open access",
    note: "Compares manual, specialized-GPT, and no-code agent workflows across 150 repeated vertical analyses. It measures execution time and process variability in one narrow synthetic task; it does not establish production accuracy, control effectiveness, or safe external communication.",
    href: "https://doi.org/10.3390/fintech4040065",
  },
  {
    id: "src_netsuite26ai",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Oracle NetSuite",
    title: "NetSuite 2026.1 AI Close, Reconciliation, and EPM Capabilities",
    date: "First-party release article; Feb 2026",
    jurisdiction: "NetSuite ERP and EPM product",
    access: "Open product-release article",
    note: "Describes AI-supported close monitoring, reconciliation setup and matching, flux analysis, and related finance features for NetSuite 2026.1. The page is first-party product-direction evidence and disclaims any delivery commitment; availability, effectiveness, learning behavior, accuracy, and control claims require separate verification.",
    href: "https://www.netsuite.com/portal/resource/articles/financial-management/netsuite-2026-1-features-new-ai-close-and-cash-management-ai-agents-for-enterprise-performance-management-and-more.shtml",
  },
  {
    id: "src_sageclose25",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Sage Intacct",
    title: "Close Automation — General Availability",
    date: "First-party release documentation; 2025 Release 3",
    jurisdiction: "Sage Intacct; United Kingdom and United States availability",
    access: "Open product documentation; subscription required for use",
    note: "Documents close-task monitoring, subledger-to-general-ledger reconciliation assistance, variance alerts, permissions, dependencies, and regional availability. It establishes documented product behavior, not autonomous accounting or independently measured outcomes.",
    href: "https://www.intacct.com/ia/docs/en_GB/releasenotes/2025/2025_Release_3/Copilot/2025-R3-close-automation.htm",
  },
  {
    id: "src_digitsagents25",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Digits",
    title: "Introducing Digits Accounting Agents",
    date: "First-party product announcement; Jun 2025",
    jurisdiction: "Commercial small-business accounting platform",
    access: "Open announcement; paid product",
    note: "Describes general-ledger, bookkeeping, reporting, reconciliation, bill-pay, invoicing, and close agents. It is vendor-authored availability and positioning evidence; automation rates, accuracy, scale, and customer outcomes require separate validation.",
    href: "https://digits.com/blog/introducing-digits-accounting-agents/",
  },
  {
    id: "src_prophixagents25",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Prophix",
    title: "Prophix One Budgeting and Reporting Agents",
    date: "First-party product announcement; Sep 2025",
    jurisdiction: "Commercial financial-performance-management platform",
    access: "Open announcement; paid product",
    note: "Documents announced budgeting and reporting agents, stated availability, policy guardrails, and audit-trail features. Performance and cycle-time claims come from the provider and its own finance team, not an independent evaluation.",
    href: "https://www.prophix.com/news/prophix-launches-the-first-autonomous-agents-for-finance-marking-a-new-era-in-finance/",
  },
  {
    id: "src_ifrsconcept18",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "IFRS Foundation and IASB",
    title: "IFRS Conceptual Framework for Financial Reporting",
    date: "Revised Mar 2018; current framework",
    jurisdiction: "Global; IFRS jurisdictions and IASB standard setting",
    access: "Official landing page; full access terms vary",
    note: "Frames reporting objectives, qualitative characteristics, elements, recognition, measurement, and presentation. It is not an IFRS Standard and cannot override a specific Standard or local endorsement.",
    href: "https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/",
  },
  {
    id: "src_ifrsmc2025",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "IFRS Foundation and IASB",
    title: "IFRS Practice Statement 1: Management Commentary",
    date: "Revised Jun 2025",
    jurisdiction: "Global; local adoption and reporting law vary",
    access: "Official summary; full statement access varies",
    note: "Connects financial, sustainability, and other value-creation narrative for management commentary. Applying it is not required to claim IFRS compliance, and local reporting requirements remain controlling.",
    href: "https://www.ifrs.org/issued-standards/list-of-standards/management-commentary-practice-statement-1/",
  },
  {
    id: "src_ifrss12023",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "IFRS Foundation and ISSB",
    title: "IFRS S1, General Requirements for Disclosure of Sustainability-related Financial Information",
    date: "Issued Jun 2023; effective Jan 2024",
    jurisdiction: "Global sustainability disclosure; adoption varies",
    access: "Official navigator; text access terms vary",
    note: "Sets general sustainability-disclosure requirements across governance, strategy, risk management, metrics, and targets. It is not a financial-accounting or assurance standard, and jurisdictional adoption must be confirmed.",
    href: "https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s1-general-requirements/",
  },
  {
    id: "src_ifrss22023",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "IFRS Foundation and ISSB",
    title: "IFRS S2, Climate-related Disclosures",
    date: "Issued Jun 2023; effective Jan 2024; amended Dec 2025",
    jurisdiction: "Global climate disclosure; adoption varies",
    access: "Official navigator; text access terms vary",
    note: "Covers climate risks and opportunities, governance, strategy, risk management, metrics, and industry-based guidance. It is climate-specific and does not replace accounting, assurance, or local disclosure requirements.",
    href: "https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s2-climate-related-disclosures/",
  },
  {
    id: "src_ifrsstax24",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "IFRS Foundation",
    title: "IFRS Sustainability Disclosure Taxonomy 2024",
    date: "Published Apr 2024",
    jurisdiction: "Global digital sustainability reporting",
    access: "Open taxonomy landing page and package links",
    note: "Provides machine-readable tags for IFRS S1 and S2 disclosures, including industry material. The taxonomy does not create disclosure requirements and must be pinned to a specific release.",
    href: "https://www.ifrs.org/issued-standards/ifrs-sustainability-taxonomy/ifrs-sustainability-disclosure-taxonomy-2024/",
  },
  {
    id: "src_secsab0099",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "US Securities and Exchange Commission staff",
    title: "Staff Accounting Bulletin No. 99 — Materiality",
    date: "Aug 1999; current staff guidance",
    jurisdiction: "United States SEC registrants",
    access: "Open government HTML",
    note: "Explains why quantitative thresholds cannot replace qualitative materiality analysis. It is SEC staff guidance, not a Commission rule or a mechanical conclusion engine.",
    href: "https://www.sec.gov/interps/account/sab99.htm",
  },
  {
    id: "src_secsab0108",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "US Securities and Exchange Commission staff",
    title: "Staff Accounting Bulletin No. 108",
    date: "Sep 2006; current staff guidance",
    jurisdiction: "United States SEC registrants",
    access: "Open government HTML",
    note: "Addresses rollover and iron-curtain approaches to evaluating current- and prior-year misstatements. It is staff guidance rather than a Commission rule, and registrant facts remain controlling.",
    href: "https://www.sec.gov/rules-regulations/staff-guidance/staff-accounting-bulletins/staff-accounting-bulletin-no-108",
  },
  {
    id: "src_irspub1075",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "Internal Revenue Service",
    title: "Publication 1075: Tax Information Security Guidelines",
    date: "Rev. Nov 2021; current Safeguards Program reference",
    jurisdiction: "United States federal tax information recipients",
    access: "Open government PDF",
    note: "Covers safeguards, access, encryption, contractors, cloud services, and incidents for federal tax information. It does not apply to every accounting dataset or replace tax law and agency-specific requirements.",
    href: "https://www.irs.gov/pub/irs-pdf/p1075.pdf",
  },
  {
    id: "src_oecdtax30",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Organisation for Economic Co-operation and Development",
    title: "Tax Administration 3.0: The Digital Transformation of Tax Administration",
    date: "Dec 2020",
    jurisdiction: "International tax administration",
    access: "Open report landing page and PDF",
    note: "Describes a digitally integrated tax-administration operating model, data exchange, and taxpayer interaction. It is a non-binding strategy report, not tax law or evidence that a particular AI system works.",
    href: "https://www.oecd.org/en/publications/tax-administration-3-0-the-digital-transformation-of-tax-administration_ca274cc5-en.html",
  },
  {
    id: "src_fasbtax2025",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "Financial Accounting Standards Board",
    title: "2025 GAAP Financial Reporting Taxonomy",
    date: "2025 taxonomy release",
    jurisdiction: "United States GAAP digital reporting",
    access: "Open official page and downloads",
    note: "Provides versioned US GAAP concepts and digital-reporting artifacts. The taxonomy is not the Codification and does not create accounting requirements; annual releases require explicit version control.",
    href: "https://fasb.org/page/detail?pageId=%2Fprojects%2FFASB-Taxonomies%2F2025-gaap-financial-reporting-taxonomy.html",
  },
  {
    id: "src_xbrloim10",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL International",
    title: "Open Information Model 1.0",
    date: "Recommendation Apr 2023",
    jurisdiction: "Global digital reporting",
    access: "Open specification index",
    note: "Defines a syntax-independent XBRL model and transformations for xBRL-JSON, CSV, and XML. It covers XBRL semantics and conformance, not the accounting meaning of a reported fact.",
    href: "https://specifications.xbrl.org/work-product-index-open-information-model-open-information-model.html",
  },
  {
    id: "src_xbrltaxpkg",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "XBRL International",
    title: "Taxonomy Packages 1.0",
    date: "Recommendation Apr 2016",
    jurisdiction: "Global digital reporting",
    access: "Open specification",
    note: "Defines taxonomy-package manifests, URL remapping, metadata, and versioning support. It governs packaging rather than report semantics, and the package version and dependencies must be controlled.",
    href: "https://www.xbrl.org/Specification/taxonomy-package/REC-2016-04-19/taxonomy-package-REC-2016-04-19.html",
  },
  {
    id: "src_iso20022",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "ISO TC 68 Financial Services",
    title: "ISO 20022",
    date: "Continuously maintained standard and repository",
    jurisdiction: "Global financial messaging; market profiles vary",
    access: "Open official portal; ISO rights apply",
    note: "Provides common message semantics for payments, securities, trade finance, cards, and foreign exchange. A message is not a ledger entry or accounting conclusion, and implementation profiles differ by market.",
    href: "https://www.iso20022.org/",
  },
  {
    id: "src_datasheets21",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Gebru and coauthors",
    title: "Datasheets for Datasets",
    date: "CACM publication Dec 2021; preprint 2018",
    jurisdiction: "Cross-domain dataset governance",
    access: "Open preprint; publication access varies",
    note: "Proposes documentation for dataset motivation, composition, collection, processing, use, distribution, and maintenance. Documentation improves provenance but does not prove quality, legality, representativeness, or fitness.",
    href: "https://arxiv.org/abs/1803.09010",
  },
  {
    id: "src_modelcards19",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Mitchell and coauthors",
    title: "Model Cards for Model Reporting",
    date: "FAT* 2019; preprint 2018",
    jurisdiction: "Cross-domain model governance",
    access: "Open preprint; publication rights apply",
    note: "Proposes model disclosures for intended use, evaluation conditions, performance, limitations, and ethical considerations. A model card is disclosure, not evidence of production reliability or accounting suitability.",
    href: "https://arxiv.org/abs/1810.03993",
  },
  {
    id: "src_ibmfactsheets",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "IBM Research",
    title: "FactSheets: Increasing Trust in AI Services through Supplier Declarations of Conformity",
    date: "IBM Journal of Research and Development; Jul 2019",
    jurisdiction: "Cross-domain AI service governance",
    access: "Open research summary; article rights apply",
    note: "Proposes service-level supplier declarations covering purpose, performance, safety, security, and provenance. Supplier self-report is not independent assurance or professional approval.",
    href: "https://research.ibm.com/publications/factsheets-increasing-trust-in-ai-services-through-suppliers-declarations-of-conformity",
  },
  {
    id: "src_crfmfoundation",
    topic: "Agent engineering",
    kind: "Research paper",
    owner: "Stanford Center for Research on Foundation Models",
    title: "On the Opportunities and Risks of Foundation Models",
    date: "Research report; Aug 2021, revised Jul 2022",
    jurisdiction: "Cross-domain foundation-model research",
    access: "Open preprint",
    note: "Surveys foundation-model capabilities, data, evaluation, security, applications, and systemic risks. It is broad background, not accounting evidence, current product evaluation, or control guidance.",
    href: "https://arxiv.org/abs/2108.07258",
  },
  {
    id: "src_react2023",
    topic: "Agent engineering",
    kind: "Research paper",
    owner: "Yao and coauthors",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    date: "ICLR 2023",
    jurisdiction: "Cross-domain agent research",
    access: "Open preprint and conference paper",
    note: "Introduces interleaved reasoning, external actions, and observations for tool-using agents. Its QA and interactive benchmarks do not make reasoning traces audit evidence or establish accounting authority.",
    href: "https://arxiv.org/abs/2210.03629",
  },
  {
    id: "src_toolformer23",
    topic: "Agent engineering",
    kind: "Research paper",
    owner: "Schick and coauthors",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    date: "Preprint; Feb 2023",
    jurisdiction: "Cross-domain tool-use research",
    access: "Open preprint",
    note: "Studies when a language model should call APIs and how it incorporates results. Learned tool use does not establish authorization, approved sources, deterministic correctness, or accountable review.",
    href: "https://arxiv.org/abs/2302.04761",
  },
  {
    id: "src_reflexion23",
    topic: "Agent engineering",
    kind: "Research paper",
    owner: "Shinn and coauthors",
    title: "Reflexion: Language Agents with Verbal Reinforcement Learning",
    date: "NeurIPS 2023",
    jurisdiction: "Cross-domain agent research",
    access: "Open preprint and code",
    note: "Studies linguistic feedback and episodic reflective memory across repeated trials. Self-generated reflection can preserve or compound error and does not replace accountable human review.",
    href: "https://arxiv.org/abs/2303.11366",
  },
  {
    id: "src_mllifecycle",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Suresh and Guttag",
    title: "A Framework for Understanding Sources of Harm throughout the Machine Learning Life Cycle",
    date: "EAAMO 2021; revised Dec 2021",
    jurisdiction: "Cross-domain machine-learning lifecycle",
    access: "Open preprint",
    note: "Distinguishes seven sources of harm across data collection, development, and deployment. It is a research taxonomy, not a formal risk standard or an accounting-control conclusion.",
    href: "https://arxiv.org/abs/1901.10002",
  },
  {
    id: "src_trustautomation",
    topic: "Controls and governance",
    kind: "Research paper",
    owner: "Lee and See",
    title: "Trust in Automation: Designing for Appropriate Reliance",
    date: "Human Factors; 2004",
    jurisdiction: "Cross-domain human factors",
    access: "Publisher abstract; article access varies",
    note: "A foundational synthesis of trust calibration, reliance, automation characteristics, context, displays, and feedback. It predates LLM agents and does not define professional review sufficiency.",
    href: "https://journals.sagepub.com/doi/10.1518/hfes.46.1.50_30392",
  },
  {
    id: "src_humanaiguides",
    topic: "Agent engineering",
    kind: "Research paper",
    owner: "Microsoft Research and CHI",
    title: "Guidelines for Human-AI Interaction",
    date: "CHI 2019",
    jurisdiction: "Cross-domain human-AI interface design",
    access: "Open DOI page; publication rights apply",
    note: "Presents 18 empirically validated interaction guidelines for initial use, ongoing use, errors, and adaptation. The guidelines are not a compliance checklist and predate current agentic interfaces.",
    href: "https://doi.org/10.1145/3290605.3300233",
  },
  {
    id: "src_ncuai2026",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "National Credit Union Administration",
    title: "Artificial Intelligence — Regulatory and Supervisory Resources",
    date: "Living regulator page; modified Apr 2026",
    jurisdiction: "United States federally insured credit unions",
    access: "Open government HTML",
    note: "Frames vendor diligence, member-data handling, fair lending, model and operational risk, internal controls, monitoring, and board oversight. NCUA states that it has no AI-specific regulation and supervises AI under existing frameworks.",
    href: "https://ncua.gov/regulation-supervision/regulatory-compliance-resources/artificial-intelligence-ai",
  },
  {
    id: "src_banktprm23",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Federal Reserve Board, FDIC, and OCC",
    title: "Interagency Guidance on Third-Party Relationships: Risk Management",
    date: "Final interagency guidance; Jun 2023",
    jurisdiction: "United States banking organizations",
    access: "Open government HTML and PDF",
    note: "Covers planning, due diligence, contracting, monitoring, accountability, and termination across the third-party lifecycle. It is banking risk guidance rather than AI-specific or accounting-specific authority.",
    href: "https://www.occ.gov/news-issuances/bulletins/2023/bulletin-2023-17.html",
  },
  {
    id: "src_naicaibull",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "National Association of Insurance Commissioners",
    title: "Model Bulletin on the Use of Artificial Intelligence Systems by Insurers",
    date: "Model bulletin adopted Dec 2023",
    jurisdiction: "United States insurance; state adoption varies",
    access: "Open model bulletin PDF",
    note: "Addresses insurer AI inventories, governance, validation and testing, consumer outcomes, documentation, and third parties. It is a model bulletin and becomes directly applicable only through a jurisdiction's action.",
    href: "https://content.naic.org/sites/default/files/inline-files/2023-12-4%20Model%20Bulletin_Adopted_0.pdf",
  },
  {
    id: "src_ifrs17impl",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "IFRS Foundation and IASB",
    title: "IFRS 17 Insurance Contracts — Supporting Material",
    date: "Standard effective Jan 2023; living implementation material",
    jurisdiction: "IFRS insurance accounting; local adoption varies",
    access: "Official supporting-material hub; standard access terms vary",
    note: "Indexes implementation material for contract grouping, fulfilment cash flows, contractual service margin, the premium-allocation approach, reinsurance, transition, and disclosures. The supporting material does not replace IFRS 17 or local endorsement.",
    href: "https://www.ifrs.org/supporting-implementation/supporting-materials-by-ifrs-standards/ifrs-17/",
  },
  {
    id: "src_ioscoai2021",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "International Organization of Securities Commissions",
    title: "Use of Artificial Intelligence and Machine Learning by Market Intermediaries and Asset Managers",
    date: "Final report; Sep 2021",
    jurisdiction: "Global capital markets and asset management",
    access: "Open PDF",
    note: "Covers governance, testing, monitoring, data, bias, explainability, outsourcing, and ethics for market intermediaries and asset managers. It is non-binding supervisory guidance, not accounting-agent outcome evidence.",
    href: "https://www.iosco.org/library/pubdocs/pdf/IOSCOPD684.pdf",
  },
  {
    id: "src_ioscoai2025",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "International Organization of Securities Commissions",
    title: "Artificial Intelligence in Capital Markets: Use Cases, Risks, and Challenges",
    date: "Consultation report; Mar 2025",
    jurisdiction: "Global capital markets",
    access: "Open PDF",
    note: "Surveys current AI uses in research, trading, surveillance, financial crime, and internal operations, with concentration, third-party, data, and human-oversight risks. It is consultation material, not final binding requirements or validated outcomes.",
    href: "https://www.iosco.org/library/pubdocs/pdf/IOSCOPD788.pdf",
  },
  {
    id: "src_hipaaba",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "US Department of Health and Human Services, Office for Civil Rights",
    title: "HIPAA Business Associates",
    date: "Living regulator guidance; reviewed Jul 2026",
    jurisdiction: "United States HIPAA covered entities and business associates",
    access: "Open government HTML",
    note: "Explains when service providers, including accounting services and downstream subcontractors, become business associates handling protected health information and require written safeguards. It does not determine accounting treatment or every fact-specific HIPAA role.",
    href: "https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/business-associates/index.html",
  },
  {
    id: "src_cmsmcref",
    topic: "Practice examples",
    kind: "Official guidance",
    owner: "Centers for Medicare & Medicaid Services",
    title: "Medicare Cost Report Electronic Filing",
    date: "Living filing guidance; modified Jun 2026",
    jurisdiction: "United States Medicare Part A providers",
    access: "Open government HTML and manuals",
    note: "Defines the electronic submission surface for Medicare cost-report packages and supporting documentation, including access and acceptance workflows. It does not authorize unattended filing or replace provider, preparer, or MAC responsibilities.",
    href: "https://www.cms.gov/medicare/audits-compliance/part-a-cost-report/medicare-cost-report-electronic-filing-mcref",
  },
  {
    id: "src_aicpacon25",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "AICPA & CIMA",
    title: "2025 Construction Contractors: Audit and Accounting Guide",
    date: "2025 edition",
    jurisdiction: "United States construction accounting and audit",
    access: "Paid publication landing page",
    note: "Covers contractor economics, bonds, controls over estimates and job costs, billing, revenue and costs, joint ventures, and tailored audit procedures. It is copyrighted professional guidance, not an AI standard or deployment evaluation.",
    href: "https://www.aicpa-cima.com/cpe-learning/publication/construction-contractors-audit-and-accounting-guide",
  },
  {
    id: "src_ricsai2025",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "Royal Institution of Chartered Surveyors",
    title: "Responsible Use of Artificial Intelligence in Surveying Practice",
    date: "First edition Sep 2025; effective Mar 2026",
    jurisdiction: "Global RICS members and regulated firms",
    access: "Open landing page; standard rights apply",
    note: "Addresses professional judgment, data and system governance, risk management, procurement, output reliability, assurance, and client transparency in the built environment. It is surveying guidance, not accounting authority.",
    href: "https://www.rics.org/profession-standards/rics-standards-and-guidance/conduct-competence/responsible-use-of-ai",
  },
  {
    id: "src_asu201815",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "Financial Accounting Standards Board",
    title: "ASU 2018-15: Customer's Accounting for Implementation Costs in a Cloud Computing Arrangement",
    date: "Issued Aug 2018; check current Codification",
    jurisdiction: "United States GAAP cloud-computing arrangements",
    access: "Open issued-update PDF; Codification controls",
    note: "Addresses capitalization, expense, amortization, impairment, and presentation of implementation costs in service-contract cloud arrangements. The issued update is not a substitute for the current Codification or a fact-specific conclusion.",
    href: "https://storage.fasb.org/ASU_2018-15.pdf",
  },
  {
    id: "src_focusv14",
    topic: "Accounting and reporting",
    kind: "Technical reference",
    owner: "FinOps Foundation",
    title: "FOCUS Specification 1.4",
    date: "Published specification; 2026",
    jurisdiction: "Cross-provider cloud and SaaS billing data",
    access: "Open specification; CC BY 4.0",
    note: "Defines a common schema and minimum requirements for billing data supporting allocation, chargeback, budgets, and forecasting. It is an operational data contract, not GAAP, and provider conformance and version pinning still require validation.",
    href: "https://focus.finops.org/docs/specification/v1-4/",
  },
  {
    id: "src_fercacct",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "Federal Energy Regulatory Commission",
    title: "Accounting Matters",
    date: "Living regulator hub; updated Jun 2026",
    jurisdiction: "United States FERC-jurisdictional utilities and pipelines",
    access: "Open government HTML and linked authorities",
    note: "Indexes FERC Uniform Systems of Accounts, forms, orders, and Chief Accountant guidance for electric, gas, and oil-pipeline entities. These regulatory requirements are industry-specific and do not establish an AI-agent design.",
    href: "https://www.ferc.gov/accounting-matters-1",
  },
  {
    id: "src_doeeai2024",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "US Department of Energy, CESER",
    title: "Initial Risk Assessment on Artificial Intelligence for Critical Energy Infrastructure",
    date: "Interim assessment; Apr 2024",
    jurisdiction: "United States critical energy infrastructure",
    access: "Open government report",
    note: "Maps AI applications to unintentional failure, adversarial attack, hostile use, and software-supply-chain risks in energy systems. It is an interim operational-risk assessment, not accounting guidance or proof of agent performance.",
    href: "https://www.energy.gov/ceser/articles/doe-delivers-initial-risk-assessment-artificial-intelligence-critical-energy",
  },
  {
    id: "src_nistmfg2",
    topic: "Security and identity",
    kind: "Official guidance",
    owner: "National Institute of Standards and Technology",
    title: "Cybersecurity Framework 2.0 Manufacturing Profile",
    date: "Initial public draft; Sep 2025",
    jurisdiction: "Manufacturing operational technology and industrial control systems",
    access: "Open government draft",
    note: "Maps CSF 2.0 governance and cybersecurity outcomes to manufacturing environments, including supply-chain, platform, and infrastructure resilience. It remains a closed-comment draft, voluntary, and cyber-focused rather than accounting-specific.",
    href: "https://csrc.nist.gov/pubs/ir/8183/r2/ipd",
  },
  {
    id: "src_socsupply",
    topic: "Controls and governance",
    kind: "Official guidance",
    owner: "AICPA & CIMA",
    title: "SOC for Supply Chain",
    date: "Framework publication; Sep 2023",
    jurisdiction: "Production, manufacturing, and distribution systems",
    access: "Official overview; framework access varies",
    note: "Provides a voluntary reporting framework around security, availability, processing integrity, confidentiality, privacy, and supply-chain system controls. It is not an AI or accounting standard and does not establish operating effectiveness without an engagement.",
    href: "https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-soc-for-supply-chain",
  },
  {
    id: "src_pcidss401",
    topic: "Security and identity",
    kind: "Rule or standard",
    owner: "PCI Security Standards Council",
    title: "PCI Data Security Standard v4.0.1",
    date: "Published Jun 2024; future-dated requirements effective Mar 2025",
    jurisdiction: "Global payment-card account-data environments",
    access: "Official document hub; rights apply",
    note: "Defines technical and operational requirements for entities that store, process, transmit, or can affect cardholder-data environments. It is a payment-security standard, not accounting or AI guidance, and exact scope and assessment status must be confirmed.",
    href: "https://www.pcisecuritystandards.org/standards/pci-dss/",
  },
  {
    id: "src_irsretail",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "Internal Revenue Service",
    title: "Retail Industry Audit Technique Guide",
    date: "Publication 5495; revised Mar 2021",
    jurisdiction: "United States retail tax examination",
    access: "Open government PDF",
    note: "Covers receipts, rebates, chargebacks, gift cards, inventory methods, point-of-sale records, online retail, loyalty programs, and cost of goods sold. It is an examiner aid, not law, GAAP, or agent-performance evidence.",
    href: "https://www.irs.gov/pub/irs-pdf/p5495.pdf",
  },
  {
    id: "src_cfr200grants",
    topic: "Law and policy",
    kind: "Rule or standard",
    owner: "US Office of Management and Budget and eCFR",
    title: "2 CFR Part 200, Uniform Administrative Requirements, Cost Principles, and Audit Requirements for Federal Awards",
    date: "Current regulation; major 2024 revision",
    jurisdiction: "United States federal awards",
    access: "Open authoritative eCFR",
    note: "Governs award identifiers, cost allowability, internal controls, subrecipient monitoring, records, and audit requirements for federal awards. It does not authorize agent action or replace award- and entity-specific analysis.",
    href: "https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200",
  },
  {
    id: "src_gasb0096",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "Governmental Accounting Standards Board",
    title: "GASB Statement No. 96, Subscription-Based Information Technology Arrangements",
    date: "Issued May 2020; effective after Jun 2022",
    jurisdiction: "United States state and local governments",
    access: "Open issued-standard PDF; rights apply",
    note: "Addresses subscription liabilities and assets, implementation stages, capitalization, amortization, and disclosures for government SBITAs. It is public-sector accounting authority, not AI guidance.",
    href: "https://storage.gasb.org/GASBS%2096.pdf",
  },
  {
    id: "src_asu202308",
    topic: "Accounting and reporting",
    kind: "Rule or standard",
    owner: "Financial Accounting Standards Board",
    title: "ASU 2023-08: Accounting for and Disclosure of Crypto Assets",
    date: "Issued Dec 2023; effective after Dec 2024",
    jurisdiction: "United States GAAP qualifying crypto assets",
    access: "Open issued-update PDF; Codification controls",
    note: "Introduces fair-value-through-net-income measurement, presentation, reconciliation, and disclosure requirements for qualifying crypto assets. It does not cover every token or replace the current Codification and fact-specific scope analysis.",
    href: "https://storage.fasb.org/ASU%202023-08.pdf",
  },
  {
    id: "src_secsab122",
    topic: "Accounting and reporting",
    kind: "Official guidance",
    owner: "US Securities and Exchange Commission staff",
    title: "Staff Accounting Bulletin No. 122",
    date: "Issued Jan 2025; effective Jan 2025",
    jurisdiction: "United States SEC registrants and crypto-asset safeguarding",
    access: "Open government HTML",
    note: "Rescinds SAB 121 and removes Topic 5.FF while describing transition disclosure. It is SEC staff guidance, not a Commission rule, and entities still evaluate safeguarding obligations under applicable accounting and disclosure requirements.",
    href: "https://www.sec.gov/rules-regulations/staff-guidance/staff-accounting-bulletins/staff-accounting-bulletin-122",
  },
  {
    id: "src_taxpraben26",
    topic: "Evaluation and evidence",
    kind: "Research paper",
    owner: "Hu and coauthors; Association for Computational Linguistics",
    title: "TaxPraBen: A Scalable Benchmark for Structured Evaluation of LLMs in Chinese Real-World Tax Practice",
    date: "ACL 2026",
    jurisdiction: "China tax practice; benchmark research",
    access: "Open ACL Anthology paper",
    note: "Evaluates 19 language models on more than 7,300 structured instances drawn from 14 Chinese tax-practice datasets. Benchmark performance does not establish filing authority, professional acceptability, or transfer to another tax system.",
    href: "https://aclanthology.org/2026.acl-long.1765/",
  },
  {
    id: "src_workiva26agents",
    topic: "Practice examples",
    kind: "Practice example",
    owner: "Workiva",
    title: "Workiva Specialized AI Agents and Intelligence Layer",
    date: "Product announcement; Jul 2026",
    jurisdiction: "Global product; availability and terms vary",
    access: "Open investor-relations release",
    note: "Describes first-party Tie-Out, Benchmarking, and Sustainability Disclosure agents, a knowledge layer, and an MCP gateway for reporting workflows. It establishes vendor-described features, not independent accuracy, adoption, control effectiveness, or customer outcomes.",
    href: "https://investor.workiva.com/news-releases/news-release-details/workiva-launches-specialized-ai-agents-and-intelligence-layer",
  },
  {
    id: "src_irsopr26ai",
    topic: "Law and policy",
    kind: "Official guidance",
    owner: "Internal Revenue Service, Office of Professional Responsibility",
    title: "Introductory Guidelines for Responsible AI Use in Federal Tax Practice",
    date: "Professional-responsibility guidance; Jun 2026",
    jurisdiction: "United States federal tax practice",
    access: "Open government bulletin",
    note: "Directs practitioners to review AI output, facts, citations, calculations, confidentiality, documentation, and professional judgment. It is introductory guidance, not a new regulation or permission to delegate practitioner responsibility.",
    href: "https://content.govdelivery.com/accounts/USIRS/bulletins/41d6e70?reqfrom=share",
  },
] as const;
