import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';

const manifestPath = 'data/coverage/snapshots.json';
const runtimePath = 'data/coverage/snapshots.generated.ts';
const idPattern = /^\d{4}-\d{2}-\d{2}\.\d+$/;
const digest = body => createHash('sha256').update(body).digest('hex');
const json = value => JSON.stringify(value, null, 2) + '\n';
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const compare = (a, b) => a.id.localeCompare(b.id, 'en', { numeric: true });

function runtimeSource(manifest) {
  return '// Generated by scripts/snapshot-history.mjs; edit immutable snapshot inputs instead.\n'
    + manifest.snapshots.map((entry, i) => `import snapshot${i} from "./${entry.path}";`).join('\n')
    + '\n\nconst snapshots: unknown[] = [' + manifest.snapshots.map((_, i) => `snapshot${i}`).join(', ') + '];\n'
    + `const metadata = ${JSON.stringify(manifest.history_metadata)};\n`
    + 'export default { ...metadata, snapshots };\n';
}

/** Read either the historical flat contract or the checksum-indexed store. */
export function readSnapshotHistory({ root = process.cwd() } = {}) {
  const manifest = read(path.join(root, manifestPath));
  assert.ok(Array.isArray(manifest.snapshots), 'Snapshot history must contain an array');
  if (manifest.schema_version !== '2.0.0') {
    assert.equal(manifest.schema_version, '1.0.0', 'Unsupported snapshot history schema');
    return manifest;
  }
  assert.equal(manifest.history_metadata?.schema_version, '1.0.0', 'Unsupported exported history schema');
  assert.equal(new Set(manifest.snapshots.map(entry => entry.id)).size, manifest.snapshots.length, 'Duplicate snapshot ID');
  assert.deepEqual(manifest.snapshots, [...manifest.snapshots].sort(compare), 'Snapshot index must be in numeric edition order');
  const snapshots = manifest.snapshots.map(entry => {
    assert.match(entry.id, idPattern, 'Invalid snapshot ID');
    assert.equal(entry.path, `snapshots/${entry.id}.json`, 'Invalid snapshot path');
    const file = path.join(root, 'data/coverage', entry.path);
    assert.ok(!fs.lstatSync(file).isSymbolicLink(), 'Snapshot files must not be symlinks');
    const body = fs.readFileSync(file);
    assert.equal(body.length, entry.bytes, `Snapshot size mismatch: ${entry.id}`);
    assert.equal(digest(body), entry.sha256, `Snapshot checksum mismatch: ${entry.id}`);
    const snapshot = JSON.parse(body);
    assert.equal(snapshot.id, entry.id, 'Snapshot ID differs from index');
    return snapshot;
  });
  assert.equal(fs.readFileSync(path.join(root, runtimePath), 'utf8'), runtimeSource(manifest), 'Generated snapshot imports differ from index');
  return { ...manifest.history_metadata, snapshots };
}

/** Append or migrate without removing or rewriting any historical object. */
export function writeSnapshotHistory(history, { root = process.cwd() } = {}) {
  const before = readSnapshotHistory({ root });
  const { snapshots, ...metadata } = history;
  assert.deepEqual(metadata, Object.fromEntries(Object.entries(before).filter(([key]) => key !== 'snapshots')), 'Historical metadata must be preserved');
  assert.ok(Array.isArray(snapshots));
  const byId = new Map(snapshots.map(snapshot => [snapshot.id, snapshot]));
  assert.equal(byId.size, snapshots.length, 'Duplicate snapshot ID');
  for (const prior of before.snapshots) assert.deepEqual(byId.get(prior.id), prior, `Immutable snapshot differs or is missing: ${prior.id}`);
  const staged = new Map();
  const entries = [...snapshots].sort(compare).map(snapshot => {
    assert.match(snapshot.id, idPattern, 'Invalid snapshot ID');
    const relative = `snapshots/${snapshot.id}.json`;
    const file = path.join(root, 'data/coverage', relative);
    let body = Buffer.from(json(snapshot));
    if (fs.existsSync(file)) {
      assert.ok(!fs.lstatSync(file).isSymbolicLink(), 'Snapshot files must not be symlinks');
      body = fs.readFileSync(file);
      assert.deepEqual(JSON.parse(body), snapshot, `Immutable snapshot file differs: ${snapshot.id}`);
    } else staged.set(file, body);
    return { id: snapshot.id, path: relative, bytes: body.length, sha256: digest(body) };
  });
  const manifest = { schema_version: '2.0.0', history_metadata: metadata, snapshots: entries };
  staged.set(path.join(root, manifestPath), Buffer.from(json(manifest)));
  staged.set(path.join(root, runtimePath), Buffer.from(runtimeSource(manifest)));
  // All history, paths and collisions have been checked before any writes.
  for (const [file, body] of staged) {
    if (fs.existsSync(file) && fs.readFileSync(file).equals(body)) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
  }
  return manifest;
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  assert.equal(process.argv[2], '--migrate', 'Usage: node scripts/snapshot-history.mjs --migrate');
  const manifest = writeSnapshotHistory(readSnapshotHistory());
  console.log(`Preserved ${manifest.snapshots.length} snapshots in checksum-indexed files.`);
}
