import { coverage, getRecord } from "./corpus";
import { coverageTopology, coverageHistory, coverageMetrics } from "./coverage";
import { shell, esc } from "./render";

const url = (params: URLSearchParams, changes: Record<string,string>) => {
  const next = new URLSearchParams(params); next.delete("page");
  for (const [key, value] of Object.entries(changes)) value ? next.set(key, value) : next.delete(key);
  return `/coverage${next.size ? `?${next}` : ""}`;
};
const count = (value: number) => value.toLocaleString("en-US");
const options = (rows: [string,string][], selected: string) => rows.map(([value, text]) => `<option value="${esc(value)}"${value === selected ? " selected" : ""}>${esc(text)}</option>`).join("");

export function coveragePage(params: URLSearchParams) {
  const data = coverage.select(params), s = data.summary, f = data.filters;
  const selected = data.selected_industry, question = data.selected_question;
  const industryOptions = coverageTopology.industry_backbone.nodes.filter(n => ["sector", "subsector"].includes(n.level) || n.code === f.industry);
  const region = selected ? selected.title : "All industries";
  const table = f.view === "industries"
    ? `<div class="coverage-table-wrap" role="region" aria-label="Industry material table" tabindex="0"><table class="coverage-table"><caption>${selected ? `Inside ${esc(selected.title)}` : "The 20 sectors in NAICS-US 2022"}${question ? ` · ${esc(question.title)}` : ""}</caption><thead><tr><th scope="col">Industry</th><th scope="col">At this scope</th><th scope="col">In narrower industries</th><th scope="col">Scoped assessments</th></tr></thead><tbody>${data.industry_rows.map(n => `<tr><th scope="row"><a href="${esc(url(params,{industry:n.code,show:"all"}))}"><span class="coverage-code">${esc(n.code)}</span>${esc(n.title)} <span aria-hidden="true">→</span></a></th><td>${count(n.direct_records)}</td><td>${count(n.narrower_records)}</td><td>${n.scoped_assessments || '<span class="coverage-muted">Unassessed</span>'}</td></tr>`).join("") || '<tr><td colspan="4">No narrower industries match this view. Use the Questions tab to inspect this scope.</td></tr>'}</tbody></table></div>`
    : `<div class="coverage-table-wrap" role="region" aria-label="Question material table" tabindex="0"><table class="coverage-table"><caption>${esc(region)} · Accounting question families</caption><thead><tr><th scope="col">Question family</th><th scope="col">${selected ? "At this scope" : "Associated records"}</th>${selected ? '<th scope="col">Broader context</th>' : ""}<th scope="col">Scoped assessments</th></tr></thead><tbody>${data.question_rows.map(q => `<tr><th scope="row"><a href="${esc(url(params,{question:q.id,view:"questions",show:"all"}))}">${esc(q.title)}</a><small>${esc(coverageTopology.question_groups[q.group as keyof typeof coverageTopology.question_groups])}</small></th><td>${count(q.associated_records)}</td>${selected ? `<td>${q.broader_context_records}</td>` : ""}<td>${q.scoped_assessments || '<span class="coverage-muted">Unassessed</span>'}</td></tr>`).join("") || `<tr><td colspan="${selected ? 4 : 3}">No question families match this view.</td></tr>`}</tbody></table></div>`;
  const assessments = data.assessments.map(a => `<article class="coverage-assessment" id="${esc(a.id)}"><p class="eyebrow">${esc(a.status)} · ${esc(a.reviewed_at)}</p><h3>${esc(coverage.questionById.get(a.question_id)?.title)} / ${esc(coverage.nodeByCode.get(a.industry_code)?.title)}</h3><p>${esc(a.scope)}</p><dl class="coverage-dimensions">${coverageTopology.depth_dimensions.map(d => `<div><dt>${esc(d.title)}</dt><dd>${esc(a.dimensions[d.id as keyof typeof a.dimensions])}</dd></div>`).join("")}</dl><h4>Remaining gaps</h4><ul>${a.gaps.map(g => `<li>${esc(g)}</li>`).join("")}</ul><details><summary>Evidence and assessment basis</summary><p>${esc(a.review_basis)}</p><ul>${a.evidence_record_ids.map(id => `<li><a href="/records/${esc(id)}">${esc(getRecord(id)?.title || id)}</a></li>`).join("")}</ul><p>${esc(a.reviewer)}. Source currency: ${esc(a.source_currency.replaceAll("-", " "))}.</p></details></article>`).join("");
  const history = coverageHistory.snapshots as { id:string; recorded_at:string; corpus_version:string; topology_version:string; mapping_version:string; summary:Omit<typeof s,"assessment_status_counts"> }[];
  const screening = coverageTopology.subsector_screening.find(p => p.naics_code === f.industry);
  const body = `<article class="coverage-page">
    <header class="coverage-hero"><p class="eyebrow">Research coverage</p><h1>See where the<br>research reaches.</h1><p class="lede">Explore the accounting landscape, find the material we have, and see what still needs assessment.</p><p class="coverage-muted">${count(s.record_count)} records · ${s.industry_counts.sector} sectors · ${s.industry_counts.subsector} subsectors · ${count(s.industry_counts["us-industry"])} detailed US industries · ${s.question_families} question families</p></header>
    <p class="coverage-baseline-label">Entire corpus snapshot · ${esc(data.corpus_version)} · Mapping method ${esc(data.mapping_version)}</p>
    <section class="coverage-stats" aria-label="Entire corpus snapshot; exploration filters apply below">
      <div><strong>${s.question_families_with_material}<span> / ${s.question_families}</span></strong><p>Question families with material</p><small>Proposed content associations</small></div>
      <div><strong>${s.sectors_with_material}<span> / ${s.industry_counts.sector}</span></strong><p>Sectors with associated material</p><small>Includes narrower industries</small></div>
      <div><strong>${s.scoped_assessments}</strong><p>Scoped research assessment${s.scoped_assessments === 1 ? "" : "s"}</p><small>${s.assessment_status_counts.partial} partial · ${s.assessment_status_counts["sufficient-for-stated-scope"]} sufficient for stated scope</small></div>
      <div><a href="/coverage?mapping=question-unassigned#material"><strong>${s.question_unassigned_records}</strong><p>Records awaiting question mapping</p></a><small>Missing mapping does not mean irrelevant</small></div>
    </section>
    <p class="coverage-note">Material counts show where records have been linked. Only a scoped assessment evaluates what that evidence supports. General and broader-industry material does not automatically cover every detailed industry.</p>
    <details class="coverage-definitions"><summary>Metric definitions and source data</summary><p>${esc(coverageMetrics.population)} ${esc(coverageMetrics.time_basis)}</p><dl>${coverageMetrics.definitions.map(m=>`<div><dt>${esc(m.title)} · ${esc(m.unit)}</dt><dd>${esc(m.numerator)}${m.denominator ? `, out of ${esc(m.denominator.toLowerCase())}.` : "."} ${esc(m.caveat)}</dd></div>`).join("")}</dl><p><a href="/downloads/coverage-records.jsonl">Source mapping rows</a> · <a href="/downloads/coverage-assessments.json">Assessment evidence</a> · <a href="/downloads/coverage-topology.json">Industry and question denominators</a></p></details>
    <section class="coverage-explore" aria-labelledby="explore-heading"><div class="coverage-section-head"><h2 id="explore-heading">Explore the landscape</h2><a href="/coverage">Reset view</a></div>
      <form class="coverage-filters" action="/coverage#explore-heading" method="get"><input type="hidden" name="view" value="${esc(f.view)}"/>
        <label>Industry<select name="industry">${options([["","All industries"],...industryOptions.map(n => [n.code,`${n.code} · ${n.title}`] as [string,string])],f.industry)}</select></label>
        <label>Accounting question<select name="question">${options([["","All question families"],...coverageTopology.question_families.map(q=>[q.id,q.title] as [string,string])],f.question)}</select></label>
        <label>Show rows<select name="show">${options([["all","All areas"],["with-material","With associated material"],["without-material","Without direct or narrower material"],["unassessed","With unassessed questions"]],f.show)}</select></label><button type="submit">Apply filters</button>
      </form>
      <nav class="coverage-tabs" aria-label="Coverage views"><a href="${esc(url(params,{view:"industries"}))}"${f.view === "industries" ? ' aria-current="page"' : ""}>Industries</a><a href="${esc(url(params,{view:"questions"}))}"${f.view === "questions" ? ' aria-current="page"' : ""}>Questions</a></nav>
      ${selected ? `<nav class="breadcrumbs" aria-label="Industry hierarchy"><a href="${esc(url(params,{industry:""}))}">All industries</a>${data.ancestors.map(n=>`<span>/</span><a href="${esc(url(params,{industry:n.code}))}">${esc(n.title)}</a>`).join("")}<span>/</span><span>${esc(selected.title)}</span></nav><div class="coverage-selection"><h3>${esc(selected.code)} · ${esc(selected.title)}</h3><p>${selected.direct_records} record${selected.direct_records===1?"":"s"} associated at this scope · ${selected.narrower_records} in narrower industries · ${selected.broader_context_records} in broader context.</p><p>${selected.scoped_assessments ? `${selected.scoped_assessments} scoped assessment; its boundaries are shown below.` : "No assessment at this exact industry scope."}</p></div>` : ""}
      ${question ? `<div class="coverage-selection"><h3>${esc(question.title)}</h3><p>${esc(question.screening_question)}</p><a href="${esc(url(params,{question:""}))}">Show all question families</a></div>` : ""}
      ${screening ? `<details class="coverage-prompt"><summary>Research prompt for ${esc(screening.title)}</summary><p>${esc(screening.screening_question)}</p><p>Proposed screening prompt. Applicability and detailed-industry exceptions remain unassessed.</p></details>` : ""}
      ${table}<p class="coverage-muted">Counts use unique records within each cell. Rows can overlap. “At this scope” means the exact recorded industry code; narrower and broader scopes remain separate.</p>
    </section>
    <section id="assessments"><h2>What has been assessed?</h2>${assessments || `<p>No scoped assessments match this view. Associated records remain available for review below.</p>`}</section>
    <section id="material"><div class="coverage-section-head"><h2>${selected ? "Material at this industry scope" : "Associated and unassigned records"}</h2><span>${count(data.total)} records</span></div>
      <form class="coverage-mapping-filter" action="/coverage#material" method="get">${Object.entries(f).filter(([key,value])=>key!=="mapping"&&value).map(([key,value])=>`<input type="hidden" name="${esc(key)}" value="${esc(value)}"/>`).join("")}<label>Mapping status<select name="mapping">${options([["all","All records in scope"],["question-unassigned","Question not yet assigned"],["industry-unassigned","Industry not yet assigned"],["shared-context","Shared context"]],f.mapping)}</select></label><button type="submit">Filter records</button></form>
      ${data.records.map(r=>`<article class="coverage-record"><div><small>${esc(r.kind)} · ${r.coverage.question_mappings.length ? "Proposed question mapping" : "Question unassigned"}</small><h3><a href="/records/${esc(r.id)}">${esc(r.title)}</a></h3><p>${esc(r.summary)}</p></div><span>${r.coverage.industry_scope === "specific" ? r.coverage.industry_mappings.map(i=>esc(i.industry_code)).join(" · ") : esc(r.coverage.industry_scope.replaceAll("-"," "))}</span></article>`).join("") || '<p>No records match these mapping filters.</p>'}
      <nav class="pagination" aria-label="Coverage record pages">${data.page>1 ? `<a href="${esc(url(params,{page:String(data.page-1)}))}#material">← Previous</a>` : '<span></span>'}<span>Page ${data.page} of ${Math.max(1,data.pages)}</span>${data.page<data.pages ? `<a href="${esc(url(params,{page:String(data.page+1)}))}#material">Next →</a>` : '<span></span>'}</nav>
      ${data.broader_context.length ? `<details><summary>${data.broader_context.length} records from broader industry context</summary><p>These are navigation leads. They are not counted as direct material for ${esc(region)}.</p><ul>${data.broader_context.map(r=>`<li><a href="/records/${esc(r.id)}">${esc(r.title)}</a> · ${r.industry_codes.map(esc).join(", ")}</li>`).join("")}</ul></details>` : ""}
    </section>
    <section class="coverage-history"><h2>Keep track of coverage</h2><p>${history.length ? `History begins with the ${esc(history[0].recorded_at)} baseline. Each snapshot preserves its corpus, topology and mapping versions.` : "The first baseline is being prepared. No historical trend is inferred."}</p>${history.length ? `<div class="coverage-table-wrap" role="region" aria-label="Coverage snapshot history" tabindex="0"><table class="coverage-table"><caption>Measured snapshots; changes in mapping method can change counts without adding research</caption><thead><tr><th>Date / snapshot</th><th>Mapping method</th><th>Records</th><th>Question families with material</th><th>Scoped assessments</th></tr></thead><tbody>${history.map(h=>`<tr><th>${esc(h.recorded_at)}<small>${esc(h.id)}</small></th><td>${esc(h.mapping_version)}</td><td>${h.summary.record_count}</td><td>${h.summary.question_families_with_material} / ${h.summary.question_families}</td><td>${h.summary.scoped_assessments}</td></tr>`).join("")}</tbody></table></div>` : ""}<p>Downloads contain the entire corpus snapshot. Exploration filters above do not narrow these files.</p><p><a href="/downloads/coverage.json">Current analytics JSON</a> · <a href="/downloads/coverage-records.jsonl">Record mappings JSONL</a> · <a href="/downloads/coverage-cells.csv">Subsector screening matrix CSV</a> · <a href="/downloads/coverage-history.json">Snapshot history</a> · <a href="/downloads/coverage-topology.json">Full topology</a></p></section>
    <details class="coverage-method"><summary>How to read and maintain this map</summary><p>${esc(data.notes.denominator)}</p><p>${esc(data.notes.associations)} ${esc(data.notes.assessment)}</p><p>${s.subsectors_with_direct_material} of 96 subsectors and ${s.detailed_industries_with_direct_material} of 1,012 detailed industries have material assigned at that exact level. ${s.assessed_subsector_question_pairs} of ${count(s.subsector_question_screening_pairs)} possible subsector/question pairs have a scoped assessment. These are mapping and review totals, not percentages of accounting knowledge.</p><p>The ${s.industry_mapped_records} records with industry associations, ${s.shared_context_records} marked as shared context and ${s.industry_unassigned_records} awaiting an industry assignment partition the current corpus. Source currency, professional review and reuse rights retain their record-level status.</p><p>Update versioned mappings and scoped assessments in the source corpus, then capture a new snapshot. The site and exports are rebuilt from the same files. <a href="/schemas/coverage.schema.json">Coverage schema</a> · <a href="/api/v1/coverage">Coverage API</a></p><p>Industry backbone: <a href="${esc(coverageTopology.industry_backbone.source_landing_url)}">US Census Bureau, NAICS-US 2022</a>. Topology ${esc(data.topology_version)}; mappings ${esc(data.mapping_version)}; assessments ${esc(data.assessment_version)}.</p></details>
  </article>`;
  return shell("Research coverage", "Explore corpus coverage across industries and accounting questions, with explicit evidence gaps and versioned analytics.", body, "coverage", "/coverage");
}
